- name: Interactive use / comfort features
  tags:
    - rke2-node
    - rke2-node.interactive
  include_tasks:
    file: interactive.yml
    apply:
      tags:
        - rke2-node
        - rke2-node.interactive

- name: Platform-specific bugware
  tags:
    - rke2-node
    - rke2-node.udp
    - rke2-node.bugware
  include_tasks:
    file: bugware.yml
    apply:
      tags:
        - rke2-node
        - rke2-node.bugware

- name: Support for NFS volumes
  ansible.builtin.apt:
    name: nfs-common
    state:
      present

- name: Rancher cluster membership
  tags:
    - rke2-node
    - rke2-node.register
  include_tasks:
    file: register.yml
    apply:
      tags:
        - rke2-node
        - rke2-node.register
