- name: Træfik front-end
  include_tasks:
    file: traefik.yml
    apply:
      tags:
        - traefik
        - træfik
  tags:
    - traefik
    - træfik
    - traefik.bluegreen
    - træfik.bluegreen
    - traefik.extra
    - træfik.extra
