gitlab_namespace: gitlab
gitlab_hostname: gitlab-next.epfl.ch
gitlab_tls_private_key: >-
  {{ tls_credentials.gitlab_next.key
          | eyaml(tls_credentials.eyaml_keys) }}

gitlab_values:
  # Documentation: https://docs.gitlab.com/charts/charts/globals/#configure-host-settings
  global:
    gitlabVersion: "{{ gitlab_version }}"
    edition: ce
    time_zone: "Europe/Zurich"
    hosts:
      domain: "{{ gitlab_hostname }}"
      gitlab:
        name: "{{ gitlab_hostname }}"
    
    ingress:
      # Reference to the existing traefik IngressClass
      class: traefik
      configureCertmanager: false
      tls:
        secretName: gitlab-next-tls

    # Documentation: https://docs.gitlab.com/integration/omniauth/#configure-common-settings
    appConfig:
      omniauth:
        enabled: true
        allowSingleSignOn: ['openid_connect_epfl', 'openid_connect_guest']
        blockAutoCreatedUsers: false
        autoLinkUser: ['openid_connect_epfl', 'openid_connect_guest']
        syncProfileFromProvider: ['openid_connect_epfl', 'openid_connect_guest']
        syncProfileAttributes: ['name', 'email']
        externalProviders: ['openid_connect_guest']
        providers:
          - secret: gitlab-epfl-provider
          - secret: gitlab-guest-provider
    
    extraEnv:
      GITLAB_LOG_LEVEL: "error"
      # Force redeploy on secret change. Chart currently does not support pod annotation
      CHECKSUM_EPFL_PROVIDER: "{{ epfl_provider | checksum }}"
      CHECKSUM_GUEST_PROVIDER: "{{ guest_provider | checksum }}"

  # Disable cert-manager because managing certificates ourselves
  certmanager:
    install: false

  # Do not create an IngressClass because traefik existing
  nginx-ingress:
    enabled: false
