# Secrets for https://github.com/epfl-dojo/GitlabStatisticsPrometheusExporter
# Required by https://go.epfl.ch/gitlab-pub-stats
#
# To edit the encrypted secrets below, you need eyaml installed.
# Familiarize yourself with
# https://puppet.com/blog/encrypt-your-data-using-hiera-eyaml first.
# The edit command goes like this,
#
#   ansible-deps-cache/bin/eyaml edit -d \
#       --pkcs7-public-key eyaml/epfl_gitlab.pkcs7.pem \
#       roles/rke2-gitlab/vars/monitoring-secrets.yml
#
# 💡 This *will not* decrypt anything for you because chances are, you
# don't need to decrypt secrets (YA RLY). For those cases where you
# do, wielding the private key from Keybase is left as an exercise to
# the reader.

eyaml_keys:
  priv: /keybase/team/epfl_gitlab/eyaml/private_key.pkcs7.pem
  pub: "{{ playbook_dir }}/eyaml/epfl_gitlab.pkcs7.pem"

# To update:
# 1. As a GitLab administrator, go to https://gitlab.epfl.ch/admin/users/GitlabStatisticsPrometheusExporter and click Impersonate
# 2. Navigate to https://gitlab.epfl.ch/-/user_settings/personal_access_tokens
# 4. Create a new token with the following settings:
#    - Token name: anything you like e.g. "Prometheus"
#    - Expiration date: one year from now (this is the maximum)
#    - Scopes : read_api, read_user, read_repository
# 5. Click the blue “Create personal access token” button
# 6. Copy the token and paste it below
# 7. Run `gitsible -t monitoring --prod`
private_token: ENC[PKCS7,MIIBqQYJKoZIhvcNAQcDoIIBmjCCAZYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAZqWiCnURc0sbEEyV/nulbsCQjxN6jBUrr0CMNNNqwK/cVO/WRduSZJxZlKk2CQrq4GHFYA2cjeMGSJMExoFQomV6o3ATBZxTAZnBO9o7zI1o2dwuSpqTauhvsO4ne1G7cPcygt29RUUD25ZG/MSGNjOFVm8L6RHsmEJNs7zOur63gYOf9j5B5E+n8Pos8QfWvWd48bTOLhXJDfikWUyxuyxTvovJcxPXUD+sf5UkgTxSK9VGZUb4/hWXMfQJ1WrUIJbxGWBGuOmSUbw7FyMEAE+r6oiyVmdm2kCHePMcF/WM5ME1DZJSq+Fknqtjbus9+EdUil5PSEGDflau+ntfoDBsBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBCZIRZSwZXSyhmt8mSsM5LJgEAQO1Jw8SM/ii4GIaCW22jHz5LK5SAE4TdYHGWqhpEQLFNVjz698GIsMxCZGYcix75s92+DYgbjr4V1kNpCN0om]
