gitlab_namespace: gitlab
gitlab_hostname: gitlab-next.epfl.ch
gitlab_tls_private_key: >-
  {{ tls_credentials.gitlab_next.key
          | eyaml(tls_credentials.eyaml_keys) }}

##############################
## gitlab helm chart values ##
##############################
gitlab_values:
  # Documentation: https://docs.gitlab.com/charts/charts/globals/#configure-host-settings
  global:
    gitlabVersion: "{{ gitlab_version }}"
    edition: ce
    time_zone: "Europe/Zurich"
    hosts:
      domain: "{{ gitlab_hostname }}"
      gitlab:
        name: "{{ gitlab_hostname }}"
    
    ingress:
      # Reference to the existing traefik IngressClass
      class: traefik
      configureCertmanager: false
      tls:
        secretName: gitlab-next-tls

    # Documentation: https://docs.gitlab.com/integration/omniauth/#configure-common-settings
    appConfig:
      omniauth:
        enabled: true
        allowSingleSignOn: ['oidc_entra_epfl', 'oidc_switch_edu_id_guest']
        blockAutoCreatedUsers: false
        autoLinkUser: ['oidc_entra_epfl', 'oidc_switch_edu_id_guest']
        syncProfileFromProvider: ['oidc_entra_epfl', 'oidc_switch_edu_id_guest']
        syncProfileAttributes: ['name', 'email']
        externalProviders: ['oidc_switch_edu_id_guest']
        providers:
          - secret: gitlab-epfl-provider
          - secret: gitlab-guest-provider
    
    extraEnv:
      GITLAB_LOG_LEVEL: "error"
      # Force redeploy on secret change. Chart currently does not support pod annotation
      CHECKSUM_EPFL_PROVIDER: "{{ epfl_provider | checksum }}"
      CHECKSUM_GUEST_PROVIDER: "{{ guest_provider | checksum }}"

    # Use external gitaly
    gitaly:
      enabled: false
      external:
        - name: default
          hostname: gitaly-gitaly
      authToken:
        secret: gitlab-gitaly-secret
        key: token

  # Disable cert-manager because managing certificates ourselves
  certmanager:
    install: false

  # Do not create an IngressClass because traefik existing
  nginx-ingress:
    enabled: false

  gitlab-runner:
    install: false
    certsSecretName: gitlab-next-tls


##############################
## gitaly helm chart values ##
##############################
gitaly_values:
  # Documentation: https://docs.gitlab.com/charts/charts/globals/#configure-host-settings
  global:
    gitlabVersion: "{{ gitlab_version }}"
    edition: ce
    time_zone: "Europe/Zurich"
    hosts:
      domain: "{{ gitlab_hostname }}"
      gitlab:
        name: "{{ gitlab_hostname }}"

    extraEnv:
      GITLAB_LOG_LEVEL: "ERROR"

    gitaly:
      enabled: true
      authToken:
        secret: gitlab-gitaly-secret
        key: token
      persistence:
        accessMode: ReadOnlyMany
        size: 1Ti
        matchLabels:
          name: repo-data

    certificates:
      enabled: true
      customCAs:
        - secret: gitlab-next-tls

    appConfig:
      object_store:
        enabled: true
        connection:
          secret: gitlab-rails-secret

    registry:
      notificationSecret:
        secret: gitlab-registry-notification
        key: secret
        
    shell:
      authToken:
        secret: gitlab-gitlab-shell-secret
        key: secret
    
    postgresql:
      persistence:
        enabled: true
        existingClaim: gitlab-postgresql-pvc
    
    redis:
      host: gitlab-redis-master
      
    # Disable non gitaly-related services
    minio:
      enabled: false
    kas:
      enabled: false

  # Disable non gitaly-related services
  certmanager:
    install: false
  certmanager-issuer:
    install: false
    email: "none@epfl.none"
  shared-secrets:
    enabled: false
  registry:
    enabled: false
  nginx-ingress:
    enabled: false
  gitlab-runner:
    install: false
  postgresql:
    install: false
  redis:
    install: false
  gitlab:
    # Gitaly : use existing PV instead of creating a new PV
    gitaly:
      persistence:
        enabled: true
        accessMode: ReadOnlyMany
        size: 1Ti
        matchLabels:
          name: repo-data
    # Disable non gitaly-related services
    webservice:
      enabled: false
    sidekiq:
      enabled: false
    toolbox:
      enabled: false
    migrations:
      enabled: false
    gitlab-shell:
      enabled: false
    praefect:
      enabled: false
