# To edit the encrypted secrets below, you need eyaml installed.
# Familiarize yourself with
# https://puppet.com/blog/encrypt-your-data-using-hiera-eyaml first.
# The edit command goes like this,
#
#   ansible-deps-cache/bin/eyaml edit -d \
#       --pkcs7-public-key eyaml/epfl_gitlab.pkcs7.pem \
#       roles/rke2-gitlab/vars/openid-secret.yml
#
# 💡 This *will not* decrypt anything for you because chances are, you
# don't need to decrypt secrets (YA RLY). For those cases where you
# do, wielding the private key from Keybase is left as an exercise to
# the reader.

# Documentation: https://docs.gitlab.com/administration/auth/oidc/
epfl_provider:
  name: "oidc_entra_epfl"
  label: "EPFL"
  args:
    name: "oidc_entra_epfl"
    strategy_class: "OmniAuth::Strategies::OpenIDConnect"
    scope: ["openid", "profile", "email"]
    response_type: "code"
    issuer:  "https://login.microsoftonline.com/{{ epfl_app_tenant_id }}/v2.0"
    client_auth_method: "basic"
    discovery: false
    # Sciper ID
    uid_field: "uniqueid"
    pkce: true
    client_options:
      identifier: "{{ epfl_app_client_id }}"
      secret: "{{ epfl_app_client_secret }}"
      redirect_uri: "https://{{ gitlab_hostname }}/users/auth/oidc_entra_epfl/callback"
      end_session_endpoint: "https://login.microsoftonline.com/{{ epfl_app_tenant_id }}/oauth2/v2.0/logout"
      authorization_endpoint: "https://login.microsoftonline.com/{{ epfl_app_tenant_id }}/oauth2/v2.0/authorize"
      token_endpoint: "https://login.microsoftonline.com/{{ epfl_app_tenant_id }}/oauth2/v2.0/token"
      userinfo_endpoint: "https://graph.microsoft.com/oidc/userinfo"
      jwks_uri: "https://login.microsoftonline.com/{{ epfl_app_tenant_id }}/discovery/v2.0/keys?appid={{ epfl_app_client_id }}"

# Documentation: https://help.switch.ch/eduid/docs/services/openid-connect/
guest_provider:
  name: "oidc_switch_edu_id_guest"
  label: "Externe"
  args:
    name: "oidc_switch_edu_id_guest"
    strategy_class: "OmniAuth::Strategies::OpenIDConnect"
    scope: ["openid", "profile", "email", "https://login.eduid.ch/authz/User.Read"]
    response_type: "code"
    issuer:  "https://login.eduid.ch/"
    client_auth_method: "basic"
    discovery: false
    uid_field: "swissEduIDLinkedAffiliationUniqueID"
    pkce: true
    client_options:
      identifier: "{{ guest_app_client_id }}"
      redirect_uri: "https://{{ gitlab_hostname }}/users/auth/oidc_switch_edu_id_guest/callback"
      end_session_endpoint: "https://login.eduid.ch/idp/profile/oauth2/revocation"
      authorization_endpoint: "https://login.eduid.ch/idp/profile/oidc/authorize"
      token_endpoint: "https://login.eduid.ch/idp/profile/oidc/token"
      userinfo_endpoint: "https://login.eduid.ch/idp/profile/oidc/userinfo"
      jwks_uri: "https://login.eduid.ch/idp/profile/oidc/keyset"

epfl_app_tenant_id: >-
  {{
  "ENC[PKCS7,MIIBmQYJKoZIhvcNAQcDoIIBijCCAYYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAvlCp6McC02BlxpRbtHjFuVOZ2kLjkUvx9V73aXJw+XotPoo2+MG9K5m3NeGIa+o/pwzoqIqjnkRRRtMjkvDHyHQzcrl6VydWcZ+ESa2vYpZRp+EpFV/YEzZzseQmg3ATykWGY/6OGxQEW5H8L9A+v0rtMibmnHXnlCskr4C0fOYplhYvyD/KnNnzIl223/HCQsrU+CBuYvCzgWrYRQ3kpTIvrEzqn25Fb3lKENqhe7mLI8Vln/gJA9It82OJifswSOkA9EoO/vfzsvaKY3xa0qCF+PXiZE0G+qKSFNuo3pAK3f/wZ1qOuiUcUHf/Pr91JFT+stcyhxLpButiei7WMTBcBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBD0dk/Xuk3UyEnKLyuELSmwgDDrHj22ag1bMyTSVnEh9DHZLkcTtbU/ddAPNHt8um27u4snjS2YDhxlcMZsoMZEen0=]"
  | eyaml(gitlab_credentials.eyaml_keys) }}
epfl_app_client_id: >-
  {{
  "ENC[PKCS7,MIIBmQYJKoZIhvcNAQcDoIIBijCCAYYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAQ/kILkCT9mtThq1vOFlEZoS5qE5jQZUqUddE7XHmQav6C8BNZyLhPJVCjbjURfpynRSb9VD8bC6I2fpsDqeTs/lrnXxoe0FJIXmvEw2MhRYRd2OwkV63rzH5OPqGjY4yYy3UWtJgE0+gtG4LUj9XzzNhBnRTrBZlI0jXYEwGNzvJzTr9wEwucFP77Y8ME6uVe+oVqK4902ibBcAkEohsVfOOLeu1WffMY8vP071zC7y/i7gNLGBaGQLVncSGRPr5lPOtp2S5RuPieLjNsUxIUyQ7G5LCwNI3AAFemfBcRA2u37BSGCVOVndkiImkxTjRApRKTbQjlBw/I73l7Z8bTDBcBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBDzRHqlRvHIIS9aMxDigN0XgDC8PBwrqZ8mksb3BvNAPh+yquOQKuJmtLLKnWlRFR5/TaUKE+Ez+xya3iqlca8+epQ=]"
  | eyaml(gitlab_credentials.eyaml_keys) }}
epfl_app_client_secret: >-
  {{
  "ENC[PKCS7,MIIBmQYJKoZIhvcNAQcDoIIBijCCAYYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAN7YTmF/tIxnb4Fm2b0JsQfArqvLKWcDyyM+4dCHvWFlrGgNziA8PosEVE6mSgeMWEODi1pLM7UBQXptae3tkK7UQDLDiEJ2psudnw4A2/pfOxEi1iq092SjBwAMTpGzrsoVjP0/TEHHrll21aIFscrSUHJ/WAcoeSeNT1KQr4DF46KciPRonPYjw2cDKx6gBNAQLCc0jnJl4LK9CFwoLboUYF5wPzz99BqZr2sLkoGaXwr6NTW8WAIK3QXayfu2Re9UWYfqQIgp7DOzD/Ccgm6jzfyWkweHHvsacozw/1hCYc1ROl9uAYSY64BgGUaIE6GEeRs0yRjanzwXcuP9LyTBcBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBAYZpZB6RM+qZAbjaPJjkfLgDD4nesiTGCaDEUCAu73e/HbcWHP33Nn9JY/7QNsyyBCGZhb43oVYcoYaJDFMcuygRw=]"
  | eyaml(gitlab_credentials.eyaml_keys) }}
  
guest_app_client_id:  >-
  {{
  "ENC[PKCS7,MIIBiQYJKoZIhvcNAQcDoIIBejCCAXYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAIS8NofY72vJntC+a0Kfho5RhRHgl8M2VFRyyVaaeKR7e/HNDEbXkvAFy8vSHo21h9Ts6S0Nh9T0r5+Al+3ImLVa6tLBlCY/Es3WRxnvzkcomX5Jigfhn2CbEP5H/tM23OViF0a8e+cbRLJFbbtW2ATrfTihY1usHmd99CA22Sii3DKu3GduloWjq6GEfpVpv0ZHNGe/EcGrx5NYhSmAtByjXY3XUv2xFZv1DMBxm0bVxFIBSzHDa1Fqb5fuv0Q8D6ArTu4HuUV8xTBkzGbJ6y8laV3A6M6nRP+56IQf5UXfrl9HwkHvXxZ3/MCLqEduQijP9wQI8Wp9kpAEVUqGtFzBMBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBCSlELTQKznzwYvyVLQ+Y/pgCCzwUGsT+HMfMG3xecRQtVlyNuNm9AOT2g37bib/NdfPw==]"
  | eyaml(gitlab_credentials.eyaml_keys) }}
  