# Documentation: https://docs.gitlab.com/administration/auth/oidc/
openid_provider:
  name: "openid_connect"
  label: "Azure OIDC"
  args:
    name: "openid_connect"
    scope: ["openid", "profile", "email"]
    response_type: "code"
    issuer:  "https://login.microsoftonline.com/{{ app_tenant_id }}/v2.0"
    client_auth_method: "basic"
    discovery: false
    uid_field: "preferred_username"
    pkce: true
    client_options:
      identifier: "{{ app_client_id }}"
      secret: "{{ app_client_secret }}"
      redirect_uri: "https://{{ gitlab_hostname }}/users/auth/openid_connect/callback"
      end_session_endpoint: "https://login.microsoftonline.com/{{ app_tenant_id }}/oauth2/v2.0/logout"
      authorization_endpoint: "https://login.microsoftonline.com/{{ app_tenant_id }}/oauth2/v2.0/authorize"
      token_endpoint: "https://login.microsoftonline.com/{{ app_tenant_id }}/oauth2/v2.0/token"
      userinfo_endpoint: "https://graph.microsoft.com/oidc/userinfo"
      jwks_uri: "https://login.microsoftonline.com/{{ app_tenant_id }}/discovery/v2.0/keys?appid={{ app_client_id }}"

app_tenant_id: >-
  {{
  "ENC[PKCS7,MIIBmQYJKoZIhvcNAQcDoIIBijCCAYYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAvlCp6McC02BlxpRbtHjFuVOZ2kLjkUvx9V73aXJw+XotPoo2+MG9K5m3NeGIa+o/pwzoqIqjnkRRRtMjkvDHyHQzcrl6VydWcZ+ESa2vYpZRp+EpFV/YEzZzseQmg3ATykWGY/6OGxQEW5H8L9A+v0rtMibmnHXnlCskr4C0fOYplhYvyD/KnNnzIl223/HCQsrU+CBuYvCzgWrYRQ3kpTIvrEzqn25Fb3lKENqhe7mLI8Vln/gJA9It82OJifswSOkA9EoO/vfzsvaKY3xa0qCF+PXiZE0G+qKSFNuo3pAK3f/wZ1qOuiUcUHf/Pr91JFT+stcyhxLpButiei7WMTBcBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBD0dk/Xuk3UyEnKLyuELSmwgDDrHj22ag1bMyTSVnEh9DHZLkcTtbU/ddAPNHt8um27u4snjS2YDhxlcMZsoMZEen0=]"
  | eyaml(gitlab_credentials.eyaml_keys) }}
app_client_id: >-
  {{
  "ENC[PKCS7,MIIBmQYJKoZIhvcNAQcDoIIBijCCAYYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAwvvTCqvdKo1LiB6/D1Ccx/0tn/anIuUkcfszWp0/Af5yZuN9d72IMjDvcwLETFKqf/EROwHTdqi/VupXX3Fi4Xug4q2KyIvA7i8hoK1qrRiASHEWKovV3j+ayHB6Nw62sL4sWSeivFUKKNWqi1K/zrD6KVvkyWkQNwN+UJQZE/CWZEJ7nXHlHldUp41SEQJXx6p9mNAAKea1zFCUv6rGYp1NpAer0WRvIwlK9U9QWn+4u6PNzlxEYZhldHBKISgqKOI2EZ74oQrRoesNDuYQCXHwmjTuEz/VVs4mpKJhnjQBrQXX9zo7aRPbv7+rWZ9UXvXiDo6TGbu+7Id3HkgJNjBcBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBA8wq5h/OfU9DNWBiGF3F28gDAhh3of+7wYl4j7Od4YTo7CFxrRoFnP5Lee5juuHKiu1GIhnsKe4Y8SreNn2/Xi/xo=]"
  | eyaml(gitlab_credentials.eyaml_keys) }}
app_client_secret: >-
  {{
  "ENC[PKCS7,MIIBmQYJKoZIhvcNAQcDoIIBijCCAYYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAllFWNLLy+kgfnjqVJ/Dr0PtdeGRhi82+tauXfhgknEiE4DZ3I9w3aBWcBq3wOQqSj0rMX6ZAmWiTFZfdrxL9HjNsHZXYNRytR63s32Q4BfIc3CCfBaddg3veispJOV4N1dMh7F0xotV7KktblfK+OkKCpW2zd3uEBNlZ7TfqUd2j2+5SAZiuv5nJ+Rn4sZSdi8BdlI618gJmxcGemyOvrnouXPiClmh1oYqVnEqMs8jEvL7+qHm9phhqWTLpyrS1PTtyklOy2ZA3RAcK/hZqL2LRoDLhgbURQHwHQB0P2IuzTlyTgtW7hsDLsiseK8YACQQ7Otr2k41ThyDVJIhLMjBcBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBD1a9Bgw35r9g68ZqaMKqmKgDDAAdBjBnukNe7SEZa5OmLsHcyw4XmGKdmMjNO/do6mJY9hNvsFcqXfc6eLvudASHY=]"
  | eyaml(gitlab_credentials.eyaml_keys) }}
