# To edit the encrypted secrets below, you need eyaml installed.
# Familiarize yourself with
# https://puppet.com/blog/encrypt-your-data-using-hiera-eyaml first.
# The edit command goes like this,
#
#   ansible-deps-cache/bin/eyaml edit -d \
#       --pkcs7-public-key eyaml/epfl_gitlab.pkcs7.pem \
#       roles/rke2-gitlab/vars/postgres-secrets.yml
#
# 💡 This *will not* decrypt anything for you because chances are, you
# don't need to decrypt secrets (YA RLY). For those cases where you
# do, wielding the private key from Keybase is left as an exercise to
# the reader.

eyaml_keys:
  priv: /keybase/team/epfl_gitlab/eyaml/private_key.pkcs7.pem
  pub: "{{ playbook_dir }}/eyaml/epfl_gitlab.pkcs7.pem"

postgres:
  prod:
    username: gitlab
    password: ENC[PKCS7,MIIBuQYJKoZIhvcNAQcDoIIBqjCCAaYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAWdxooHDOE8vngWXW+j0f0jIQ2l/pjv5Yz8708Xj9ueQDWn6urGUAzUB8FNDi06IwYbpDjp8diq9DZNX/qfSqRHdY5tLOCFub+haJHbKlQktv9xN6whfjFMw4NjXvE3oft6jGJ91TpdjifOLg5RjJXhhZaYttPsKVpnxlZxLOJ4wansv5RE3uFEuh7bF/8FmqDSQ1pE4VU9v889uYyLr5+PnXFuNFFbSl7yCGktIej9lm98Fyg4NKHxll3BjtH8dWecTRekxlXY5HVaRdXamLXfOGJZvup95sVrElBTGgclxKxbueU8xR8owxXwsKekEPSRJl7nawNkIpn68v2l9fUzB8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBCEeTVESLPUrkFLl5M4VYLvgFBSYt5CiFc/a2fsMP5nV1TtAafuxZwxOIoaEIW3qSjCXocB4cS3aoLAIfONI2tfciZbMNfNxeMy8KXPPQgCouJp1JmyJGt+c6WjFBSEeM/IAg==]
  test:
    username: gitlab
    password: ENC[PKCS7,MIIBuQYJKoZIhvcNAQcDoIIBqjCCAaYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAbMUu0HZHUL0oyzR7LXYkipUQzBP651GNiBiJk+t2KZvSbAIRcOuZmP/EG6fBFrFVZPSKEtMK3oTW1OGX60HjILovGGGqe8z630Vspd2Ik/atNX5dzWyfQ3Em7MftvnjhHLZxcMeMqEJC96sJdGb2/b+ZY367F/0yzcFQs4hpuD3fuBujuJtiRVjRWDvs6ZvcSYTJUj2170Rgb5azFWGqPOs2MaWIE0VYoFcldqu9tZdbJCEJR8noGCTLhPiD76svE3N6dfaUPO/WTYkHaPGeJP71r3u52AynaEogRXUyxza6/BfKuUkTIyy73a4iAfWipYwR7k3zc9pUgD+VX6dCZjB8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBDH3PWp7ktj2s8z8Q0OVym0gFD1ngEIgfLYGnQJqhNiZcUYTozw4qw3UOgP9XkYzG8IC3BqgYLa4gMFUE9QErXgshoZKkUpCNfc2GHdDDjPqtrta4X1t4Ay0U9RzGouhrKWLw==]
