pg_main_rails_database_name: gitlabhq_production

pg_password_secret_key_ref:
  name: >-
    {{ "postgres-prod-passwords"
    if inventory_deployment_stage == "test"
    else "gitlab-postgresql-password" }}
  key: postgresql-postgres-password
