# To edit the encrypted secrets below, you need eyaml installed.
# Familiarize yourself with
# https://puppet.com/blog/encrypt-your-data-using-hiera-eyaml first.
# The edit command goes like this,
#
#   ansible-deps-cache/bin/eyaml edit -d \
#       --pkcs7-public-key eyaml/epfl_gitlab.pkcs7.pem \
#       roles/rke2-gitlab/vars/runner-credentials.yml
#
# 💡 This *will not* decrypt anything for you because chances are, you
# don't need to decrypt secrets (YA RLY). For those cases where you
# do, wielding the private key from Keybase is left as an exercise to
# the reader.

eyaml_keys:
  priv: /keybase/team/epfl_gitlab/eyaml/private_key.pkcs7.pem
  pub: "{{ playbook_dir }}/eyaml/epfl_gitlab.pkcs7.pem"

# Runner runs in Rancher and polls work for this GitLab repository from gitlab.com's API.
# Token obtained as per https://docs.gitlab.com/tutorials/create_register_first_runner/
runner:
   token: ENC[PKCS7,MIIBiQYJKoZIhvcNAQcDoIIBejCCAXYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAQwvuszux42A3T5zXLv5mNwzNCbgi1ulowWqb4JhBhrmWRGD3fSY81TedZGG8Y0nsrIrs+UG7K+FRBuTjntv2QkCY95bL6J7bB6Ypa6mymdp0XTV27fbPl4rvtipuBPakL3/QPUuidjy01D3EyGa6tGOCHfrYl+XdzJIjm19hNc9MM36d9M/+Q8JuIC1yrL9VvLcXUCPOXwEvzFhMHktH9l/OKF6zicRiPd0MB8GsILvwAcf/Er9KO+cyGjoqnatGHG7EbBML5AbJWJ9bB9nAu/V8f0FhKwv2Wykhyw2mD8NQhOVMztlkA4H9STmcsFSpe2ffapRiq+ItX0AGxh6W4DBMBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBDL29/I1WRsTFiQLv1iA+FigCCp6DDha3agzWH7hJ33Px46qGbI6aOuajnUrdyoj2tDmQ==]

# ../../../.gitlab-ci.yml uses this both to pull the images that run
# its scripts, and to push the images it builds.
# The so-called “robot account” object in Quay that owns these credentials
# lives at https://quay-its.epfl.ch/organization/svc1160?tab=robots
quay_builder_robot_account:
  name: svc1160+builder
  token: ENC[PKCS7,MIIBuQYJKoZIhvcNAQcDoIIBqjCCAaYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAt0V0m2EHgaRrJkSRx1/z46lRxIvODJ6KhBn6GIPGwbk8w4BzUXRE0wi3IAZgpGuTAIWHHFggro9v1U0cTIfNRXpU1ckqF9zGHkoJPdVekzF+9Zfaiwl6GhQ1OkQmso/9UFk2avDdelZzpE5GTPHWbDWuN/rVoCwcY5T0EyN9CCa900jQrs/D/aO4biYLcn6GdW6ofuSw9RN8lV5IsXRo7ULl7SGyEKnc5SejjMAS3Z+wtyLH8a727hqWK2FUVH1RqszayDsr9D2N/GA8dTrV+AjVAPurRwJX81peGmy6TXgN7DIVqrCMXTGDVRADg92Oj2bIzP8O7CYMUmyE5bXiYDB8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBB7y1LArgqd9EHl+dDhuJVPgFBv6h5TsH6rXvuVjKtZrJGmA7QruKoKAOOPIswbUELaXJ0u0tGVu2rAwqbXo8wpe2xHDLyeAhN5cT7qh0jzyHb8LuRyBLdvvoGxqk4O8KECnQ==]

quay_api:
  # Quay API token that Ansible wields to create mirrors etc.
  # To regenerate this token:
  # (paraphrased from https://docs.redhat.com/en/documentation/red_hat_quay/3/html-single/red_hat_quay_api_guide/index#token-overview)
  #
  # 1. Browse https://quay-its.epfl.ch/
  # 2. **Make sure to log out and then back in.** Some token manipulation steps require either
  #    that you have a fresh (less than a few minutes old) session, or that you type in your
  #    password to re-autenticate. Unfortunately the latter will *not* work on quay-its.epfl.ch,
  #    no matter what. (Mumble LDAP something something)
  # 3. Browse https://quay-its.epfl.ch/organization/svc1160?tab=applications
  # 4. (If not already done) Create the `Ansible` application. Click the “Create New Application” button in the upper right corner; type in Ansible and press Enter.
  #
  #    💡 If you get prompted for a password at this time, it means that you didn't read
  #    the above instructions carefully. Sorry about that.
  # 5. Click the `gitlab-runner` hyperlink
  # 6. In the left sidebar, click Generate Token (pictured by a cinema ticket)
  # 7. Check the “Administer Repositories”, “Create Repositories” boxes and leave all others unchecked.
  # 8. Click the Generate Access Token button (green) at the bottom
  # 9. Click Authorize application
  # 10. A token should appear. If it doesn't, see 💡, above.
  bearer_token: ENC[PKCS7,MIIBmQYJKoZIhvcNAQcDoIIBijCCAYYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEADigo7L1oGfrxc7pcbK3tq4tbh0oCoh4F3+iCLyYrdFgDRf7E3aZogR99slDSp17+FELHICoisOoBT2qemZW7Gg6BvQDtgLTA72WZ4HoNLdnyrUDY+TzqYGHzNJunkKXCbohWTsZnY9s1iN/29G16opRwBNjuSWRKiXweTtVUbYi9XPKiqRUQk5yceq4I0tBDcSnStEgHPpTCS6Rb+XQALCBSeCZxPNim8UhpH4dvX9e77hsBPCSgTxJv4fsYwnSmpzQdD2xuGqdAWrFmCUUsMr4Kb+xqd2v98wdljRETgARUqDu3rg/CfJJXpBmfnUdoyjMykxexuiHPg3W+u35ziTBcBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBDrHIpAd5rswaSaMuWsSIbRgDAE7ftw+dXVSxzaqKv7cP0/UsY5snH8paNJNwne4WAnCpRR9a5BAf8Ij5iBJ9Lbzy8=]
