# To edit the encrypted secrets below, you need eyaml installed.
# Familiarize yourself with
# https://puppet.com/blog/encrypt-your-data-using-hiera-eyaml first.
# The edit command goes like this,
#
#   ansible-deps-cache/bin/eyaml edit -d \
#       --pkcs7-public-key eyaml/epfl_gitlab.pkcs7.pem \
#       roles/rke2-gitlab/vars/tls-credentials.yml
#
# 💡 This *will not* decrypt anything for you because chances are, you
# don't need to decrypt secrets (YA RLY). For those cases where you
# do, wielding the private key from Keybase is left as an exercise to
# the reader.

eyaml_keys:
  priv: /keybase/team/epfl_gitlab/eyaml/private_key.pkcs7.pem
  pub: "{{ playbook_dir }}/eyaml/epfl_gitlab.pkcs7.pem"

gitlab_next:
  key: ENC[PKCS7,MIIIHQYJKoZIhvcNAQcDoIIIDjCCCAoCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAtkpAh9g0w6z4E9n2AHxboRbbJIbDTlPR/QwEQCew048GKBikIAK0T8P2xnh/iirzLqtQfEZqabzYEy+/s9r71+IJLm8AG+osAh5Whi914H7fBeyVYC1OyiLKunf8shfKJumoVTjkm+Thb7wL5pPxQ79kuNQ91nc088a75PKSAe0B6ZAEqgwN5jNAAQkQz63vTmtrpAQb8sEbr9RLD+ikRKoteRHiuDxNBLDTlhYXeB3StWOgUSbgCDYQnmeL1Rm5c4FzfCEDIHkWij39GQortkXTEHNEpNpcbxXGlIy9Nx+FRwisEQyNKU9Ku81JaqOx9qWqfZbq5Nik3pWx/wGtBzCCBt4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEGKJmdUw5/MNoJ0B9+i7/9CAggawyRNkyxqAz6zIYSWKKyZgGQwa7503ninLYk9ZnbwRNdE5nd7Nf/A09mZ54mKuU9+IEwy1ecSQ+Omku0N43TWfpsafpXPtNaFzVLhROMfkhdxCGeLkmwREkpWoMB28SBEJCHnB+UYst1c915OErSy0L+E8RhqT8pYivK9J9yKOU6KMHzpw+APYRdFKqyCd4XN3245OR5In1WLSWEYoZSNhjmUW4GXju7MlDyzN4SsB5rb3DJfFEji2U9+ggufANt/ZfVk7wvzISUe7xrwqqlp54F2G8PFwH3FJ3+mbFVqaq+DyUHj8uCCRBWOI8wfTxRg1RWkGiSu3EPY054tsmCwg3npNQjPVnMyT9Vi5jV7WiF9zcVS37TbgK2tG5hRwnfHFmaouH3ay1SFait/fZDvmOKC3QDV7YeD32opGqLd9BpM1ySBtlILhLpOr3OaKLEkZSniZNCZIic6+NdwYug5dtrVPzs9C0sOcvCLc3cXm7/qwSedEZQuNL3uZJd+BRVabvvnmL8fh+SUMxAl/TFYkp2g02CeWnS4Ene+Gu+CMc/Me7h/A7FJFqy9FdTJdprmZRCUJkUbhobLYSQZAbkNaIkeDjArK95qEAun377XAAiFIRWjeVbKetjCB/ZZnbczFhWS7xY9av29vQTkqR3QZrLmCl+w6UxvFtkrHOvkKdr6CYtTj+ByG7jBd8jwjup9X+3UB9jOFsucQJA/Et0pM2sd4I+kbYCCpqGTu0QWO7UsdVOPssIW9keBzhhWd7roUlsXJbR5X6EORJF3FT6sH5VmqPaIVXbKUu1O729xawCWguOYQsy/p5cEYaViHqZEQWQlC7tXbYVpTGWSBURIaIUnNJnKAfXfEJyZlmPy4/HMHbPeuVzI6a69Yyg1b494jU8tzVU0Fkm0bkSEv96363U+25/bBHXkjDQE55+T2hqKJVQ6B9E9ntVJ/s7Of8h7CpwAwj5IzLY7ArngLYZ36FWK09UONX1lZGWzJC3a64BgPkMSwDTir6CTlghAzdiUIlpiM/MGwrv/cDDegBUGomrnCzPKfRw03Ga50vamyNI7zReM6qD9bHniCeI+5JylmUhVAqlSbA2dvX2qMEe42Us+Lk3w/cyKmZPLHfHydmrozEGNhlQIiy4liH3HwwJ/5V32S1Jbto7n7StzPmg3Sbp2tDNpFsVPgbGYT3+tB5Xp9AZSvjeVBQmsTOmqJ0qucenVawr3Pv0474ZE722H2oAcLeOnChlSTsEdU9ANaqRu++VIbHoBca/f+CxmQdu3+8rAeT1bUwBD5tzNDpNJHrpCYiy5NL8fJ2V4BUYhX0F1vPvaN5gVFrY3mq70+oyfjZjHQ9VOvTXnu7mKvkgJXEGnRwku1eMgO4vd8+hGKOhZymhvnuP9wZPHlD48PaagsXiuijPwRTqPoXvkqEYMnW/lg5y3ZVn/1eidUq9dnIrNtz3Qh9AdfN6hXERMwXxT55fjIUwWSNfPo7Rt0ZU2Fr7LeRdkS6iSDhPN4fiEmnIg8NRRdNhrrFyaYpEfMLYI5Dsyg0i8pLAyMx7g4s5OPnztCO+MGIfcSWlM6LNxoBJJisbamYMVH+ZMz40kfwHxshcjmu2vbnFed0ps4eQqsa2FgC0uUQrc1u8ANbm6oTJdq7G/NNu9r9RkhlBRhqcgMUvalyhGYgN15e633H10cQRhy+dRlnITu2hLNqSop+lN4u7oaEYe0ljCt80Jd8r8t9nBlVhvJqFREW4vzGxEb2lwlCtFl/lkP+wd6lHNv5d47f+kIbOiVQ+c54l9ywxfBFmraWnRepwb9nWe+guC510zp9BAlgl6opPwLKYgU0qb4b1G9645gvbvqxEojqFk9kOUSi8jTjheTQy4/0NreRhd53wkjKq3moFd0PGAyyBhycJjrayFKz9I665MJ/TDmdgLlTVm3MQHR7440vs5eWSsscQ060uhfy9lp3plvoUDiXLX2V4NUEnkcSunuyVwcPekPOALXA/BRf+bgYb2eREAGs5iZheAS5Sji8CTMczAKi9qWlzkHTAvP2Wyut2OvQUL8+xTuYgYN+gtqohjUfjr0ymhNMDSuITRUqzUPjEAIDui7A3lTWe+UV31VTjGIa9w3e/nYehOuPxt+DrXmNxuOjlXMfaaoHVYD8EaJrya+0sDSeGmsRpWGj9HsByfXwe5j+icTa3+hwAc3yPduzqpMMmytUvPpiCivZhI/uzDfzQ4Ho+RF2hF7r7qOTnWSUWdoISU3XBbWpcPAkSlQ3g5Z5+NfbmtJAx9YiO2+zUg=]
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIG6TCCBdGgAwIBAgIQBiUUZtTkdVKL1Osm5wy5/TANBgkqhkiG9w0BAQsFADBZ
    MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMTMwMQYDVQQDEypE
    aWdpQ2VydCBHbG9iYWwgRzIgVExTIFJTQSBTSEEyNTYgMjAyMCBDQTEwHhcNMjUw
    NDEwMDAwMDAwWhcNMjYwNDA5MjM1OTU5WjB0MQswCQYDVQQGEwJDSDERMA8GA1UE
    BxMITGF1c2FubmUxNDAyBgNVBAoMK8OJY29sZSBwb2x5dGVjaG5pcXVlIGbDqWTD
    qXJhbGUgZGUgTGF1c2FubmUxHDAaBgNVBAMTE2dpdGxhYi1uZXh0LmVwZmwuY2gw
    ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC7+ww6aj9noMpJo4kPMpah
    7W1/HTxnUwGyOzo7ZBTobTfMOTwhkRlXP7eRoiKmKU0j0nCr0FxprlSsyW0bpnx2
    dmZtCtcnQnTrXcqXwMJdHYE6rqRhirEBvZQhucgE99ic27JtRKZayzw9N/jjWxjG
    7IAVHnw5DlVvJgE+6S+Jxwdd4LRRntm/bMxPkJkeYBB5LVkbRe496yKBh5Bz0k2I
    BK+86fSimTBCXhl8YY1nJLMbx0tlG8nqZoZrQcbZFCm7xQhxCoWVAZmcicg3GgQr
    qXd5dfGf3jsh421q8xuzTFFMhpDZEksFQNGasJvfSCNegTX0DbveBSUMtrwO+q+D
    AgMBAAGjggOQMIIDjDAfBgNVHSMEGDAWgBR0hYDAZsffN97PvSk3qgMdvu3NFzAd
    BgNVHQ4EFgQUJbMbu0dFRkHO6BPBYYH7h3y2HOMwHgYDVR0RBBcwFYITZ2l0bGFi
    LW5leHQuZXBmbC5jaDA+BgNVHSAENzA1MDMGBmeBDAECAjApMCcGCCsGAQUFBwIB
    FhtodHRwOi8vd3d3LmRpZ2ljZXJ0LmNvbS9DUFMwDgYDVR0PAQH/BAQDAgWgMB0G
    A1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjCBnwYDVR0fBIGXMIGUMEigRqBE
    hkJodHRwOi8vY3JsMy5kaWdpY2VydC5jb20vRGlnaUNlcnRHbG9iYWxHMlRMU1JT
    QVNIQTI1NjIwMjBDQTEtMS5jcmwwSKBGoESGQmh0dHA6Ly9jcmw0LmRpZ2ljZXJ0
    LmNvbS9EaWdpQ2VydEdsb2JhbEcyVExTUlNBU0hBMjU2MjAyMENBMS0xLmNybDCB
    hwYIKwYBBQUHAQEEezB5MCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5kaWdpY2Vy
    dC5jb20wUQYIKwYBBQUHMAKGRWh0dHA6Ly9jYWNlcnRzLmRpZ2ljZXJ0LmNvbS9E
    aWdpQ2VydEdsb2JhbEcyVExTUlNBU0hBMjU2MjAyMENBMS0xLmNydDAMBgNVHRMB
    Af8EAjAAMIIBfwYKKwYBBAHWeQIEAgSCAW8EggFrAWkAdwAOV5S8866pPjMbLJkH
    s/eQ35vCPXEyJd0hqSWsYcVOIQAAAZYfs6kPAAAEAwBIMEYCIQDi/4qfRXGq23aZ
    5+gmouLws3ec5SpbGEPQma5yOw+YpwIhAOBrvuaLGnxWoHBAms9reVNkOMz84iHN
    JF4MMIZhTLm0AHYAZBHEbKQS7KeJHKICLgC8q08oB9QeNSer6v7VA8l9zfAAAAGW
    H7Oo0wAABAMARzBFAiEAvCzmUwCd0eBiYpi95B6myFi/zH76mq/8MKETspR7DS0C
    IBtqe3SENkKbhVrBsa+y7LjPbbgEoiwOCuL2o5H5kv8lAHYASZybad4dfOz8Nt7N
    h2SmuFuvCoeAGdFVUvvp6ynd+MMAAAGWH7Oo2gAABAMARzBFAiB+g0An4ETy2N+9
    GBXSi2bwRefdh8tZaUP0xoJjbhct8wIhAINU4EoqJZzV9sxZ+jgbl3v1XOL5hx2v
    evit9kEg/JGeMA0GCSqGSIb3DQEBCwUAA4IBAQC9ZOTKcOQ+LsWhekXJ/TjyDPnH
    VGLZbJecjhevnO24+NtPfpJKV38TskEQkV9Td/6F2ZlTzwQFf1KLiXKy6b6OOfxz
    qVJoxaWbz/fL9E4QYOqXvB74kCxDZOUNs+JYr9eFlRU+sJ0nLDpb58cg+tfXx/GZ
    6760YnBVSz9Jj50kPX4w8xoAOTUBHu14fxHXc90giYvBdVYpqzi2B39HGWlcK6W0
    PXpQWvjGCzuOzfa2KlQF7ezgdWvJYAsTLwTmEa+wNwoR38EQP173Xw/DwTegsMpx
    JMEVkc6vJGCxg1OdJkJWr1r62MvYdxbHrDblXTxakHUuK6BOPkUMAgFf85f5
    -----END CERTIFICATE-----
