# To edit the encrypted secrets below, you need eyaml installed.
# Familiarize yourself with
# https://puppet.com/blog/encrypt-your-data-using-hiera-eyaml first.
# The edit command goes like this,
#
#   ansible-deps-cache/bin/eyaml edit -d \
#       --pkcs7-public-key eyaml/epfl_gitlab.pkcs7.pem \
#       roles/rke2-gitlab/vars/tls-credentials.yml
#
# 💡 This *will not* decrypt anything for you because chances are, you
# don't need to decrypt secrets (YA RLY). For those cases where you
# do, wielding the private key from Keybase is left as an exercise to
# the reader.

eyaml_keys:
  priv: /keybase/team/epfl_gitlab/eyaml/private_key.pkcs7.pem
  pub: "{{ playbook_dir }}/eyaml/epfl_gitlab.pkcs7.pem"

gitlab_next:
  key: ENC[PKCS7,MIIIHQYJKoZIhvcNAQcDoIIIDjCCCAoCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAtkpAh9g0w6z4E9n2AHxboRbbJIbDTlPR/QwEQCew048GKBikIAK0T8P2xnh/iirzLqtQfEZqabzYEy+/s9r71+IJLm8AG+osAh5Whi914H7fBeyVYC1OyiLKunf8shfKJumoVTjkm+Thb7wL5pPxQ79kuNQ91nc088a75PKSAe0B6ZAEqgwN5jNAAQkQz63vTmtrpAQb8sEbr9RLD+ikRKoteRHiuDxNBLDTlhYXeB3StWOgUSbgCDYQnmeL1Rm5c4FzfCEDIHkWij39GQortkXTEHNEpNpcbxXGlIy9Nx+FRwisEQyNKU9Ku81JaqOx9qWqfZbq5Nik3pWx/wGtBzCCBt4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEGKJmdUw5/MNoJ0B9+i7/9CAggawyRNkyxqAz6zIYSWKKyZgGQwa7503ninLYk9ZnbwRNdE5nd7Nf/A09mZ54mKuU9+IEwy1ecSQ+Omku0N43TWfpsafpXPtNaFzVLhROMfkhdxCGeLkmwREkpWoMB28SBEJCHnB+UYst1c915OErSy0L+E8RhqT8pYivK9J9yKOU6KMHzpw+APYRdFKqyCd4XN3245OR5In1WLSWEYoZSNhjmUW4GXju7MlDyzN4SsB5rb3DJfFEji2U9+ggufANt/ZfVk7wvzISUe7xrwqqlp54F2G8PFwH3FJ3+mbFVqaq+DyUHj8uCCRBWOI8wfTxRg1RWkGiSu3EPY054tsmCwg3npNQjPVnMyT9Vi5jV7WiF9zcVS37TbgK2tG5hRwnfHFmaouH3ay1SFait/fZDvmOKC3QDV7YeD32opGqLd9BpM1ySBtlILhLpOr3OaKLEkZSniZNCZIic6+NdwYug5dtrVPzs9C0sOcvCLc3cXm7/qwSedEZQuNL3uZJd+BRVabvvnmL8fh+SUMxAl/TFYkp2g02CeWnS4Ene+Gu+CMc/Me7h/A7FJFqy9FdTJdprmZRCUJkUbhobLYSQZAbkNaIkeDjArK95qEAun377XAAiFIRWjeVbKetjCB/ZZnbczFhWS7xY9av29vQTkqR3QZrLmCl+w6UxvFtkrHOvkKdr6CYtTj+ByG7jBd8jwjup9X+3UB9jOFsucQJA/Et0pM2sd4I+kbYCCpqGTu0QWO7UsdVOPssIW9keBzhhWd7roUlsXJbR5X6EORJF3FT6sH5VmqPaIVXbKUu1O729xawCWguOYQsy/p5cEYaViHqZEQWQlC7tXbYVpTGWSBURIaIUnNJnKAfXfEJyZlmPy4/HMHbPeuVzI6a69Yyg1b494jU8tzVU0Fkm0bkSEv96363U+25/bBHXkjDQE55+T2hqKJVQ6B9E9ntVJ/s7Of8h7CpwAwj5IzLY7ArngLYZ36FWK09UONX1lZGWzJC3a64BgPkMSwDTir6CTlghAzdiUIlpiM/MGwrv/cDDegBUGomrnCzPKfRw03Ga50vamyNI7zReM6qD9bHniCeI+5JylmUhVAqlSbA2dvX2qMEe42Us+Lk3w/cyKmZPLHfHydmrozEGNhlQIiy4liH3HwwJ/5V32S1Jbto7n7StzPmg3Sbp2tDNpFsVPgbGYT3+tB5Xp9AZSvjeVBQmsTOmqJ0qucenVawr3Pv0474ZE722H2oAcLeOnChlSTsEdU9ANaqRu++VIbHoBca/f+CxmQdu3+8rAeT1bUwBD5tzNDpNJHrpCYiy5NL8fJ2V4BUYhX0F1vPvaN5gVFrY3mq70+oyfjZjHQ9VOvTXnu7mKvkgJXEGnRwku1eMgO4vd8+hGKOhZymhvnuP9wZPHlD48PaagsXiuijPwRTqPoXvkqEYMnW/lg5y3ZVn/1eidUq9dnIrNtz3Qh9AdfN6hXERMwXxT55fjIUwWSNfPo7Rt0ZU2Fr7LeRdkS6iSDhPN4fiEmnIg8NRRdNhrrFyaYpEfMLYI5Dsyg0i8pLAyMx7g4s5OPnztCO+MGIfcSWlM6LNxoBJJisbamYMVH+ZMz40kfwHxshcjmu2vbnFed0ps4eQqsa2FgC0uUQrc1u8ANbm6oTJdq7G/NNu9r9RkhlBRhqcgMUvalyhGYgN15e633H10cQRhy+dRlnITu2hLNqSop+lN4u7oaEYe0ljCt80Jd8r8t9nBlVhvJqFREW4vzGxEb2lwlCtFl/lkP+wd6lHNv5d47f+kIbOiVQ+c54l9ywxfBFmraWnRepwb9nWe+guC510zp9BAlgl6opPwLKYgU0qb4b1G9645gvbvqxEojqFk9kOUSi8jTjheTQy4/0NreRhd53wkjKq3moFd0PGAyyBhycJjrayFKz9I665MJ/TDmdgLlTVm3MQHR7440vs5eWSsscQ060uhfy9lp3plvoUDiXLX2V4NUEnkcSunuyVwcPekPOALXA/BRf+bgYb2eREAGs5iZheAS5Sji8CTMczAKi9qWlzkHTAvP2Wyut2OvQUL8+xTuYgYN+gtqohjUfjr0ymhNMDSuITRUqzUPjEAIDui7A3lTWe+UV31VTjGIa9w3e/nYehOuPxt+DrXmNxuOjlXMfaaoHVYD8EaJrya+0sDSeGmsRpWGj9HsByfXwe5j+icTa3+hwAc3yPduzqpMMmytUvPpiCivZhI/uzDfzQ4Ho+RF2hF7r7qOTnWSUWdoISU3XBbWpcPAkSlQ3g5Z5+NfbmtJAx9YiO2+zUg=]
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDHzCCAgegAwIBAgIUEBSY95RpIrP5HnZj4IWeYzBzmvcwDQYJKoZIhvcNAQEL
    BQAwHjEcMBoGA1UEAwwTZ2l0bGFiLW5leHQuZXBmbC5jaDAgFw0yNTA0MDExNzUz
    MjZaGA8yMDUyMDgxNzE3NTMyNlowHjEcMBoGA1UEAwwTZ2l0bGFiLW5leHQuZXBm
    bC5jaDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALv7DDpqP2egykmj
    iQ8ylqHtbX8dPGdTAbI7OjtkFOhtN8w5PCGRGVc/t5GiIqYpTSPScKvQXGmuVKzJ
    bRumfHZ2Zm0K1ydCdOtdypfAwl0dgTqupGGKsQG9lCG5yAT32Jzbsm1EplrLPD03
    +ONbGMbsgBUefDkOVW8mAT7pL4nHB13gtFGe2b9szE+QmR5gEHktWRtF7j3rIoGH
    kHPSTYgEr7zp9KKZMEJeGXxhjWcksxvHS2UbyepmhmtBxtkUKbvFCHEKhZUBmZyJ
    yDcaBCupd3l18Z/eOyHjbWrzG7NMUUyGkNkSSwVA0Zqwm99II16BNfQNu94FJQy2
    vA76r4MCAwEAAaNTMFEwHQYDVR0OBBYEFCWzG7tHRUZBzugTwWGB+4d8thzjMB8G
    A1UdIwQYMBaAFCWzG7tHRUZBzugTwWGB+4d8thzjMA8GA1UdEwEB/wQFMAMBAf8w
    DQYJKoZIhvcNAQELBQADggEBAElPcy9MrHrYRPrxKruCwXdMsi9sC5jKkgUnktla
    8fmlroui/9wKmSd/rmOaN2ZiQqnnuATKKgtkH6MhUxmjy5azMl2DTWiAm4/FfPjb
    82ysEezSu6t+aN+M1sjjYI9xx/xX9bs1llTnNaKeXPAtOCw8opEsuVe68WDWkdON
    A9ZcRCMZ0LoBVdD0+7Bog+8f2ANE72mG3OWVBbqA6KMRXti0lQWetgAA8YuhJ50Q
    xmNiNZreIncQQWklcSHTlNXa6xfkj1ydCKNy4+AduLkkpR6q6o3sPiheGMtwsuqR
    0fLOp6j15QYgmP5/VtS/KA7XAeoB4EJ98iPtFsC9aW1EzY0=
    -----END CERTIFICATE-----
