- when: inventory_deployment_stage == "prod"
  include_tasks:
    file: tls.yml
    apply:
      tags:
        - gitlab
        - gitlab.tls
  tags:
    - gitlab
    - gitlab.tls
    - gitlab.tls.csr
