# docker-compose -f docker-compose-gitlabprod.yml up -d

version: "3.3"
services:
  gitlab_v13_2_6:   # ⚠ Il y a une version cachée dans cette ligne !!!
                    # Pensez à la modifier aussi !! (Sinon, vous «mettrez à jour»
                    # la version qui tourne, et donc → downtime !!)
    image: epflsti/gitlab-docker:13.2.6
    environment:
      - ENVIRONMENT=prod
    logging:
      options:
        max-size: 50m
        max-file: "3"
    volumes:
      # Keep this list in sync with service gitlabstaging in docker-compose.yml
      - "/srv/gitlab/secrets/ssh/ssh_host_dsa_key:/etc/gitlab/ssh_host_dsa_key:ro"
      - "/srv/gitlab/secrets/ssh/ssh_host_dsa_key.pub:/etc/gitlab/ssh_host_dsa_key.pub:ro"
      - "/srv/gitlab/secrets/ssh/ssh_host_key:/etc/gitlab/ssh_host_key:ro"
      - "/srv/gitlab/secrets/ssh/ssh_host_key.pub:/etc/gitlab/ssh_host_key.pub:ro"
      - "/srv/gitlab/secrets/ssh/ssh_host_ecdsa_key:/etc/gitlab/ssh_host_ecdsa_key:ro"
      - "/srv/gitlab/secrets/ssh/ssh_host_ecdsa_key.pub:/etc/gitlab/ssh_host_ecdsa_key.pub:ro"
      - "/srv/gitlab/secrets/ssh/ssh_host_ed25519_key:/etc/gitlab/ssh_host_ed25519_key:ro"
      - "/srv/gitlab/secrets/ssh/ssh_host_ed25519_key.pub:/etc/gitlab/ssh_host_ed25519_key.pub:ro"
      - "/srv/gitlab/secrets/ssh/ssh_host_rsa_key:/etc/gitlab/ssh_host_rsa_key:ro"
      - "/srv/gitlab/secrets/ssh/ssh_host_rsa_key.pub:/etc/gitlab/ssh_host_rsa_key.pub:ro"
      - "/srv/gitlab/secrets/gitlab-secrets.json:/etc/gitlab/gitlab-secrets.json"
      - "./gitlab-main/gitlab.rb:/etc/gitlab/gitlab.rb"
      - "/srv/gitlab/backup:/var/opt/gitlab/backups"
      - "/srv/gitlab/data/git-data:/var/opt/gitlab/git-data"
      - "/srv/gitlab/data/ssh_user_public_keys:/var/opt/gitlab/.ssh"
      - "/srv/gitlab/data/shared:/var/opt/gitlab/gitlab-rails/shared"
      - "/srv/gitlab/data/uploads:/var/opt/gitlab/gitlab-rails/uploads"
      - "/srv/gitlab/data/gitlab-ci/builds:/var/opt/gitlab/gitlab-ci/builds"
      # Below this line, things are different between gitlabprod and gitlabstaging
      - "/srv/gitlab/run/redis-socket:/var/opt/gitlab/redis"
      - "/srv/gitlab/run/postgres-socket:/var/opt/gitlab/postgresql"
