namespace: epfl_si
name: rancher

version: 0.9.0

readme: README.md

authors:
- EPFL SI ISAS-FSD <isas-fsd@groupes.epfl.ch>

description: Ansible support for Rancher and RKE2 automation

license:
- GPL-2.0-or-later

tags:
- rancher

dependencies:
  kubernetes.core: ">=5.0.0"
  epfl_si.k8s: ">=0.2.0"
  epfl_si.actions: ">=2.3.0"

repository: https://github.com/epfl-si/ansible-collection-rancher

documentation: https://github.com/epfl-si/ansible-collection-rancher

homepage: https://github.com/epfl-si/ansible-collection-rancher

# The URL to the collection issue tracker
issues: https://github.com/epfl-si/ansible-collection-rancher/issues

build_ignore: []
