#!/bin/bash
#
# This is a wrapper around ansible / ansible-playbook.
#
# Usage ("ansible" mode):
#
#   ./gitsible -m raw all -a 'date'
#
# Usage ("ansible-playbook" mode):
#
#   ./gitsible -l prod
#
#
# If you are unfamiliar with Ansible, read up on it at
# - https://www.ansible.com/overview/how-ansible-works
# - https://github.com/jdauphant/awesome-ansible

cd "$(dirname "$0")"; cd "$(/bin/pwd)"

ansible_suitcase_dir () {
    echo $PWD/ansible-deps-cache
}

ensure_suitcase () {
    if ! test -f ansible-deps-cache/.versions 2>/dev/null; then
        curl https://raw.githubusercontent.com/epfl-si/ansible.suitcase/master/install.sh | \
            SUITCASE_DIR="$(ansible_suitcase_dir)" \
            SUITCASE_ANSIBLE_VERSION=9.3.0 \
            SUITCASE_WITH_EYAML=1 \
            SUITCASE_ANSIBLE_REQUIREMENTS=requirements.yml \
            bash -x
    fi

    . "$(ansible_suitcase_dir)"/lib.sh
    ensure_ansible_runtime
}

ensure_suitcase

ansible_flags="-e @vars/versions.yml -e @vars/docker-networking.yml $(ansible_flag_set_var_git_current_branch)"

inventory_mode="staging"
inventories () {
    case "$inventory_mode" in
        staging) echo "-i inventory/common -i inventory/staging" ;;
        prod)    echo "-i inventory/common -i inventory/staging -i inventory/prod" ;;
    esac
}

###########################################################################

mode=ansible-playbook

while [ "$#" -gt 0 ]; do
  case "$1" in
        --prod)
            inventory_mode="prod"
            shift ;;
        -m) mode=ansible
            ansible_args+=("-m")
            shift ;;
        *)
            ansible_args+=("$1")
            shift ;;
    esac
done

set -e

case "$mode" in
    ansible-playbook)
        ansible-playbook $playbook_flags $(inventories) "${ansible_args[@]}" \
                         -e "wpsible_cwd=$OLDPWD" $ansible_flags \
                         playbook.yml
        ;;
    ansible)
        ansible $(inventories) $ansible_flags "${ansible_args[@]}"
        ;;
esac
