- hosts: gitlab_rke2_clusters
  gather_facts: no
  tags:
    - rke2.cluster.create
  tasks:
    - name: "Create cluster in Rancher"
      include_role:
        name: rke2-cluster
        tasks_from: create.yml
        apply:
          tags:
            - rke2.cluster.create
  vars:
    ansible_k8s_kubeconfig: "rke2-credentials-cache/local.yml"

- hosts: gitlab_rke2_workers
  gather_facts: no
  roles:
    - role: rke2-worker

- hosts: gitlab_rke2_clusters
  gather_facts: no
  roles:
    - role: rke2-cluster
  vars:
    ansible_k8s_kubeconfig: "rke2-credentials-cache/{{ inventory_hostname }}.yml"
