- hosts: gitlab_rke2_clusters
  gather_facts: no
  tasks:
    - name: "Cluster object in upstream Rancher"
      include_role:
        name: rke2-cluster
        tasks_from: upstream.yml
        apply:
          tags:
            - rke2.upstream
          delegate_to: rancher
      tags:
        - rke2.upstream

- hosts: gitlab_rke2_vms
  gather_facts: yes   # epfl_si.rancher.rke2_node wants facts
  roles:
    - role: gitlab-node
    - role: xaas-ipv6
    - role: epfl_si.rancher.rke2_node
      vars:
        rancher_rke2_ingress_controller: traefik
        # rancher_rke2_is_worker and rancher_rke2_is_controlplane are set in the inventory.

- hosts: gitlab_rke2_clusters
  gather_facts: no
  roles:
    - role: rke2-cluster
      vars:
        rke2_cluster_expose_prometheus_as_hostname: "gitlab-prometheus.epfl.ch"

- hosts:
    - cattle-monitoring-system   # for gitlab-prometheus
    - gitlab
  gather_facts: no
  roles:
    - role: tls-server-secrets
      vars:
        tls_certify_hostnames:
        - gitlab.epfl.ch
        - gitlab-test.epfl.ch
        - gitlab-next.epfl.ch
        - gitlab-prometheus.epfl.ch

- hosts: gitlab_rke2_namespaces
  gather_facts: no
  roles:
    - role: rke2-gitlab
