- hosts: gitlab_rke2_clusters
  gather_facts: no
  tags:
    - rke2.cluster.create
  tasks:
    - name: "Create cluster in Rancher"
      include_role:
        name: rke2-cluster
        tasks_from: create.yml
        apply:
          tags:
            - rke2.cluster.create
  vars:
    ansible_k8s_kubeconfig: "rke2-credentials-cache/local.yml"

- hosts: gitlab_rke2_vms
  gather_facts: yes   # epfl_si.rancher.rke2_node wants facts
  roles:
    - role: xaas-ipv6
    - role: epfl_si.rancher.rke2_node
      vars:
        rancher_rke2_insecure: false
        # rancher_rke2_is_worker and rancher_rke2_is_controlplane are set in the inventory.

- hosts: gitlab_rke2_clusters
  gather_facts: no
  roles:
    - role: rke2-cluster
  vars:
    ansible_k8s_kubeconfig: "rke2-credentials-cache/{{ inventory_hostname }}.yml"
