collections:
  - name: community.general
  - name: kubernetes.core
  - name: epfl_si.k8s
  - name: epfl_si.rancher
    version: ">=0.8.0"
  - name: epfl_si.quay
    version: ">=0.5.0"
roles:
- src: epfl_si.ansible-module-eyaml
