# Disable “hardware”-assisted UDP checksumming on VMware VMs to
# work around https://github.com/flannel-io/flannel/issues/1279

- name: Disable UDP checksum offload (VMware)
  when: ansible_facts['virtualization_type'] == "VMware"
  tags: rke2-node.udp
  block:
  - name: udp-checksum-offload-disable.service definition
    ansible.builtin.copy:
      content: |
        ; This file is maintained by Ansible
        [Unit]
        Description=Disable udp checksum offload
        Before=rancher-system-agent.service
        [Install]
        WantedBy=rancher-system-agent.service
        [Service]
        Type=oneshot
        RemainAfterExit=true
        ExecStart=ethtool --offload  {{ rancher_rke2_main_network_interface }}  rx off  tx off
      dest: /etc/systemd/system/udp-checksum-offload-disable.service
    register: _ethtool_offload_systemd_definition_file

  - name: udp-checksum-offload-disable.service activation
    ansible.builtin.systemd_service:
      name: udp-checksum-offload-disable.service
      state: started
      enabled: true
      daemon_reload: >
        {{ _ethtool_offload_systemd_definition_file | default({}) is changed }}

- name: Blacklist ip6tables-MARK impaired kernel (Ubuntu Noble)
  vars:
    _is_ubuntu_noble: >-
       ansible_facts['distribution'] == "Ubuntu"
       and ansible_facts['distribution_version'] is version('24.04', '==')
  when: _is_ubuntu_noble
  block:
  - name: APT pin on last known-good kernel version
    copy:
        dest: "/etc/apt/preferences.d/no-linux-image-56-generic"
        # What we actually want, would be to blacklist 6.8.0-56.58, as it exhibits
        # the symptoms of https://github.com/rancher/rke2/issues/7438 . But
        # it appears that you cannot do that with APT — At least, not when the
        # defective package is already installed. The next best thing is to
        # “whiter-than-whitelist” the last known good version:
        content: |
          Package: linux-image-generic linux-generic linux-headers-generic
          Pin: version 6.8.0-55.57
          Pin-Priority: 1000
    register: _apt_pin
  - name: Update APT cache
    when: _apt_pin is changed
    apt:
      update_cache: yes
