# “Documentation” is at https://github.com/rancher/rke2/issues/5928#issuecomment-2759404098
- name: Select ingress controller
  when: >-
    rancher_rke2_ingress_controller is defined
  ansible.builtin.copy:
    dest: /etc/rancher/rke2/config.yaml.d/70-ingress.yaml
    content: |
        ingress-controller: {{ rancher_rke2_ingress_controller }}
  register: _rke2_config_ingress

- name: Check whether RKE2 server is already installed
  changed_when: false
  ansible.builtin.shell:
    cmd: |
      systemctl is-enabled rke2-server || true
  register: _rke2_server

- name: Restart one RKE2 server
  when: _some_rke2_server is defined
  delegate_to: "{{ _some_rke2_server }}"
  run_once: true
  ansible.builtin.systemd_service:
    name: rke2-server
    state: restarted
  vars:
    _some_rke2_server: >-
      {{
      hostvars.values()
      | selectattr("_rke2_config_ingress", "defined")
      | selectattr("_rke2_config_ingress.changed")
      | selectattr("_rke2_server.stdout", "defined")
      | selectattr("_rke2_server.stdout", "search", "enabled")
      | map(attribute='inventory_hostname')
      | first
      }}
