- when:
    - rancher_rke2_longhorn_storage_path is defined
    - rancher_rke2_longhorn_storage_path is string
    - query("epfl_si.k8s.k8s",
            api_version="longhorn.io/v1beta2",
            kind="Node",
            namespace="longhorn-system",
            resource_name=rancher_rke2_longhorn_node_name) | length > 0

  name: "Turn on Longhorn storage on desired nodes"
  epfl_si.k8s.k8s:
    definition:
      apiVersion: longhorn.io/v1beta2
      kind: Node
      metadata:
        name: "{{ rancher_rke2_longhorn_node_name }}"
        namespace: longhorn-system
      spec:
        disks:
          longhorn:
            diskType: filesystem
            path: "{{ rancher_rke2_longhorn_storage_path }}"
            allowScheduling: true
