- name: configure crictl for interactive use
  ansible.builtin.blockinfile:
    path: /root/.profile
    marker: '# {mark} ANSIBLE MANAGED BLOCK - crictl'
    block: |
      export CRI_CONFIG_FILE=/var/lib/rancher/rke2/agent/etc/crictl.yaml
      export CONTAINERD_ADDRESS=unix:///run/k3s/containerd/containerd.sock
      export PATH=$PATH:/var/lib/rancher/rke2/bin

# TODO: this assumes recent Ubuntu.
- name: install kubectl
  community.general.snap:
    name: kubectl
    classic: yes
    channel: latest/stable

- name: configure kubectl
  ansible.builtin.blockinfile:
    path: /root/.profile
    marker: '# {mark} ANSIBLE MANAGED BLOCK - kubectl'
    block: |
      export KUBECONFIG=/etc/rancher/rke2/rke2.yaml

- when: rancher_rke2_has_etcd
  name: install etcdctl
  ansible.builtin.apt:
    name: etcd-client

- when: rancher_rke2_has_etcd
  name: "{{ _env_script }}"
  ansible.builtin.copy:
    dest: "{{ _env_script }}"
    content: |
      export ETCDCTL_ENDPOINTS='https://127.0.0.1:2379'
      export ETCDCTL_CACERT='/var/lib/rancher/rke2/server/tls/etcd/server-ca.crt'
      export ETCDCTL_CERT='/var/lib/rancher/rke2/server/tls/etcd/server-client.crt'
      export ETCDCTL_KEY='/var/lib/rancher/rke2/server/tls/etcd/server-client.key'
      export ETCDCTL_API=3
  vars:
    _env_script: /etc/profile.d/rke2-etcdctl.sh
