- name: configure crictl for interactive use
  ansible.builtin.blockinfile:
    path: /root/.profile
    marker: '# {mark} ANSIBLE MANAGED BLOCK - crictl'
    block: |
      export CRI_CONFIG_FILE=/var/lib/rancher/rke2/agent/etc/crictl.yaml
      export CONTAINERD_ADDRESS=unix:///run/k3s/containerd/containerd.sock
      export PATH=$PATH:/var/lib/rancher/rke2/bin

# TODO: this assumes recent Ubuntu.
- name: install kubectl
  community.general.snap:
    name: kubectl
    classic: yes
    channel: latest/stable

- name: configure kubectl
  ansible.builtin.blockinfile:
    path: /root/.profile
    marker: '# {mark} ANSIBLE MANAGED BLOCK - kubectl'
    block: |
      export KUBECONFIG=/etc/rancher/rke2/rke2.yaml
