- tags: always
  when: >-
    ('virtualization_type' not in ansible_facts)
    or
    ('distribution' not in ansible_facts)
  name: "Gather select Ansible facts"
  ansible.builtin.setup:
    gather_subset:
      - virtualization_type  # for ansible_facts['virtualization_type'] in bugware.yml
      - distribution  # for ansible_facts['distribution'] in _remove_k8s_node.yml

- name: Requirements for RKE2
  tags:
    - rke2-node
    - rke2-node.deps
  include_tasks:
    file: deps.yml
    apply:
      tags:
        - rke2-node
        - rke2-node.deps

- name: Interactive use / comfort features
  tags:
    - rke2-node
    - rke2-node.interactive
  include_tasks:
    file: interactive.yml
    apply:
      tags:
        - rke2-node
        - rke2-node.interactive

- name: Platform-specific bugware
  tags:
    - rke2-node
    - rke2-node.udp
    - rke2-node.bugware
  include_tasks:
    file: bugware.yml
    apply:
      tags:
        - rke2-node
        - rke2-node.bugware

- name: Support for NFS volumes
  ansible.builtin.apt:
    name: nfs-common
    state:
      present

- name: RKE2 pre-configuration
  tags:
    - rke2-node
    - rke2-node.config
  include_tasks:
    file: config.yml
    apply:
      tags:
        - rke2-node
        - rke2-node.config

- name: Rancher cluster membership
  tags:
    - rke2-node
    - rke2-node.register
  include_tasks:
    file: register.yml
    apply:
      tags:
        - rke2-node
        - rke2-node.register
