# -*- mode: yaml; -*-

all:
  children:
    all_gitlabs:
      hosts:
        gitlabprod:
  hosts:
    gitlabprod:   # Not really a host (see gitlab-serving role in ../../playbooks/main.yml)
      ansible_host: gitlab.epfl.ch
      ansible_user: root
      ansible_port: 2202
      ansible_ssh_common_args: '-o ForwardAgent=yes'
