# Prometheus-(and-more-)as-a-service for your RKE2 cluster

- name: "`rancher` Helm repository"
  epfl_si.k8s.helm_repository:
    name: rancher
    repo_url: https://charts.rancher.io/

- name: "`Namespace/cattle-monitoring-system`"   # The chart won't let you choose another
  epfl_si.rancher.namespace:
    name: cattle-monitoring-system
    is_system: true

- name: "`rancher-monitoring` Helm chart"
  epfl_si.k8s.helm:
    name: rancher-monitoring
    namespace: "cattle-monitoring-system"
    chart_ref: rancher/rancher-monitoring
    force: >-
      {{ rke2_monitoring_helm_force is defined }}
    values:
      rke2Etcd:
        enabled: true
      rke2ControllerManager:
        enabled: true
      rke2Scheduler:
        enabled: true
      rke2Proxy:
        enabled: true
      grafana:
        enabled: false
      alertmanager:
        enabled: false
      prometheus:
        prometheusSpec:
          # This is the “small T-shirt” configuration, whereby only one
          # Prometheus instance in the cluster monitors everything.
          serviceMonitorSelectorNilUsesHelmValues: false
          serviceMonitorSelector: {}
          podMonitorSelectorNilUsesHelmValues: false
          podMonitorSelector: {}
          ruleSelectorNilUsesHelmValues: false
          ruleSelector: {}
          # Optional: pick up alerts from other namespaces too
          ruleNamespaceSelector: {}
          serviceMonitorNamespaceSelector: {}
          podMonitorNamespaceSelector: {}
          # We want storage with that:
          storageSpec:
            volumeClaimTemplate:
              spec:
                storageClassName: nfs-client
                accessModes: ["ReadWriteMany"]
                resources:
                  requests:
                    storage: 50Gi   # Required, even though Kubernetes doesn't actually allocate anything
          # Connect to the team's external NOC.
          # https://github.com/rancher/charts/blob/main/charts/rancher-monitoring/values.yaml#L2361
          additionalAlertManagerConfigsSecret: >-
            {{ rancher_rke2_cluster_prometheus.additional_alertmanager_configs_secret
            | default(None) }}
        ingress: >-
          {{ _ingress_expose_prometheus
          | default({ "enabled": False }) }}
      defaultRules:
        disabled:
          Watchdog: true
    post_renderer: "{{ role_path }}/scripts/rancher-monitoring-post-renderer"

  vars:
    _hosts: [ "{{ rancher_rke2_cluster_prometheus.expose.hostname }}" ]
    _ingress_expose_prometheus:
      # Will be `is not defined` (in the Ansible sense) if any consumed vars is missing,
      # which is fine (see `ingress: >-` stanza, above).
      enabled: true
      ingressClassName: traefik
      hosts: "{{ _hosts }}"
      annotations:
        # https://doc.traefik.io/traefik/v2.2/routing/providers/kubernetes-ingress/
        traefik.ingress.kubernetes.io/router.middlewares: >-
          cattle-monitoring-system-prometheus-basicauth@kubernetescrd
      tls:
        - secretName: "{{ rancher_rke2_cluster_prometheus.expose.tls_secret }}"
          hosts: "{{ _hosts }}"

- when: rancher_rke2_cluster_prometheus.expose.basic_auth is defined
  name: "`Middleware/prometheus-basicauth`"
  # https://doc.traefik.io/traefik/reference/routing-configuration/http/middlewares/basicauth/#configuration-examples
  # under “Kubernetes” tab
  epfl_si.k8s.k8s:
    definition:
      apiVersion: traefik.io/v1alpha1
      kind: Middleware
      metadata:
        name: prometheus-basicauth
        namespace: cattle-monitoring-system
      spec:
        basicAuth:
          secret: prometheus-basicauth

- when: rancher_rke2_cluster_prometheus.expose.basic_auth is defined
  name: "`Secret/prometheus-basicauth`"
  epfl_si.k8s.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: prometheus-basicauth
        namespace: cattle-monitoring-system
      stringData:
        # The sybilline phrase “The option users supports Kubernetes secrets.” at
        # https://doc.traefik.io/traefik/reference/routing-configuration/http/middlewares/basicauth/#kubernetes-secrets
        # is apparently supposed to mean this:
        users: "{{ rancher_rke2_cluster_prometheus.expose.basic_auth }}"
