- name: ssh access to nodes
  ansible.posix.authorized_key:
    user: root
    state: >-
      {{ item.state | default("present") }}
    key: "{{ item.key }}"

  with_items:
    - key: https://github.com/domq.keys
    - key: https://github.com/ponsfrilus.keys
    - key: https://gitlab.com/avidalqim.keys
      state: absent
