- name: Install required packages
  package:
    name:
      - lvm2
      - parted
      - e2fsprogs

- name: "Check if {{ node_storage_pvs[-1] }} already exists"
  command: "lsblk -no NAME {{ node_storage_secondary_disk }}"
  register: _lsblk_output
  changed_when: false

- name: Create {{ node_storage_pvs[-1] }} (primary partition)
  command: >-
    parted {{ node_storage_secondary_disk }} --script mklabel gpt mkpart primary 0% 100% set 1 lvm on
  when: "(node_storage_pvs[-1] | basename) not in _lsblk_output.stdout"

- name: Check if {{ node_storage_pvs[-1] }} is an LVM PV
  command: pvs --noheadings -o pv_name
  register: _pvs_output
  changed_when: false

- name: "pvcreate {{ node_storage_pvs[-1] }}"
  when: >-
    node_storage_pvs[-1] not in _pvs_output.stdout
  command: "pvcreate {{ node_storage_pvs[-1] }}"

- name: "Configure {{ node_storage_vg }}"
  lvg:
    state: present
    vg: "{{ node_storage_vg }}"
    pvs: "{{ node_storage_pvs }}"

- name: "Logical Volumes (LVs)"
  with_items: "{{ node_storage_lvs }}"
  when: item.condition.value | default(True)
  lvol:
    state: present
    vg: "{{ node_storage_vg }}"
    lv: "{{ item.name }}"
    size: "{{ item.size }}"

- block:
    - name: "Format the LVs"
      with_items: "{{ node_storage_lvs }}"
      when: item.condition.value | default(True)
      filesystem:
        fstype: "{{ item.fs }}"
        dev: "{{ _devname }}"

    - name: "Put up the LVs in fstab and mount them"
      with_items: "{{ node_storage_lvs }}"
      when: item.condition.value | default(True)
      ansible.posix.mount:
        state: mounted
        path: "{{ item.mountpoint }}"
        src: "{{ _devname }}"
        fstype: "{{ item.fs }}"
  vars:
    _devname: >-
      /dev/{{ node_storage_vg }}/{{ item.name }}

- name: "`/var/lib/rancher/kubelet`"
  ansible.builtin.file:
    state: directory
    path: /var/lib/rancher/kubelet

- name: "`/var/lib/kubelet` → `/var/lib/rancher/kubelet`"
  ansible.builtin.file:
    state: link
    dest: /var/lib/kubelet
    src: /var/lib/rancher/kubelet
