# Delete everything (so as to start over)

- name: "Delete the {{ k8s_namespace }} namespace"
  kubernetes.core.k8s:
    name: "{{ k8s_namespace }}"
    api_version: v1
    kind: Namespace
    state: absent

- name: "Wait for the {{ k8s_namespace }} namespace to go down"
  changed_when: false
  shell:
    cmd: |
      kubectl get namespace {{ k8s_namespace }} || true
  register: _kubectl_get_namespace
  until: >
    ansible_check_mode or ("NotFound" in _kubectl_get_namespace.stderr)
  retries: 20
  delay: 30

- name: "Delete the {{ k8s_persistentvolume_name }} PersistentVolume"
  kubernetes.core.k8s:
    kind: PersistentVolume
    api_version: v1
    name: "{{ k8s_persistentvolume_name }}"
    state: absent

- name: "Wait for the {{ k8s_persistentvolume_name }} PersistentVolume to go down"
  changed_when: false
  shell:
    cmd: |
      kubectl get pv {{ k8s_persistentvolume_name }} || true
  register: _kubectl_get_namespace
  until: >
    ansible_check_mode or ("NotFound" in _kubectl_get_namespace.stderr)
  retries: 20
  delay: 30
