# Credentials to wield in order to push to ic-registry.epfl.ch
#
# To edit the encrypted secrets below, you need eyaml installed.
# Familiarize yourself with
# https://puppet.com/blog/encrypt-your-data-using-hiera-eyaml first.
# The edit command goes like this,
#
#   ansible-deps-cache/bin/eyaml edit -d \
#     --pkcs7-public-key eyaml/epfl_gitlab.ic_gitlab.pkcs7.pem \
#     roles/gitlab-k8s/vars/harbor-credentials.yml
#
# 💡 This *will not* decrypt anything for you because chances are, you
# don't need to decrypt secrets (YA RLY). For those cases where you
# do, wielding the private key from Keybase is left as an exercise to
# the reader.
harbor_credentials:
  hostname: ic-registry.epfl.ch
  username: "robot$pasbot"
  token:  "{{ _harbor_robot_account_jwt_token | eyaml(eyaml_keys) }}"

_harbor_robot_account_jwt_token: ENC[PKCS7,MIIBzwYJKoZIhvcNAQcDoIIBwDCCAbwCAQAxggFXMIIBUwIBADA7MC4xLDAqBgNVBAMMI0VZQU1MIHNlY3JldHMgZm9yIGljLWdpdGxhYi5lcGZsLmNoAgkA9XsB4Is7gaEwDQYJKoZIhvcNAQEBBQAEggEAH+60TzPPHlBIDB3XJGs2qwW0oqxUxUa2PKYCRIPFsYpGDpYsrN5D9/EVKQqIs3zfF62BSaoItO89xzhaB5Ho9z4Ir5MmeXAZs0pYctaiY+tZdLHrHZxcdO7zruLpMNgFdGqr9i7ce9YrZT/O47KymKUgfBdf6ibUP5l2VwfKccVpCEIXULc3LDjKhmV2lMWhI+SqxV/P+WinEAa8xkI41r+L0a6GjmkKGo2NU7vukLrWI20L/fk36WQuYw7Ne1CKz6qpi32f2tQuEU6dSoTWgRrO69Fl/r1tEikJ+wycVIR/HpxGZUajRfrU4EKnz3VqZ1WKcckyFgvxOXzc6PDTYjBcBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBDawG5Uf7ppW1aJRc7cjZuUgDCOM9ogiwtXbGKmbKZtNhOdUtSKGADtukqPwRe31ts5/CDXmIkhxXqHcOMB2suEW5g=]
