# Fake cert and key for ingress traffic (inside the k8s cluster)
#
# To edit the encrypted secrets below, you need eyaml installed.
# Familiarize yourself with
# https://puppet.com/blog/encrypt-your-data-using-hiera-eyaml first.
# The edit command goes like this,
#
#   ansible-deps-cache/bin/eyaml edit -d \
#     --pkcs7-public-key eyaml/epfl_gitlab.ic_gitlab.pkcs7.pem \
#     roles/gitlab-k8s/vars/ingress-tls-secrets.yml
#
# 💡 This *will not* decrypt anything for you because chances are, you
# don't need to decrypt secrets (YA RLY). For those cases where you
# do, wielding the private key from Keybase is left as an exercise to
# the reader.

ingress_tls_private_key: ENC[PKCS7,MIIIMwYJKoZIhvcNAQcDoIIIJDCCCCACAQAxggFXMIIBUwIBADA7MC4xLDAqBgNVBAMMI0VZQU1MIHNlY3JldHMgZm9yIGljLWdpdGxhYi5lcGZsLmNoAgkA9XsB4Is7gaEwDQYJKoZIhvcNAQEBBQAEggEAdufGvOm+Q723fZSrnTajAgJdFgwBWqspXS3wO6jp1XoCjL0mqff3RLjZSN9SH3b66zAB9c0p2UOFl/T4Yo11GH48kH15408t+q/rWf02SwoFeBFVQiC6QYHtVQQaEg5O9o1ZzQlDiAOkmyV/TnmaBd/yo5K2RZJuvS+3sMh+SCiv86pbBwkqVUBNEmcUxB15ecvfLyCY30duq1I50OP3qxT5F6UNB3Z38bk5pfYxdS8FMvZhwr/A0okLY12TFmaCh9GXICgi+xvY9DZpnzZKOJedTexQi7Yr/mVCwmJbx3MVOeGeH5c7gj5XSVp+wJoOHvQQtGoISp1uoA4Zb0+4/zCCBr4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEKu0mH0vyi9Ig7Y99AdggDWAggaQxc0Hb1LtaF9yFDNb4Hj5AWVy38hsAG1Df0gcJ3G5U5z2dpG6BZrlz/3UVKPZ/D+vbUi877BDhpkbFlG55Cd+COJqblX+PBwgzROHiECrqW7GwgTgmfvEwbOgk/utaXC+j38+zrzl32WJacGhVLxW4cEeXZbYdH0m/Ahk1dBYRRRKhZ4izQnrZM5jqwmXiRjZ1PPWlSuLnzLkJd5MbTe350V1Q5XebjADSKdpEyrGUxO3MSTE338le9pajiSK0DSBy9Ytn+G1ECkUHQpYpdLvN7wNUGPcZstotNY417m6gzmI+6CzwJWI4UQFMivpHK0YIotCFAD5p58xXes4LiPyQqyiFd3CZcKmLO9cjoQFg5g1fsZFx0553bI4q53RzdF7nP2eEAhAVtdarAP7OYWbDj/BGQ/rhs1b5CquKViaIN44EBmFbr9M+ZhNmC0tN9xsYZRy9luGpy5M647kvJdbVbOpLYxKUB7C3agh7aidrwoqAQYrIcY2F+oSPLkRl1ceHtjMoX3l1ktRvYdtyTm4ArMVMTpcaGXilP/cJ3JBUAnVKafzhPNMpySWy08j3YJyXQd0Gx+YObFrW+ydhn9IDChz2/R0CQMNwFE7hI6YpyhiuSNGelxzF7NvTkeYMvWi0xkDh/d5EnpkbWFV9hfI21nBaHHBbu1kV/9x2U0NztmnlUXuR+Z1gdUjVeKc9Ca5takKijSjAJXAqEEX9yPQ0RduQQC8gqFSX9bQEA/aIxvS3hydtr3rUMh2al1mXoOy8gneovoi7Iv7QxAAwamNC2xA9n27/zJY/ikddac24FW4/2qexygqDmYZ7vt67d5ZyhN1yKWuUVqDd3AF4Cpha+09PjSqNiGdXOKx8N9ER+zwiC3Ud/jT6Ewdzexxw/IRxerEZSHG+1iSABruVSCSzCSpw/wn/egMKTZoWihIPqNpnYbN8JN+Stk+T5ByxAh4qGNWhaNGZ3wu3iFrdI+tXIvtjGKuFMnHwJ0o/yPrklr7lamzhAnu1dq7zgaulDT6isc3GybTYVKSK8F67j7uYg8yQzboXaX5WFuxP1bS5ys8Ms6t7WHXULdN9uPqFYU1Dy+F+8ZXRdQK7Y8Hc/aJO0QsjfnkvjMVj84IYX927rfNHVvUH+mluHcH4emGz8Pm3c6zKcSnQ9S1ZJgyjN9+EBbJysI8s3scUot+ojOzJFcY8YyYKBe3/JAjTjmc1N+8B3oyH3er7//dV44vUc6YQNtOEhyPkXq2Dfd/nXxAKmXcYymjpaRZLhsJCG6gaQ6hsoeO/DNBYjsItpoSJMEICJWMaOiq16BMlGonjVzqf0u1QTQWGCZjf66b4uN/SQonkyK2YdIUlUFxyhzPFuR8STIlCGH5LwpqVAouy1CE7vX6yhiS6Z22DaFd1/LuNkvShYLfK1cHkoLGEucuYKAyjzMItknmjVmjjMvN6Int0oXOyiMEEGOjnXjWpcHqQ1VJs7cYLS5x0TWBdv/3viOxM5AC9vDZ8gk476GoDu67u/i/GTdX1jwEcLd/43R9McBcoGVQdU5eagDNGkf3onqETK68OPeiRss7Q3MJMn4it6sXgmtuXRwZIhIRG4wWGWs+9ntearK/0AwzOrQa0Q254paOQn4FFs/I6YqW5oAVOO2K9SBMbPX049PWYy+lnGZufuYygYW43cRosbHLpdk90qtmhmjLGfdc7bvyqY2wmTzJft55zyevo7ctfoO6hrcfTQw6bOMmkQc4Sifxtfludb2GUs7OSCnyxVkBUhCMEEnxdUiYlP00PQa51KZoMLVKZYGguyTwF9uP7YJ9krME93gTGsulXmaMqE6lzXXY74BShehVI168F6laCNRdWEoy86VIy4jdLmzTLGjReRtlmCoCVth19+RCZTbh8XkT+XVdXASXPZykQIljnxMSVPUbfz2z+m85DqelRIW56LD8WuLD2YCaJrhYSUJd9aDeEzEazBdXQNL15LH0GZV0SrtaaU1JLOTouOZOBUIJssDLyrHVdy9foq+TqRr0nIfaslhu8TE68Kr1HkSXJDa8NrgWHqrQk6HBKKfIO4hxjvJ/Bynom0DQPt8KrLI0ON2SMzDoUxkEHEIfY7tpATXriPJhA7DQJ8Ynjud6oBdi5Err3FmJ4fEt0pEmelj/Z7eaGfB4X+aTqVajRaT96F2Yj0gK6mcxNeRLVTNglF+FWh5dGhHlQ0qixsnmbk/UpRKJX/1xeieZJ/eWHFewn4kADmjj]


ingress_tls_certificate: |
  -----BEGIN CERTIFICATE-----
  MIIDGzCCAgOgAwIBAgIUMb99xTP9bpOnJupDOujWJiZ6Ny0wDQYJKoZIhvcNAQEL
  BQAwHDEaMBgGA1UEAwwRaWMtZ2l0bGFiLmVwZmwuY2gwIBcNMjEwMTIyMTIzOTQz
  WhgPMjEyMDEyMjkxMjM5NDNaMBwxGjAYBgNVBAMMEWljLWdpdGxhYi5lcGZsLmNo
  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwAkr82ScS3ba+F4vjW4A
  Ga8NnKzX1pI/4cAL0pXvT6RJfwiiIx3nqKKs7t9oIgV8LIiVEhzL6UuCKGRiCcW3
  tSyQZEVYoU1bS2Iy+qZr6Z32Phv3YbQxKBrdaIwbFu33QMUXDI7xAGfNl25WMSya
  MQgDzBBEe4ib/B/qCyTvmt7FKzFQzGmaCmyDzSKBvai8NyXv2Zh7wgfIjqXKmYGH
  DSGH9Ik0tGpYX2lIy4v74a1SACdcOkjjJsnO1rgKiXUrcL+F9pQqqUtPlr3/jzlm
  N4D5WIT+5TJUrbVRTx+Gr8qWjbvRryx4exnDOQ2DdbzGUghSrW0V55SePbhg/WcL
  3wIDAQABo1MwUTAdBgNVHQ4EFgQUeoOG5ACcshRyG5zadNBETzd0rjYwHwYDVR0j
  BBgwFoAUeoOG5ACcshRyG5zadNBETzd0rjYwDwYDVR0TAQH/BAUwAwEB/zANBgkq
  hkiG9w0BAQsFAAOCAQEAmbP5BaP6nM8C+Sm5CHlUbnZ07LkxqSoY3bhgZQ5jZ2ql
  Zneegqc6T2smdwazUx8hqMS9lDavIS3YAE0jLk3CldiHiCuicI+2fHQ423avK8QE
  1qLGtvX/j343Kq3hjjXGb5Ltcdiq2kgc7lXhsQOq7ddliD+Xnxi2ygLkNL0aSlI0
  MbiR+VydTH+9didR+Fszbe8JT0L39n9ZdkWhWV3hzqn+oOaP0Pf+voyl0Be8dvPY
  9oc0nLUxnuEqInpfo1lPkQSgT9vlqQj59DFn18x8XXUiZo4+ELbydrxqGaYb9jO1
  3Ntcvbg3q4U7KZHnORjJwuVdfyJGYlOEMkx3w5brPw==
  -----END CERTIFICATE-----
