# Secrets consumed by more than one k8s-*.yml tasks file

- name: "gitlab-passwords secret"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: gitlab-passwords
        namespace: "{{ k8s_namespace }}"
      type: Opaque
      data:
        gitlab_rails_db_password.txt: >-
          {{ lookup('pipe',
                    'cat {{ keybase_gitlab_rails_db_password_file }}')
                  | b64encode }}
        gitlab_rails_redis_password.txt: >-
          {{ lookup('pipe',
                    'cat {{ keybase_gitlab_rails_redis_password_file }}')
                  | b64encode }}

