- name: "Delete {{ k8s_namespace }} namespace"
  community.kubernetes.k8s:
    name: "{{ k8s_namespace }}"
    api_version: v1
    kind: Namespace
    state: absent
  tags:
    - never
    - k8s.wipe

- name: "Wait for the {{ k8s_namespace }} namespace to go down"
  changed_when: false
  shell:
    cmd: |
      kubectl get namespace gitlab || true
  register: _kubectl_get_namespace
  until: >
    ansible_check_mode or ("NotFound" in _kubectl_get_namespace.stderr)
  retries: 20
  delay: 30
  tags:
    - never
    - k8s.wipe

- name: "{{ k8s_namespace }} namespace"
  community.kubernetes.k8s:
    name: "{{ k8s_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: "gitlab-passwords secret"
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: gitlab-passwords
        namespace: "{{ k8s_namespace }}"
      type: Opaque
      data:
        gitlab_rails_db_password.txt: >-
          {{ lookup('pipe',
                    'cat {{ keybase_gitlab_rails_db_password_file }}')
                  | b64encode }}
        gitlab_rails_redis_password.txt: >-
          {{ lookup('pipe',
                    'cat {{ keybase_gitlab_rails_redis_password_file }}')
                  | b64encode }}

- name: "gitlab-rails ConfigMap"
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: gitlab-rails
        namespace: "{{ k8s_namespace }}"
      data:
        gitlab.rb: >
          {{ lookup("template", "gitlab.rb.j2") }}
  vars:
    is_kubernetes: true
