- include_vars: "{{ item }}"
  with_items:
    - ssh-secrets.yml
    - gitlab-secrets.yml
    - ingress-tls-secrets.yml
    - harbor-credentials.yml
    - ../../roles/gitlab-serving/vars/main.yml
  tags: always

- name: "Push latest image"
  delegate_to: gitlabstaging
  shell:
    executable: /bin/bash
    cmd: |
      set -e  # Not -x just yet — Here there be tokens
      docker login -u '{{ harbor_credentials.username }}' \
          -p '{{ harbor_credentials.token }}' \
          '{{ harbor_credentials.hostname }}'
      set -x  # Now we can

      docker tag "{{ gitlab_image_name }}" "{{ k8s_gitlab_image }}"
      docker push "{{ k8s_gitlab_image }}"
      docker logout "{{ harbor_credentials.hostname }}"

  tags:
    - k8s.push

- name: "{{ k8s_persistentvolume_name }} PersistentVolume"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: "{{ k8s_persistentvolume_name }}"
      spec:
        capacity:
          storage: 1Ti
        accessModes:
          - ReadWriteMany
        mountOptions:
          - nfsvers=3
        nfs:
          server: nas-app-ma-nfs1.epfl.ch
          path: "/si_gitlab_app"
        # Do the Right Thing when deleting/recreating the namespace:
        persistentVolumeReclaimPolicy: "Recycle"

- name: "gitlab-epfl-ch-pvc PersistentVolumeClaim"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name:  gitlab-epfl-ch-pvc
        namespace: gitlab
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 1Ti

- name: "gitlab-ssh Secret"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: gitlab-ssh
        namespace: "{{ k8s_namespace }}"
      type: Opaque
      data: "{{ ssh_secrets | base64_values }}"

- name: "gitlab-ruby Secret"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: gitlab-ruby
        namespace: "{{ k8s_namespace }}"
      type: Opaque
      data:
        gitlab-secrets.rb: "{{ _gitlab_secrets_rb | b64encode }}"
  vars:
    _gitlab_secrets_rb: |
      {{ gitlab_secrets.gitlab_rails     | to_omnibus("gitlab_rails")     }}
      {{ gitlab_secrets.gitlab_pages     | to_omnibus("gitlab_pages")     }}
      {{ gitlab_secrets.gitlab_kas       | to_omnibus("gitlab_kas")       }}
      {{ gitlab_secrets.gitlab_workhorse | to_omnibus("gitlab_workhorse") }}
      {{ gitlab_secrets.gitlab_shell     | to_omnibus("gitlab_shell")     }}
      {{ gitlab_secrets.grafana          | to_omnibus("grafana")          }}
      {{ gitlab_secrets.registry         | to_omnibus("registry")         }}
      {{ gitlab_secrets.letsencrypt      | to_omnibus("letsencrypt")      }}
      {{ gitlab_secrets.postgresql       | to_omnibus("postgresql")       }}

- name: "gitlab-rails ConfigMap"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: gitlab-rails
        namespace: "{{ k8s_namespace }}"
      data:
        gitlab.rb: >
          {{ lookup("template", "gitlab.rb.j2") }}
  vars:
    is_kubernetes: true
  register: _gitlab_configmap

- name: "gitlab Deployment"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: gitlab
        namespace: "{{ k8s_namespace }}"
        labels:
          app: gitlab
      spec:
        selector:
          matchLabels:
            app: gitlab
        replicas: 6
        template:
          metadata:
            labels:
              app: gitlab
          spec:
            affinity:
              podAntiAffinity:
                # This pod doesn't like running on VMs that have other
                # copies of itself (obviously for HA purposes)
                preferredDuringSchedulingIgnoredDuringExecution:
                  - weight: 100
                    podAffinityTerm:
                      topologyKey: kubernetes.io/hostname
                      labelSelector:
                        matchExpressions:
                          - key: app
                            operator: In
                            values:
                            - "gitlab"
            containers:
            - name: master
              image: "{{ k8s_gitlab_image }}"
              resources:
                requests:
                  memory: "1Gi"
                limits:
                  memory: "12Gi"
              ports:
              - containerPort: 80
              - containerPort: 22
              volumeMounts: "{{ volume_mounts }}"
              startupProbe:      # When container starts
                httpGet:
                  path: /-/readiness
                  port: 80
                periodSeconds: 30
                failureThreshold: 12  # 6 minutes
              readinessProbe:    # In-flight, temporary problems
                httpGet:
                  path: /-/readiness
                  port: 80
              livenessProbe:     # In-flight, fatal problems
                httpGet:
                  path: /-/liveness
                  port: 80
            volumes:
              - name: gitlab-rails-config
                configMap:
                  name: gitlab-rails
              - name: gitlab-rails-external-secrets
                secret:
                  secretName: gitlab-passwords
              - name: gitlab-rails-internal-secrets
                secret:
                  secretName: gitlab-ruby
              - name: git-nfs
                persistentVolumeClaim:
                  claimName: gitlab-epfl-ch-pvc
              - name: ssh-server-keys
                secret:
                  secretName: gitlab-ssh
                  defaultMode: 0600
  vars:
    volume_mounts: >-
      {{ config_and_secret_volume_mounts +
         nfs_volume_mounts +
         ssh_volume_mounts }}
    config_and_secret_volume_mounts:
      ## Configuration file (from ConfigMap)
      - mountPath: "/etc/gitlab/gitlab.rb"
        name: gitlab-rails-config
        subPath: gitlab.rb
      ## Secrets sourced from the configuration file
      - mountPath: "/secrets/external"
        name: gitlab-rails-external-secrets
      - mountPath: "/secrets/internal"
        name: gitlab-rails-internal-secrets
    nfs_volume_mounts:
      - mountPath: "/var/opt/gitlab/git-data"
        name: git-nfs
        subPath: data/git-data
      - mountPath: "/var/opt/gitlab/.ssh"
        name: git-nfs
        subPath: data/ssh_user_public_keys
      - mountPath: "/var/opt/gitlab/gitlab-rails/shared"
        name: git-nfs
        subPath: data/shared
      - mountPath: "/var/opt/gitlab/gitlab-rails/uploads"
        name: git-nfs
        subPath: data/uploads
      - mountPath: "/var/opt/gitlab/gitlab-ci/builds"
        name: git-nfs
        subPath: data/gitlab-ci/builds
    ssh_volume_mounts: '{{ ssh_secrets | keys |
                           as_volume_mounts("ssh-server-keys", "/etc/gitlab") }}'
  register: _gitlab_deployment

- name: "Redeploy gitlab"
  tags:
    - k8s.gitlab
    - k8s.gitlab.redeploy
  when: |
    ("k8s.gitlab.redeploy" in ansible_run_tags)
    or
    (     (_gitlab_configmap is defined)
      and (_gitlab_configmap is changed) )
    or
    (     (_gitlab_deployment is defined)
      and (_gitlab_deployment is changed) )
  shell:
    cmd: |
      kubectl -n {{ k8s_namespace }} rollout restart deployment gitlab

- name: "gitlab http Service (used by the Ingress)"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: gitlab-web
        namespace: "{{ k8s_namespace }}"
      spec:
        ports:
          - name: http
            protocol: TCP
            port: 80
        selector:
          app: gitlab

- name: "gitlab ssh Service (visible at cluster edge)"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: ssh-lb
        namespace: "{{ k8s_namespace }}"
      spec:
        type: LoadBalancer
        ports:
          - name: ssh
            protocol: TCP
            nodePort: 30022  ## Ingress traffic arrives on this port
            port: 22         ## Egress traffic goes to that port on matching
                             ## pods (by “selector”, below)
        selector:
          app: gitlab

- name: "Ingress secret (bogus SSL cert and key)"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: gitlab-ingress-tls
        namespace: "{{ k8s_namespace }}"
      type: Opaque
      data:
        tls.crt: "{{ ingress_tls_certificate | b64encode }}"
        tls.key: "{{ ingress_tls_private_key | eyaml(eyaml_keys) | b64encode }}"

- name: "gitlab http Ingress (dispatched via cluster-wide ingress controller)"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: gitlab
        namespace: "{{ k8s_namespace }}"
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          nginx.ingress.kubernetes.io/forwarded-for-header: X-Forwarded-For
      spec:
        tls:
        - hosts:
          - ic-gitlab.epfl.ch
          secretName: gitlab-ingress-tls

        rules:
        - host: "{{ k8s_serving_hostname }}"
          http:
            paths:
            - pathType: Prefix
              path: /
              backend:
                service:
                  name: gitlab-web
                  port: 
                    number: 80
