- name: "redis Deployment"
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: redis
        namespace: "{{ k8s_namespace }}"
        labels:
          app: redis
      spec:
        selector:
          matchLabels:
            app: redis
        replicas: 1
        template:
          metadata:
            labels:
              app: redis
          spec:
            containers:
            - name: master
              image: quay.io/bitnami/redis:latest
              ports:
              - containerPort: 6379
              env:
                - name: REDIS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: gitlab-passwords
                      key: gitlab_rails_redis_password.txt

- name: "redis Service"
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: redis
        namespace: "{{ k8s_namespace }}"
        labels:
          app: redis
      spec:
        ports:
        - name: redis
          port: 6379
          targetPort: 6379
        selector:
          app: redis
