traefik_monitoring_dynamic_config_file: "{{ traefik_dynamic_config_dir }}/monitoring.yml"
_traefik_isas_fsd_noc_secrets: "{{ lookup('pipe', 'keybase fs read /keybase/team/epfl_gitlab/nginx_metrics.yml') | from_yaml }}"
traefik_isas_fsd_noc_htpasswd_line: "idev-fsd-noc:{{ _traefik_isas_fsd_noc_secrets.password | password_hash('bcrypt', (inventory_hostname + '_1') | bcrypt_salt) }}"

