# To edit the encrypted secrets below, you need eyaml installed.
# Familiarize yourself with
# https://puppet.com/blog/encrypt-your-data-using-hiera-eyaml first.
# The edit command goes like this,
#
#   ansible-deps-cache/bin/eyaml edit -d \
#       --pkcs7-public-key eyaml/epfl_gitlab.pkcs7.pem \
#       roles/rke2-gitlab/vars/monitoring-secrets.yml
#
# 💡 This *will not* decrypt anything for you because chances are, you
# don't need to decrypt secrets (YA RLY). For those cases where you
# do, wielding the private key from Keybase is left as an exercise to
# the reader.

eyaml_keys:
  priv: /keybase/team/epfl_gitlab/eyaml/private_key.pkcs7.pem
  pub: "{{ playbook_dir }}/eyaml/epfl_gitlab.pkcs7.pem"

alertmanager:
   hostname: am.noc.fsd.team
   # Same as in /keybase/team/epfl_idevfsd/idevfsd-NOC/ansible_noc_secrets.yml
   username: gitlab-rancher-alertmanager
   password: ENC[PKCS7,MIIBiQYJKoZIhvcNAQcDoIIBejCCAXYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAey5HdldJ2TIxAuwjTmHNKbngZyIla9t9CZ5FhL0l9qFyfJrdl6SuylLkwUp/nE0J8ykjulXJVOhverRu3BCXRW+unIMelusPCNkTswYDc7IPlTRi9x+UIAmkvzwVIL0Z2z9+koZZ/1+tC/JWXl7NEA4Xbl9fDtHaZ8EDjB0yhFoITGAkO2wzb6ZHdQFch/Af1+wCWa3WUNkDzqtkeg81m1EQUWEHfkirEKuRWOqC0olnOrkw7xTjHV2BEr4CycHyAuSCrpHhvFtrJ3HpK/GQnGPdtA2cne8txZXidBb9Ku6Yr/LIhhho9V2YycdKltXyejtHawQIKmrlsKXN9WfgqzBMBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBD2p4x+OWJK37DGiERkmjXlgCA78t1VRZvhp3mloXRqGF4dJWV9ZlPfNO2FPP7eqvhcBQ==]
