# To edit the encrypted secrets below, you need eyaml installed.
# Familiarize yourself with
# https://puppet.com/blog/encrypt-your-data-using-hiera-eyaml first.
# The edit command goes like this,
#
#   ansible-deps-cache/bin/eyaml edit -d \
#       --pkcs7-public-key eyaml/epfl_gitlab.pkcs7.pem \
#       roles/rke2-gitlab/vars/monitoring-secrets.yml
#
# 💡 This *will not* decrypt anything for you because chances are, you
# don't need to decrypt secrets (YA RLY). For those cases where you
# do, wielding the private key from Keybase is left as an exercise to
# the reader.

eyaml_keys:
  priv: /keybase/team/epfl_gitlab/eyaml/private_key.pkcs7.pem
  pub: "{{ playbook_dir }}/eyaml/epfl_gitlab.pkcs7.pem"

alertmanager:
   hostname: am.noc.fsd.team
   # Same as in /keybase/team/epfl_idevfsd/idevfsd-NOC/ansible_noc_secrets.yml
   username: gitlab-rancher-alertmanager
   password: ENC[PKCS7,MIIBiQYJKoZIhvcNAQcDoIIBejCCAXYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAey5HdldJ2TIxAuwjTmHNKbngZyIla9t9CZ5FhL0l9qFyfJrdl6SuylLkwUp/nE0J8ykjulXJVOhverRu3BCXRW+unIMelusPCNkTswYDc7IPlTRi9x+UIAmkvzwVIL0Z2z9+koZZ/1+tC/JWXl7NEA4Xbl9fDtHaZ8EDjB0yhFoITGAkO2wzb6ZHdQFch/Af1+wCWa3WUNkDzqtkeg81m1EQUWEHfkirEKuRWOqC0olnOrkw7xTjHV2BEr4CycHyAuSCrpHhvFtrJ3HpK/GQnGPdtA2cne8txZXidBb9Ku6Yr/LIhhho9V2YycdKltXyejtHawQIKmrlsKXN9WfgqzBMBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBD2p4x+OWJK37DGiERkmjXlgCA78t1VRZvhp3mloXRqGF4dJWV9ZlPfNO2FPP7eqvhcBQ==]

prometheus:
  basicauth:
    # Both of these accounts are also in /keybase/team/epfl_idevfsd/idevfsd-NOC/ansible_noc_secrets.yml
    - user: admin
      password: ENC[PKCS7,MIIBiQYJKoZIhvcNAQcDoIIBejCCAXYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAYdi5JoOQm5OBr9Lyz1051ed5eKWuymIoNcAKBLw0YG3RGqYURvty91Cb0NNsr0LvCfh1BncCPJzrZCMOJ1BfvJBx/6pEnY+3CiRyiUXERKWCQw12Rl7596wN6Q9ByorjqvjS5cwy9QfxCSkoweVeT00Bx7PMa2JVseSIVpkhA+ZH7yVmtIlDQ/5ZoBf9/YjzIBopVvWFMO3yCbXGBrImWiCgi7wgdXrFke4dlgC3miTALG0zHko5uOvb2Wd3AUuOzf0BtezNkTqftpkzYNJT9Aq4zdbgLwyZS260uXRE0hQc/c+Q37oTkI10tdpAdgJuEwuuI8tGdnbY1UMnA4VMUjBMBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBBuouc6KdybwDKwpBHA0VxagCBpixYHEGohQgOnKuYEmPtSiMIarhrA2xqE9n2XqsRDcg==]
    - user: external-noc-federate
      password: ENC[PKCS7,MIIBiQYJKoZIhvcNAQcDoIIBejCCAXYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAdMaAxAymjYkZ9lRCyoeWZH3w0rLUKentG0SlYPewz7svBxA7dHoUl2RT6bAaHPq2T7ua3wJv4oRI1Wc+uiU4wIO5gcwNN67aDmiJr+2ooPeDkCVb5T8wE8nOqMstkoMijVbMX5IZIcNTJDEYRphrCccbEO5dZFhXPj4PSZNEWbur/f+9WczdTduv2LWDhQTnRmmgmjTMC+MIoBA9A6DVi0keR3stGR5NvJQ3n28KjdgoFoiwZuBX3LE6Y/GExReopimfwVwysy42uuGc/G9ycwwFSCVb5ZUyWLSPPb7++DTjgPPl+TXzB3NBTbb4cNwvSv9/h6CIcaXYvH2WUWEJkjBMBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBCexLsLL3Q60Egnoc0wkcQZgCCI414NG38rJaneROipMaHZQUYuMsN/kygp5qfeMGtYIQ==]
  # Courtesy `pwgen 22` (not 21, not 23 — passlib is finicky like that)
  basicauth_salt: Iepheu9meBie5Wax0aeT9i
