# Install Gitlab Statistics Prometheus Exporter
- include_vars: GitlabStatisticsPrometheusExporter-secrets.yml
  tags: always

- name: GitlabStatsExporter container
  docker_container:
    name: GitlabStatsExporter
    detach: yes
    image: epfldojo/gitlabstatisticsprometheusexporter:latest
    restart_policy: unless-stopped
    user: node
    working_dir: /app
    env:
      NODE_ENV: production
      PRIVATE_TOKEN: "{{ _gitlab_statistics_exporter_secrets.private_token }}"
      GITLAB_URL: https://gitlab.epfl.ch
    network_mode: "{{ docker_network_name }}"
