- name: Docker and Python dependencies
  import_tasks: deps.yml
  tags:
    - infrastructure
    - deps

- name: "{{ docker_network_name }} Docker network"
  docker_network:
    name: "{{ docker_network_name }}"
  tags:
    - infrastructure

- name: "“Sorry server”"
  import_tasks: sorryserver.yml
  tags:
    - infrastructure
    - sorryserver

- name: "GitlabStatisticsPrometheusExporter"
  import_tasks: GitlabStatisticsPrometheusExporter.yml
  tags:
    - infrastructure
    - statistics
