_traefik_idev_fsd_noc_secrets: "{{ lookup('file', '/keybase/team/epfl_gitlab/nginx_metrics.yml') | from_yaml }}"
traefik_idev_fsd_noc_htpasswd_line: "idev-fsd-noc:{{ _traefik_idev_fsd_noc_secrets.password | htpasswd }}"
