- tags: always
  include_vars: "{{ item }}"
  with_items:
    - build-vars.yml
    - ../../../vars/versions.yml

- tags: always
  include_vars:
    name: runner_credentials
    file: runner-credentials.yml

- name: "`namespace/{{ gitlab_build_namespace }}`"
  epfl_si.k8s.k8s:
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: '{{ gitlab_build_namespace }}'

- name: "`secret/gitlab-registration-token`"
  epfl_si.k8s.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        namespace: '{{ gitlab_build_namespace }}'
        name: gitlab-registration-token
      stringData:
        runner-registration-token: >-
          {{ runner_credentials.runner.token
          | eyaml(runner_credentials.eyaml_keys) }}

- name: "`secret/svc1160-builder`"
  epfl_si.k8s.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        namespace: '{{ gitlab_build_namespace }}'
        name: svc1160-builder
      type: kubernetes.io/dockerconfigjson
      stringData:
        .dockerconfigjson: >-
          {{ _quay_robot_account | epfl_si.quay.format_docker_config_json | string }}
  vars:
    _quay_robot_account:
      quay_hostname: "{{ ansible_quay_hostname }}"
      name: >-
        {{ runner_credentials.quay_builder_robot_account.name }}
      token: >-
        {{ runner_credentials.quay_builder_robot_account.token
        | eyaml(runner_credentials.eyaml_keys) }}

- name: "Mirror {{ gitlab_runner_alpine_image.original }} to Quay"
  epfl_si.quay.quay_repository:
    organization: "{{ gitlab_runner_alpine_image_mirrored.organization }}"
    name: "{{ gitlab_runner_alpine_image_mirrored.shortname }}"
    description: "Mirrored from {{ _mirrored_from_short }}"
    visibility: public
    mirror:
      from: "{{ _mirrored_from_short }}"
      robot_account: "{{ gitlab_runner_mirrorist_quay_robot_account }}"
      tags: ["{{ _mirrored_from_tag }}"]
  vars:
    _mirrored_from_short: >-
      {{ gitlab_runner_alpine_image.original | split(":") | first }}
    _mirrored_from_tag: >-
      {{ gitlab_runner_alpine_image.original | split(":") | last }}

- name: Make sure that the GitLab runner can pull the mirrored image
  # Note: we don't want to use
  # anonymous.apps.t-ocp-its-01.xaas.epfl.ch for that, both for
  # future-proof-ness (as the `t-` part of the name implies, this
  # service is fragile) and because it would cause additional
  # firewalling headaches.
  epfl_si.quay.robot_account_permission:
    robot_account_name: "{{ runner_credentials.quay_builder_robot_account.name }}"
    organization: "{{ gitlab_runner_quay_organization }}"
    repository_name: "alpine"
    permission: read

- name: "`gitlab/gitlab-runner` Helm chart"
  epfl_si.rancher.rancher_helm_chart:
    repository: gitlab
    chart: gitlab-runner
    namespace: "{{ gitlab_build_namespace }}"
    version: "{{ gitlab_runner_chart_version }}"
    values:
      gitlabUrl: https://gitlab.com
      rbac:
        create: true
      serviceAccount:
        create: true
      secrets:
        - name: gitlab-registration-token
      # Configure extra environment in the executor'd pods as per
      # https://docs.gitlab.com/runner/executors/kubernetes/index.html#overwrite-generated-pod-specifications
      runners:
        config: |
          [[runners]]
            [runners.feature_flags]
            # For some reason the feature flag only works here, not as
            # an environment variable for the gitlab-runner pod:
            FF_USE_ADVANCED_POD_SPEC_CONFIGURATION = true
            [runners.kubernetes]
                image = "{{ gitlab_runner_alpine_image.mirrored }}"
                image_pull_secrets = ["svc1160-builder"]

                [[runners.kubernetes.volumes.secret]]
                name = "svc1160-builder"
                mount_path = "/kaniko/.docker"
                read_only = true
                [runners.kubernetes.volumes.secret.items]
                ".dockerconfigjson" = "config.json"

                [[runners.kubernetes.pod_spec]]
                  name = "Use temporary space on NFS for builds"
                  patch = '''
                    containers:
                    - name: build
                      volumeMounts:
                      - name: builds
                        mountPath: /builds
                    - name: helper
                      volumeMounts:
                      - name: builds
                        mountPath: /builds
                    volumes:
                    - name: builds
                      ephemeral:
                        volumeClaimTemplate:
                          spec:
                            storageClassName: nfs-client
                            accessModes: [ ReadWriteOnce ]
                            resources:
                              requests:
                                storage: 10Gi
                  '''

- name: Check build automation (manual task)
  ansible.builtin.pause:
    prompt: |
      🛑 Please ensure that your RKE2 cluster's GitLab runner is now
      able to build container images out of the project's public
      repository on GitLab.com .

      Just browse
      https://gitlab.com/epfl-isasfsd/gitlab-ops/-/pipelines , log in
      if required (top right) and click New pipeline without setting
      any variables. Click on red things (if any) that pop up to
      figure out problems.

      💡 If you see

        error checking push permissions [blah blah] dial tcp [blah]:
        i/o timeout

      it means that your cluster lacks IP-level access to
      quay-its.epfl.ch through the DMZ firewall. Request it from
      portal-xaas-its.epfl.ch → My Services → Service Broker →
      left-hand side menu → Virtual Machines → (search for each VM in
      the cluster) → ⋮ → [DMZ] Reconfigure ; and wait for whatever
      needs to happen after that to complete (up to and including
      execution by a human operator of as many ServiceNow tickets as
      there are nodes in the RKE2 clusters).

      Once that is done (or before if you are feeling lazy), press C
      and Enter to continue:
