# Storage-related tasks, including Gitaly setup

- tags: always
  include_vars: "{{ item }}"
  with_items:
    - gitlab-vars.yml
    - ../../../vars/versions.yml

# We have to create the PVC if we want statically allocated storage;
# that much is documented in the box below
# https://docs.gitlab.com/charts/charts/gitlab/gitaly/#git-repository-persistence .
#
# However, what is *not* explained there is that one *cannot* pick any
# PVC name they want!! Someone apparently got bit by that, and took it
# upon themselves to explain what to do at
# https://github.com/xinity/custom-gitlab/blob/master/doc/installation/storage.md#manually-creating-persistentvolumeclaims
- name: "pvc/repo-data-gitaly-epfl-public-gitaly-0"
  epfl_si.k8s.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: repo-data-gitaly-epfl-public-gitaly-0
        namespace: "{{ inventory_namespace }}"
        labels:
          gitaly-repo-data-owner: epfl
      spec:
        accessModes:
          - ReadWriteMany
        volumeName: repo-data-epfl-public
        resources:
          requests:
            storage: "{{ gitlab_repo_volume_size }}"
        storageClassName: ""    # Prevents OUT0011449 😜

- name: "pv/repo-data-epfl-public"
  epfl_si.k8s.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: repo-data-epfl-public
        labels:
          gitaly-repo-data-owner: epfl
      spec:
        capacity:
          storage: "{{ gitlab_repo_volume_size }}"
        accessModes:
          - ReadWriteMany
        mountOptions:
          - nfsvers=3
        nfs:
          # As seen in https://portal-xaas-its.epfl.ch/automation/#/service/catalog/consume/deployment/15c5d030-fc77-449c-a33f-bf0a537d4d5e
          server: nas-app-ma-nfs1.epfl.ch
          path: "/si_gitlab_app/repositories"
        claimRef:                     # Pre-binding to the specific PVC defined above
          namespace: "{{ inventory_namespace }}"
          name: repo-data-gitaly-epfl-public-gitaly-0

- tags: always
  set_fact:
    _gitaly_helm_values: >-
         {{ _values_yaml | from_yaml
         | combine(gitlab_charts_common_values, recursive=True) }}
  vars:
    _values_yaml: |
      # Documentation: https://docs.gitlab.com/charts/charts/globals/#configure-host-settings
      global:
        gitaly:
          enabled: true
          authToken:
            secret: gitlab-gitaly-secret
            key: token

        certificates:
          enabled: true
          customCAs:
            - secret: gitlab-tls

        # Just to prevent Gitaly from attempting to trust (= mount the
        # certificates of) a nonexistent CA. 💡 `true` is not really
        # a permitted value here in the general case, but hey — It
        # works!
        ingress:
          tls: true

        appConfig:
          object_store:
            enabled: true
            connection:
              secret: gitlab-rails-secret

        postgresql:
          persistence:
            enabled: true
            existingClaim: gitlab-postgresql-pvc

        # Loop back to the services in the other chart
        redis:
          host: gitlab-redis-master
        workhorse:
          host: gitlab-webservice-default

      gitlab:
        gitaly:
          persistence:
            enabled: true
            storageClass: "-"   # Meaning, no auto-provisioning

        # Disable non gitaly-related services
        webservice:
          enabled: false
        sidekiq:
          enabled: false
        toolbox:
          enabled: false
        migrations:
          enabled: false
        gitlab-shell:
          enabled: false
        gitlab-exporter:
          enabled: false
        praefect:
          enabled: false
        exporter:
          enabled: false

      # Disable non gitaly-related services
      shared-secrets:
        enabled: false
      nginx-ingress:
        enabled: false
      gitlab-runner:
        install: false
      postgresql:
        install: false
      redis:
        install: false

# Pass `-t gitlab.storage.debug` to perform dry-run testing with e.g.
#
#   ```
#   helm diff upgrade --values gitaly-values.yaml \
#       -n gitlab gitaly-epfl-public gitlab/gitlab
#   ```
- tags: gitlab.storage.debug
  when: >-
    "gitlab.storage.debug" in ansible_run_tags
  delegate_to: localhost
  copy:
    dest: gitaly-values.yaml
    content: "{{ _gitaly_helm_values | to_nice_yaml }}"

- name: '“Public” Gitaly Helm chart in `{{ inventory_namespace }}` namespace'
  epfl_si.rancher.rancher_helm_chart:
      repository: gitlab
      chart: gitlab
      release: gitaly-epfl-public
      namespace: "{{ inventory_namespace }}"
      version: "{{ gitlab_chart_version }}"
      values: "{{ _gitaly_helm_values }}"

