- tags: always
  include_vars: "{{ item }}"
  with_items:
    - openid-secrets.yml
    - ../../../vars/versions.yml

- tags: always
  include_vars:
    name: gitlab_credentials
    file: gitlab-credentials.yml

- name: "gitlab-epfl-provider Secret"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: gitlab-epfl-provider
        namespace: "{{ gitlab_namespace }}"
      type: Opaque
      data:
        provider:
          '{{ epfl_provider | to_nice_json | b64encode }}'

- name: "gitlab-guest-provider Secret"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: gitlab-guest-provider
        namespace: "{{ gitlab_namespace }}"
      type: Opaque
      data:
        provider:
          '{{ guest_provider | to_nice_json | b64encode }}'

# We have to create the PVC if we want statically allocated storage;
# that much is documented in the box below
# https://docs.gitlab.com/charts/charts/gitlab/gitaly/#git-repository-persistence .
#
# However, what is *not* explained there is that one *cannot* pick any
# PVC name they want!! Someone apparently got bit by that, and took it
# upon themselves to explain what to do at
# https://github.com/xinity/custom-gitlab/blob/master/doc/installation/storage.md#manually-creating-persistentvolumeclaims
- name: "pvc/repo-data-gitaly-epfl-public-gitaly-0"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: repo-data-gitaly-epfl-public-gitaly-0
        namespace: "{{ gitlab_namespace }}"
        labels:
          gitaly-repo-data-owner: epfl
      spec:
        accessModes:
          - ReadWriteMany
        volumeName: repo-data-epfl-public
        resources:
          requests:
            storage: "{{ gitlab_repo_volume_size }}"
        storageClassName: ""

- name: "pv/repo-data-epfl-public"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: repo-data-epfl-public
        labels:
          gitaly-repo-data-owner: epfl
      spec:
        capacity:
          storage: "{{ gitlab_repo_volume_size }}"
        accessModes:
          - ReadWriteMany
        mountOptions:
          - nfsvers=3
        nfs:
          # As seen in https://portal-xaas-its.epfl.ch/automation/#/service/catalog/consume/deployment/15c5d030-fc77-449c-a33f-bf0a537d4d5e
          # 💡 This is the OUT0011449-safe path ☺ We'll just `mv` the goods
          # to there at the end, if we can make a full install / uninstall
          # cycle without something or other going all rimraf'y on us.
          server: nas-app-ma-nfs1.epfl.ch
          path: "/si_gitlab_app/repositories"
        claimRef:                     # Pre-binding to the specific PVC defined above
          namespace: "{{ gitlab_namespace }}"
          name: repo-data-gitaly-epfl-public-gitaly-0

- name: "Secret/gitlab-backups"
  epfl_si.k8s.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: gitlab-backups
        namespace: "{{ gitlab_namespace }}"
      type: Opaque
      stringData:
        # Documentation: https://gitlab.com/gitlab-org/charts/gitlab/-/blob/master/examples/objectstorage/rails.s3.yaml
        config: |
          provider: AWS
          # Specify the region
          region: us-east-1
          # Specify access/secret keys
          aws_access_key_id: {{ gitlab_credentials.s3_backups.access_key_id
                                | eyaml(gitlab_credentials.eyaml_keys) }}
          aws_secret_access_key: {{ gitlab_credentials.s3_backups.secret_access_key
                                | eyaml(gitlab_credentials.eyaml_keys) }}
          endpoint: {{ gitlab_credentials.s3_backups.url }}

- name: "Deploy gitlab chart inside `{{ gitlab_namespace }}` namespace"
  epfl_si.rancher.rancher_helm_chart:
      repository: gitlab
      chart: gitlab
      namespace: "{{ gitlab_namespace }}"
      version: "{{ gitlab_chart_version }}"
      values: "{{ _values_yaml | from_yaml }}"
  vars:
    _values_yaml: |
      # Documentation: https://docs.gitlab.com/charts/charts/globals/#configure-host-settings
      global:
        gitlabVersion: "{{ gitlab_version }}"
        edition: ce
        time_zone: "Europe/Zurich"
        hosts:
          domain: "{{ gitlab_hostname }}"
          gitlab:
            name: "{{ gitlab_hostname }}"

        ingress:
          # Reference to the existing traefik IngressClass
          class: traefik
          configureCertmanager: false
          tls:
            secretName: gitlab-next-tls

        # Documentation: https://docs.gitlab.com/integration/omniauth/#configure-common-settings
        appConfig:
          omniauth:
            enabled: true
            allowSingleSignOn: ['oidc_entra_epfl', 'oidc_switch_edu_id_guest']
            blockAutoCreatedUsers: false
            autoLinkUser: ['oidc_entra_epfl', 'oidc_switch_edu_id_guest']
            syncProfileFromProvider: ['oidc_entra_epfl', 'oidc_switch_edu_id_guest']
            syncProfileAttributes: ['name', 'email']
            externalProviders: ['oidc_switch_edu_id_guest']
            providers:
              - secret: gitlab-epfl-provider
              - secret: gitlab-guest-provider
      {% for storage_modality in ["artifacts", "lfs", "uploads", "packages"] %}
          {{ storage_modality }}:
            enabled: false
      {% endfor %}
          backups:
            bucket: {{ gitlab_credentials.s3_backups.bucket_name }}
            # See also gitlab.toolbox.backups.objectStorage, below

        extraEnv:
          GITLAB_LOG_LEVEL: "error"
          # Force redeploy on secret change. Chart currently does not support pod annotation
          CHECKSUM_EPFL_PROVIDER: "{{ epfl_provider | checksum }}"
          CHECKSUM_GUEST_PROVIDER: "{{ guest_provider | checksum }}"

        # Use external gitaly
        gitaly:
          enabled: false
          external:
            - name: default
              hostname: gitaly-epfl-public-gitaly
          authToken:
            secret: gitlab-gitaly-secret
            key: token

      gitlab:
        toolbox:
          backups:
            objectStorage:
              backend: s3
              config:
                secret: gitlab-backups
                key: config

      # Disable cert-manager because managing certificates ourselves
      certmanager:
        install: false

      # Do not create an IngressClass because traefik existing
      nginx-ingress:
        enabled: false

      gitlab-runner:
        install: false
        certsSecretName: gitlab-next-tls


# This comes after the gitlab helm chart deployment, because gitaly
# consumes the gitlab-registry-notification secret:
- name: 'Deploy "public" gitaly chart inside `{{ gitlab_namespace }}` namespace'
  epfl_si.rancher.rancher_helm_chart:
      repository: gitlab
      chart: gitlab
      release: gitaly-epfl-public
      namespace: "{{ gitlab_namespace }}"
      version: "{{ gitlab_chart_version }}"
      values: "{{ _values_yaml | from_yaml }}"
  vars:
    _values_yaml: |
      # Documentation: https://docs.gitlab.com/charts/charts/globals/#configure-host-settings
      global:
        gitlabVersion: "{{ gitlab_version }}"
        edition: ce
        time_zone: "Europe/Zurich"
        hosts:
          domain: "{{ gitlab_hostname }}"
          gitlab:
            name: "{{ gitlab_hostname }}"

        extraEnv:
          GITLAB_LOG_LEVEL: "ERROR"

        gitaly:
          enabled: true
          authToken:
            secret: gitlab-gitaly-secret
            key: token

        certificates:
          enabled: true
          customCAs:
            - secret: gitlab-next-tls

        appConfig:
          object_store:
            enabled: true
            connection:
              secret: gitlab-rails-secret

        registry:
          notificationSecret:
            secret: gitlab-registry-notification
            key: secret

        shell:
          authToken:
            secret: gitlab-gitlab-shell-secret
            key: secret

        postgresql:
          persistence:
            enabled: true
            existingClaim: gitlab-postgresql-pvc

        redis:
          host: gitlab-redis-master

        # Disable non gitaly-related services
        minio:
          enabled: false
        kas:
          enabled: false

      # Disable non gitaly-related services
      certmanager:
        install: false
      certmanager-issuer:
        install: false
        email: "none@epfl.none"
      shared-secrets:
        enabled: false
      registry:
        enabled: false
      nginx-ingress:
        enabled: false
      gitlab-runner:
        install: false
      postgresql:
        install: false
      redis:
        install: false
      gitlab:
        # Disable non gitaly-related services
        webservice:
          enabled: false
        sidekiq:
          enabled: false
        toolbox:
          enabled: false
        migrations:
          enabled: false
        gitlab-shell:
          enabled: false
        praefect:
          enabled: false
        gitaly:
          persistence:
            enabled: true
            storageClass: "-"   # Meaning, no auto-provisioning

- name: "Wait for {{ gitlab_hostname }} to come up"
  changed_when: false
  shell:
    cmd: |
      curl -s https://{{ gitlab_hostname }}
  register: _kubectl_get_gitlab
  until: >
    ansible_check_mode or ("/users/sign_in" in _kubectl_get_gitlab.stdout)
  retries: 30
  delay: 10

# Available settings : https://docs.gitlab.com/api/settings/#available-settings
- name: "Disable gitlab signup and password login"
  shell:
    cmd: |
      curl -s --request PUT \
      --header "PRIVATE-TOKEN: {{ gitlab_credentials.api_token | eyaml(gitlab_credentials.eyaml_keys) }}" \
      --url "https://{{ gitlab_hostname }}/api/v4/application/settings\
      ?signup_enabled=false\
      &password_authentication_enabled_for_web=false\
      &password_authentication_enabled_for_git=false"
