- tags: always
  include_vars: "{{ item }}"
  with_items:
    - openid-secrets.yml
    - gitlab-credentials.yml
    - ../../../vars/versions.yml

- tags: always
  include_vars:
    name: gitlab_credentials
    file: gitlab-credentials.yml

- name: "gitlab-epfl-provider Secret"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: gitlab-epfl-provider
        namespace: "{{ gitlab_namespace }}"
      type: Opaque
      data:
        provider:
          '{{ epfl_provider | to_nice_json | b64encode }}'

- name: "gitlab-guest-provider Secret"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: gitlab-guest-provider
        namespace: "{{ gitlab_namespace }}"
      type: Opaque
      data:
        provider:
          '{{ guest_provider | to_nice_json | b64encode }}'

- name: "repo-data-gitlab-gitaly-pv PersistentVolume"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: "repo-data-gitlab-gitaly-pv"
        labels:
          name: repo-data
      spec:
        capacity:
          storage: 1Ti
        storageClassName: nfs-client
        accessModes:
          - ReadOnlyMany
        mountOptions:
          - nfsvers=3
        nfs:
          server: nas-app-ma-nfs1.epfl.ch
          path: "/si_gitlab_app/data/repositories"
        # Do the Right Thing when deleting/recreating the namespace:
        persistentVolumeReclaimPolicy: "Recycle"

- name: "Deploy gitlab chart inside `{{ gitlab_namespace }}` namespace"
  epfl_si.rancher.rancher_helm_chart:
      repository: gitlab
      chart: gitlab
      namespace: "{{ gitlab_namespace }}"
      version: "{{ gitlab_chart_version }}"
      values: "{{ gitlab_values }}"

# This is called after the gitlab helm chart deployment because gitaly needs gitlab-registry-notification secret to be already generated
- name: "Deploy gitaly chart inside `{{ gitlab_namespace }}` namespace"
  epfl_si.rancher.rancher_helm_chart:
      repository: gitlab
      chart: gitlab
      release: gitaly
      namespace: "{{ gitlab_namespace }}"
      version: "{{ gitlab_chart_version }}"
      values: "{{ gitaly_values }}"

- name: "Waiting {{ gitlab_hostname }} up"
  changed_when: false
  shell:
    cmd: |
      curl -s https://{{ gitlab_hostname }}
  register: _kubectl_get_gitlab
  until: >
    ansible_check_mode or ("/users/sign_in" in _kubectl_get_gitlab.stdout)
  retries: 30
  delay: 10

# Available settings : https://docs.gitlab.com/api/settings/#available-settings
- name: "Disable gitlab signup and password login"
  shell:
    cmd: |
      curl -s --request PUT \
      --header "PRIVATE-TOKEN: {{ gitlab_credentials.api_token | eyaml(gitlab_credentials.eyaml_keys) }}" \
      --url "https://{{ gitlab_hostname }}/api/v4/application/settings\
      ?signup_enabled=false\
      &password_authentication_enabled_for_web=false\
      &password_authentication_enabled_for_git=false"