- tags: always
  include_vars: "{{ item }}"
  with_items:
    - openid-secrets.yml
    - gitlab-credentials.yml
    - ../../../vars/versions.yml

- tags: always
  include_vars:
    name: gitlab_credentials
    file: gitlab-credentials.yml

- name: "gitlab-epfl-provider Secret"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: gitlab-epfl-provider
        namespace: "{{ gitlab_namespace }}"
      type: Opaque
      data:
        provider:
          '{{ epfl_provider | to_nice_json | b64encode }}'

- name: "gitlab-guest-provider Secret"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: gitlab-guest-provider
        namespace: "{{ gitlab_namespace }}"
      type: Opaque
      data:
        provider:
          '{{ guest_provider | to_nice_json | b64encode }}'

- name: "repo-data-gitlab-gitaly-pv PersistentVolume"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: "repo-data-gitlab-gitaly-pv"
        labels:
          name: repo-data
      spec:
        capacity:
          storage: 1Ti
        accessModes:
          - ReadOnlyMany
        mountOptions:
          - nfsvers=3
        nfs:
          server: nas-app-ma-nfs1.epfl.ch
          path: "/si_gitlab_app/data/repositories"

- name: "Deploy gitlab chart inside `{{ gitlab_namespace }}` namespace"
  epfl_si.rancher.rancher_helm_chart:
      repository: gitlab
      chart: gitlab
      namespace: "{{ gitlab_namespace }}"
      version: "{{ gitlab_chart_version }}"
      values: "{{ _values_yaml | from_yaml }}"
  vars:
    _values_yaml: |
      # Documentation: https://docs.gitlab.com/charts/charts/globals/#configure-host-settings
      global:
        gitlabVersion: "{{ gitlab_version }}"
        edition: ce
        time_zone: "Europe/Zurich"
        hosts:
          domain: "{{ gitlab_hostname }}"
          gitlab:
            name: "{{ gitlab_hostname }}"

        ingress:
          # Reference to the existing traefik IngressClass
          class: traefik
          configureCertmanager: false
          tls:
            secretName: gitlab-next-tls

        # Documentation: https://docs.gitlab.com/integration/omniauth/#configure-common-settings
        appConfig:
          omniauth:
            enabled: true
            allowSingleSignOn: ['oidc_entra_epfl', 'oidc_switch_edu_id_guest']
            blockAutoCreatedUsers: false
            autoLinkUser: ['oidc_entra_epfl', 'oidc_switch_edu_id_guest']
            syncProfileFromProvider: ['oidc_entra_epfl', 'oidc_switch_edu_id_guest']
            syncProfileAttributes: ['name', 'email']
            externalProviders: ['oidc_switch_edu_id_guest']
            providers:
              - secret: gitlab-epfl-provider
              - secret: gitlab-guest-provider

        extraEnv:
          GITLAB_LOG_LEVEL: "error"
          # Force redeploy on secret change. Chart currently does not support pod annotation
          CHECKSUM_EPFL_PROVIDER: "{{ epfl_provider | checksum }}"
          CHECKSUM_GUEST_PROVIDER: "{{ guest_provider | checksum }}"

        # Use external gitaly
        gitaly:
          enabled: false
          external:
            - name: default
              hostname: gitaly-gitaly
          authToken:
            secret: gitlab-gitaly-secret
            key: token

      # Disable cert-manager because managing certificates ourselves
      certmanager:
        install: false

      # Do not create an IngressClass because traefik existing
      nginx-ingress:
        enabled: false

      gitlab-runner:
        install: false
        certsSecretName: gitlab-next-tls


# This is called after the gitlab helm chart deployment because gitaly needs gitlab-registry-notification secret to be already generated
- name: "Deploy gitaly chart inside `{{ gitlab_namespace }}` namespace"
  epfl_si.rancher.rancher_helm_chart:
      repository: gitlab
      chart: gitlab
      release: gitaly
      namespace: "{{ gitlab_namespace }}"
      version: "{{ gitlab_chart_version }}"
      values: "{{ _values_yaml | from_yaml }}"
  vars:
    _values_yaml: |
      # Documentation: https://docs.gitlab.com/charts/charts/globals/#configure-host-settings
      global:
        gitlabVersion: "{{ gitlab_version }}"
        edition: ce
        time_zone: "Europe/Zurich"
        hosts:
          domain: "{{ gitlab_hostname }}"
          gitlab:
            name: "{{ gitlab_hostname }}"

        extraEnv:
          GITLAB_LOG_LEVEL: "ERROR"

        gitaly:
          enabled: true
          authToken:
            secret: gitlab-gitaly-secret
            key: token
          persistence:
            accessMode: ReadOnlyMany
            size: 1Ti
            matchLabels:
              name: repo-data

        certificates:
          enabled: true
          customCAs:
            - secret: gitlab-next-tls

        appConfig:
          object_store:
            enabled: true
            connection:
              secret: gitlab-rails-secret

        registry:
          notificationSecret:
            secret: gitlab-registry-notification
            key: secret

        shell:
          authToken:
            secret: gitlab-gitlab-shell-secret
            key: secret

        postgresql:
          persistence:
            enabled: true
            existingClaim: gitlab-postgresql-pvc

        redis:
          host: gitlab-redis-master

        # Disable non gitaly-related services
        minio:
          enabled: false
        kas:
          enabled: false

      # Disable non gitaly-related services
      certmanager:
        install: false
      certmanager-issuer:
        install: false
        email: "none@epfl.none"
      shared-secrets:
        enabled: false
      registry:
        enabled: false
      nginx-ingress:
        enabled: false
      gitlab-runner:
        install: false
      postgresql:
        install: false
      redis:
        install: false
      gitlab:
        # Gitaly : use existing PV instead of creating a new PV
        gitaly:
          persistence:
            enabled: true
            accessMode: ReadOnlyMany
            size: 1Ti
            matchLabels:
              name: repo-data
        # Disable non gitaly-related services
        webservice:
          enabled: false
        sidekiq:
          enabled: false
        toolbox:
          enabled: false
        migrations:
          enabled: false
        gitlab-shell:
          enabled: false
        praefect:
          enabled: false

- name: "Waiting {{ gitlab_hostname }} up"
  changed_when: false
  shell:
    cmd: |
      curl -s https://{{ gitlab_hostname }}
  register: _kubectl_get_gitlab
  until: >
    ansible_check_mode or ("/users/sign_in" in _kubectl_get_gitlab.stdout)
  retries: 30
  delay: 10

# Available settings : https://docs.gitlab.com/api/settings/#available-settings
- name: "Disable gitlab signup and password login"
  shell:
    cmd: |
      curl -s --request PUT \
      --header "PRIVATE-TOKEN: {{ gitlab_credentials.api_token | eyaml(gitlab_credentials.eyaml_keys) }}" \
      --url "https://{{ gitlab_hostname }}/api/v4/application/settings\
      ?signup_enabled=false\
      &password_authentication_enabled_for_web=false\
      &password_authentication_enabled_for_git=false"
