- tags: always
  include_tasks:
    file: ../../../tasks/_rancher_login.yml
    apply:
      tags: always
      vars:
        ansible_rancher_url: https://rancher-fsd.epfl.ch
        ansible_rancher_credentials_dir: "rke2-credentials-cache"
        ansible_rancher_cluster_name: gitlab

- tags: always
  include_vars: gitlab-vars.yml

- when: inventory_deployment_stage == "test"
  include_tasks:
    file: build.yml
    apply:
      tags:
        - gitlab.build
  tags:
    # Not part of `-t gitlab` (for the time being), as we use stock images
    - gitlab.build

- name: "`namespace/{{ inventory_namespace }}`"
  epfl_si.k8s.k8s:
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ inventory_namespace }}"
  tags:
    - gitlab
    - gitlab.website
    - gitlab.routing
    - gitlab.tls
    - gitlab.tls.csr

- when: inventory_deployment_stage == "prod"
  include_tasks:
    file: routing.yml
    apply:
      tags:
        - gitlab
        - gitlab.routing
  tags:
    - gitlab
    - gitlab.routing

- include_tasks:
    file: serving.yml
    apply:
      tags:
        - gitlab
        - gitlab.serving
        - gitlab.website
  tags:
    - gitlab
    - gitlab.serving
    - gitlab.serving.debug
    - gitlab.serving.redeploy
    - gitlab.serving.config
    - gitlab.website

# `gitaly` comes after `serving`, because the Gitaly Helm chart
# consumes objects (such as `Secret/gitlab-registry-notification`)
# managed by the GitLab one:
- when: inventory_deployment_stage == "prod"
  include_tasks:
    file: gitaly.yml
    apply:
      tags:
        - gitlab
        - gitlab.storage
        - gitlab.gitaly
  tags:
    - gitlab
    - gitlab.storage
    - gitlab.storage.debug
    - gitlab.gitaly

- when: inventory_deployment_stage == "prod"
  include_tasks:
    file: gitlab-stats-exporter.yml
    apply:
      tags:
      - gitlab
      - gitlab.stats
  tags:
  - gitlab
  - gitlab.stats
