- include_vars: gitlab-vars.yml
  tags: always

- name: "`ClusterRepo/gitlab`"
  epfl_si.k8s.k8s:
    definition:
      apiVersion: catalog.cattle.io/v1
      kind: ClusterRepo
      metadata:
        name: gitlab
      spec:
        url: https://charts.gitlab.io
  tags:
    - gitlab
    - gitlab.helm-repo

- include_tasks:
    file: build.yml
    apply:
      tags:
        - gitlab
        - gitlab.build
        - gitlab.runner   # Obsolescent tag
  tags:
    - gitlab
    - gitlab.build
    - gitlab.runner

- include_tasks:
    file: routing.yml
    apply:
      tags:
        - gitlab
        - gitlab.routing
  tags:
    - gitlab
    - gitlab.routing
