- include_vars: gitlab-vars.yml
  tags: always

- include_tasks:
    file: build.yml
    apply:
      tags:
        - gitlab
        - gitlab.build
  tags:
    - gitlab
    - gitlab.build

- name: "`namespace/{{ gitlab_namespace }}`"
  epfl_si.k8s.k8s:
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ gitlab_namespace }}"
  tags:
    - gitlab
    - gitlab.website
    - gitlab.routing
    - gitlab.tls
    - gitlab.tls.csr

- include_tasks:
    file: routing.yml
    apply:
      tags:
        - gitlab
        - gitlab.routing
  tags:
    - gitlab
    - gitlab.routing

- include_tasks:
    file: tls.yml
    apply:
      tags:
        - gitlab
        - gitlab.tls
  tags:
    - gitlab
    - gitlab.tls
    - gitlab.tls.csr

- include_tasks:
    file: serving.yml
    apply:
      tags:
        - gitlab
        - gitlab.serving
        - gitlab.website
  tags:
    - gitlab
    - gitlab.serving
    - gitlab.serving.debug
    - gitlab.website

# `gitaly` comes after `serving`, because the Gitaly Helm chart
# consumes objects (such as `Secret/gitlab-registry-notification`)
# managed by the GitLab one:
- include_tasks:
    file: gitaly.yml
    apply:
      tags:
        - gitlab
        - gitlab.storage
        - gitlab.gitaly
  tags:
    - gitlab
    - gitlab.storage
    - gitlab.storage.debug
    - gitlab.gitaly
