- name: "LoadBalancer Service for ingress"
  with_items:
    - name: gitlab-ingress-ipv4
      ipFamily: "IPv4"
      vip: >-
        {{ lookup("community.general.dig", gitlab_hostname) }}
      pool: gitlab
    - name: gitlab-ingress-ipv6
      ipFamily: "IPv6"
      vip: >-
        {{ lookup("community.general.dig", gitlab_hostname,
        qtype="AAAA") }}
      pool: gitlab
  epfl_si.k8s.k8s:
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ item.name }}"
        namespace: kube-system
        annotations:
          metallb.universe.tf/address-pool: "{{ item.pool }}"
      spec:
        selector:
          app.kubernetes.io/name: rke2-traefik
        type: LoadBalancer
        externalTrafficPolicy: Local
        ipFamilies: ["{{ item.ipFamily }}"]
        loadBalancerIP: "{{ item.vip }}"
        ports:
          - name: ssh
            port: 22
            targetPort: 22
            protocol: TCP
          - name: http
            port: 80
            targetPort: web
            protocol: TCP
          - name: https
            port: 443
            targetPort: websecure
            protocol: TCP

- name: "Additional configuration for `rke2-traefik` Helm chart"
  epfl_si.k8s.k8s:
    definition:
      apiVersion: helm.cattle.io/v1
      kind: HelmChartConfig
      metadata:
        name: rke2-traefik
        namespace: kube-system
      spec:
        valuesContent: |
          entryPoints:
            gitlab-shell:
              address: ":22"
          ports:
            gitlab-shell:
              port: 22
            web:
              redirections:
                entryPoint:
                  permanent: true
                  to: websecure
                  scheme: https
          additionalArguments:
            # Make dashboard visible to people who port-forward 8080:
            - --api.insecure
            # Transmit %2F's to GitLab API
            # (https://aibix.io/gitlab/gitlab-18-x-hinter-traefik-warum-ploetzlich-http-400-bei-api-calls-auftreten/):
            - --entrypoints.websecure.http.encodedCharacters.allowEncodedSlash
          ingressClass:
            # All `Ingress` objects (and `Ingress`-ish objects,
            # such as the `IngressRouteTCP` object for port 22, below)
            # must have a `kubernetes.io/ingress.class: traefik`
            # annotation set:
            name: "traefik"
          metrics:
            prometheus:
              serviceMonitor:
                enabled: true
          # Run on the control plane nodes
          tolerations:
          - operator: "Exists"   # i.e. it doesn't care about any taints
          nodeSelector:
            node-role.kubernetes.io/control-plane: "true"

- name: "IngressRouteTCP/gitlab-ssh"
  epfl_si.k8s.k8s:
    definition:
      apiVersion: traefik.io/v1alpha1
      kind: IngressRouteTCP
      metadata:
        annotations:
          kubernetes.io/ingress.class: traefik
        name: gitlab-ssh
        namespace: "{{ inventory_namespace }}"
      spec:
        entryPoints:
        - gitlab-shell
        routes:
        - match: HostSNI(`*`)
          services:
          - name: gitlab-gitlab-shell
            namespace: gitlab
            port: 22
