- tags: always
  include_vars: ../../../vars/versions.yml

- name: "`namespace/{{ gitlab_ops_runner_namespace }}`"
  epfl_si.k8s.k8s:
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: '{{ gitlab_ops_runner_namespace }}'

- name: "`secret/gitlab-registration-token`"
  epfl_si.k8s.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        namespace: '{{ gitlab_ops_runner_namespace }}'
        name: gitlab-registration-token
      stringData:
        runner-registration-token: >-
          {{ _secrets.registration_token }}
  vars:
    _secrets: >-
      {{ lookup("pipe", "keybase fs read " + gitlab_com_registration_token_secrets_path)
      | from_yaml }}

- name: "`secret/svc1160-builder-push`"
  epfl_si.k8s.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        namespace: '{{ gitlab_ops_runner_namespace }}'
        name: svc1160-builder-push
      type: kubernetes.io/dockerconfigjson
      stringData:
        .dockerconfigjson: "{{ _dockerconfigjson | to_json }}"
  vars:
    _secrets: >-
       {{ lookup("pipe", "keybase fs read " + gitlab_runner_internal_secrets_path)
       | from_yaml }}
    _userpassword: "{{ _secrets.QUAY_PUSH_USERNAME }}:{{ _secrets.QUAY_PUSH_PASSWORD }}"
    _dockerconfigjson:
      auths:
        quay-its.epfl.ch:
          email: ""
          auth: "{{ _userpassword | b64encode }}"

- name: "`gitlab/gitlab-runner` Helm chart"
  epfl_si.rancher.rancher_helm_chart:
    repository: gitlab
    chart: gitlab-runner
    namespace: "{{ gitlab_ops_runner_namespace }}"
    version: "{{ gitlab_runner_chart_version }}"
    values:
      gitlabUrl: https://gitlab.com
      rbac:
        create: true
      serviceAccount:
        create: true
      secrets:
        - name: gitlab-registration-token
      # Configure extra environment in the executor'd pods as per
      # https://docs.gitlab.com/runner/executors/kubernetes/index.html#overwrite-generated-pod-specifications
      runners:
        config: |
          [[runners]]
            [runners.kubernetes]
                [[runners.kubernetes.volumes.secret]]
                name = "svc1160-builder-push"
                mount_path = "/kaniko/.docker"
                read_only = true
                [runners.kubernetes.volumes.secret.items]
                ".dockerconfigjson" = "config.json"

- name: Check build automation (manual tasks)
  ansible.builtin.pause:
    prompt: |
      🛑 Please ensure that your RKE2 cluster's GitLab runner is now
      able to build container images out of the project's public
      repository on GitLab.com .

      Just browse
      https://gitlab.com/epfl-isasfsd/gitlab-ops/-/pipelines/new and
      click New pipeline without setting any variables. Click on red
      things (if any) that pop up to figure out problems.

      💡 If you see

        error checking push permissions [blah blah] dial tcp [blah]:
        i/o timeout

      it means that your cluster lacks IP-level access to
      quay-its.epfl.ch through the DMZ firewall. Request it from
      portal-xaas-its.epfl.ch → My Services → Service Broker →
      left-hand side menu → Virtual Machines → (search for each VM in
      the cluster) → ⋮ → [DMZ] Reconfigure ; and wait for whatever
      needs to happen after that to complete (up to and including
      execution by a human operator of as many ServiceNow tickets as
      there are nodes in the RKE2 clusters).

      Once that is done (or before if you are feeling lazy), press C
      and Enter to continue:
