# GitLab-the-Web-(and-ssh-)app (storage configured separately)

- tags: always
  include_vars: "{{ item }}"
  with_items:
    - gitlab-vars.yml
    - openid-secrets.yml
    - ../../../vars/versions.yml
    - ../../../vars/ssh-secrets.yml

- tags: always
  include_vars:
    name: gitlab_credentials
    file: gitlab-credentials.yml

- name: "`gitlab` Helm repository"
  epfl_si.k8s.helm_repository:
    name: gitlab
    repo_url: https://charts.gitlab.io

- name: "Secret/gitlab-epfl-provider (Entra)"
  register: _secret_entra_provider
  epfl_si.k8s.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: gitlab-epfl-provider
        namespace: "{{ inventory_namespace }}"
      type: Opaque
      data:
        provider:
          '{{ epfl_provider | to_nice_json | b64encode }}'

- name: "Secret/gitlab-guest-provider (SWITCH EduID)"
  register: _secret_eduid_provider
  epfl_si.k8s.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: gitlab-guest-provider
        namespace: "{{ inventory_namespace }}"
      type: Opaque
      data:
        provider:
          '{{ guest_provider | to_nice_json | b64encode }}'

- name: "Secret/gitlab-gitlab-shell-host-keys"
  register: _secret_shell_host_keys
  epfl_si.k8s.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: gitlab-gitlab-shell-host-keys
        namespace: "{{ inventory_namespace }}"
      type: Opaque
      stringData:
        ssh_host_rsa_key: >-
          {{ ssh_secrets.ssh_host_rsa_key }}
        ssh_host_rsa_key.pub: >-
          {{ ssh_secrets["ssh_host_rsa_key.pub"] }}
        ssh_host_dsa_key: >-
          {{ ssh_secrets.ssh_host_dsa_key }}
        ssh_host_dsa_key.pub: >-
          {{ ssh_secrets["ssh_host_dsa_key.pub"] }}
        ssh_host_ecdsa_key: >-
          {{ ssh_secrets.ssh_host_ecdsa_key }}
        ssh_host_ecdsa_key.pub: >-
          {{ ssh_secrets["ssh_host_ecdsa_key.pub"] }}
        ssh_host_ed25519_key: >-
          {{ ssh_secrets.ssh_host_ed25519_key }}
        ssh_host_ed25519_key.pub: >-
          {{ ssh_secrets["ssh_host_ed25519_key.pub"] }}

- name: "Secret/gitlab-backups-s3cmd"
  register: _secret_backups
  epfl_si.k8s.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: gitlab-backups-s3cmd
        namespace: "{{ inventory_namespace }}"
      type: Opaque
      stringData:
        # s3cfg INI format: https://s3tools.org/kb/item14.htm
        s3cfg: |
          [default]
          access_key = {{ _s3_backups.read_write_access_key_id
                       | eyaml(_keys) }}
          secret_key = {{ _s3_backups.read_write_secret_access_key
                       | eyaml(_keys) }}
          host_base = {{ _s3_hostname }}
          host_bucket = {{ _s3_hostname }}
          bucket_location = {{ _s3_backups.region }}
  vars:
    _keys: "{{ gitlab_credentials.eyaml_keys }}"
    _s3_backups: "{{ gitlab_credentials.s3_backups }}"
    _s3_hostname: >-
     {{ _s3_backups.url | urlsplit("hostname") }}

- name: "Secret/gitlab-s3-assets"
  register: _secret_s3_assets
  epfl_si.k8s.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: gitlab-s3-assets
        namespace: "{{ inventory_namespace }}"
      type: Opaque
      stringData:
        # Documentation: https://gitlab.com/gitlab-org/charts/gitlab/-/blob/master/examples/objectstorage/rails.s3.yaml
        uploads: |
          {{ _scality_blah }}
          aws_access_key_id:     "{{ _s3.uploads.read_write_access_key_id
                                  | eyaml(_keys) }}"
          aws_secret_access_key: "{{ _s3.uploads.read_write_secret_access_key
                                  | eyaml(_keys) }}"
        artifacts: |
          {{ _scality_blah }}
          aws_access_key_id:     "{{ _s3.artifacts.read_write_access_key_id
                                  | eyaml(_keys) }}"
          aws_secret_access_key: "{{ _s3.artifacts.read_write_secret_access_key
                                  | eyaml(_keys) }}"
        packages: |
          {{ _scality_blah }}
          aws_access_key_id:     "{{ _s3.packages.read_write_access_key_id
                                  | eyaml(_keys) }}"
          aws_secret_access_key: "{{ _s3.packages.read_write_secret_access_key
                                  | eyaml(_keys) }}"
  vars:
    _scality_blah: |
      provider: AWS
      region: us-east-1
      endpoint: "{{ gitlab_credentials.s3_backups.url }}"
      path_style: true
    _s3: "{{ gitlab_credentials.s3_storage }}"
    _keys: "{{ gitlab_credentials.eyaml_keys }}"

- tags: always
  set_fact:
    _gitlab_helm_values: >-
      {{ _values_yaml | from_yaml
      | combine(gitlab_charts_common_values, recursive=True)  }}
  vars:
    _values_yaml: |
      # Documentation: https://docs.gitlab.com/charts/charts/globals/#configure-host-settings
      global:
        ingress:
          # Reference to the existing traefik IngressClass
          class: traefik
          tls:
            secretName: gitlab-tls

        appConfig:
          # Documentation: https://docs.gitlab.com/integration/omniauth/#configure-common-settings
          omniauth:
            enabled: true
            allowSingleSignOn: ['oidc_entra_epfl', 'oidc_switch_edu_id_guest']
            blockAutoCreatedUsers: {{ "false" if inventory_deployment_stage == "prod"
                                      else "true" }}
            autoLinkUser: ['oidc_entra_epfl', 'oidc_switch_edu_id_guest']
            syncProfileFromProvider: ['oidc_entra_epfl', 'oidc_switch_edu_id_guest']
            syncProfileAttributes: ['name', 'email']
            externalProviders: ['oidc_switch_edu_id_guest']
            providers:
              - secret: gitlab-epfl-provider
              - secret: gitlab-guest-provider
          backups:
            # https://docs.gitlab.com/charts/backup-restore/#backups-to-s3
            # See also gitlab.toolbox.backups.objectStorage, below
            # 💡 Yes, it appears you *can* put slashes in there; see
            # https://gitlab.com/gitlab-org/build/CNG/-/blob/master/gitlab-toolbox/scripts/bin/backup-utility#L95
            bucket: {{ gitlab_credentials.s3_backups.bucket_name }}/backup-{{ inventory_namespace }}/
            tmpBucket: {{ gitlab_credentials.s3_backups.bucket_name }}/restoretmp-{{ inventory_namespace }}/

          artifacts:
            bucket: "{{ _s3.artifacts.bucket }}"
            connection:
              secret: gitlab-s3-assets
              key: artifacts

          packages:
            bucket: "{{ _s3.packages.bucket }}"
            connection:
              secret: gitlab-s3-assets
              key: packages

          uploads:
            bucket: "{{ _s3.uploads.bucket }}"
            connection:
              secret: gitlab-s3-assets
              key: uploads

          shell:
            authToken:
              secret: gitlab-gitlab-shell-secret
              key: secret
            hostKeys:
              secret: gitlab-gitlab-shell-host-keys

        extraEnv:
          {% if ( _secret_entra_provider  | default({}) )  is changed
             or ( _secret_eduid_provider  | default({}) )  is changed
             or ( _secret_backups  | default({}) )         is changed
             or ( _secret_shell_host_keys  | default({}) ) is changed
             or ( _secret_s3_assets  | default({}) )       is changed
             or "gitlab.serving.redeploy" in ansible_run_tags %}
          MC_HAMMER: "U can touch this {{ now() }}"
          {% endif %}

        # Use external gitaly
        gitaly:
          enabled: false
          external:
            - name: default
              hostname: gitaly-epfl-public-gitaly
          authToken:
            secret: gitlab-gitaly-secret
            key: token

      gitlab:
        toolbox:
          backups:
            cron:
              enabled: true
              schedule: 38 */3 * * *
              # Back up only the PostgreSQL state (`db`); skip
              # everything else.
              extraArgs: >-
                --skip repositories --skip registry --skip lfs --skip pages
                --skip artifacts --skip packages --skip uploads
                --skip external_diffs --skip terraform_state
                --skip ci_secure_files
                -t $(date +%Y%m%d)
            # https://docs.gitlab.com/charts/backup-restore/#backups-to-s3
            # See also global.appConfig.backups.*, above
            objectStorage:
              backend: s3
              config:
                secret: gitlab-backups-s3cmd
                key: s3cfg

        sidekiq:
          metrics:
            podMonitor:
              enabled: true

      {% if (inventory_deployment_stage == "test") %}
          minReplicas: 1
          maxReplicas: 1
      {% endif %}

        gitlab-shell:
          resources:
            limits:
              memory: 4G
      {% if (inventory_deployment_stage == "test") %}
          minReplicas: 1
          maxReplicas: 1

        webservice:
          minReplicas: 1
          maxReplicas: 1
      {% endif %}

      redis:
        metrics:
          podMonitor:
            enabled: true

      postgresql:
        image:
          tag: "{{ postgresql_major_version }}"

      # Do not create / manage an IngressClass
      nginx-ingress:
        enabled: false

      gitlab-runner:
        install: false
        certsSecretName: gitlab-tls
    _s3: "{{ gitlab_credentials.s3_storage }}"

# Pass `-t gitlab.serving.debug` to perform dry-run testing with e.g.
#
#   ```
#   helm diff upgrade --values gitlab-values-test.yaml \
#       -n gitlab-test gitlab gitlab/gitlab
#   ```
- tags: gitlab.serving.debug
  when: >-
    "gitlab.serving.debug" in ansible_run_tags
  delegate_to: localhost
  copy:
    dest: "gitlab-values-{{ inventory_deployment_stage }}.yaml"
    content: "{{ _gitlab_helm_values | to_nice_yaml }}"

- name: "GitLab Helm chart"
  epfl_si.k8s.helm:
    name: gitlab
    namespace: "{{ inventory_namespace }}"
    chart_ref: gitlab/gitlab
    force: >-
      {{ helm_force is defined }}
    chart_version: "{{ gitlab_chart_version }}"
    values: "{{ _gitlab_helm_values }}"
    post_renderer: "{{ role_path }}/scripts/gitlab-post-renderer"

- name: "Wait for {{ gitlab_hostname }} to come up"
  changed_when: false
  shell:
    cmd: |
      curl -k -s https://{{ gitlab_hostname }}
  register: _curl_gitlab
  until: >
    ansible_check_mode or ("/users/sign_in" in _curl_gitlab.stdout)
  retries: 30
  delay: 10

- name: "Disable signup and password authentication"
  tags: gitlab.serving.config
  gitlab_rails:
    namespace: "{{ inventory_namespace }}"
    ruby_postconditions_class: |
      class ConfigureLoginPage < Postconditions
        postcondition "signup disabled" do
          settings.signup_enabled = false
        end
        postcondition "password authentication disabled" do
          s = settings
          s.password_authentication_enabled_for_web = false
          s.password_authentication_enabled_for_git = false
        end

        def settings
          ApplicationSetting.first
        end
      end
