# -*- mode: yaml; -*-

all:
  children:
    gitlab_rke2_vms:
      vars:
        ansible_rancher_url: https://rancher-fsd.epfl.ch
        ansible_rancher_cluster_name: gitlab
        ansible_user: root
        ansible_python_interpreter: /usr/bin/python3
        ansible_host: "{{ inventory_hostname_short }}.xaas.epfl.ch"
      children:
        gitlab_rke2_workers:
          hosts:
            itsgitlab0004:
            itsgitlab0005:
          vars:
            rancher_rke2_is_worker: true
            rancher_rke2_is_controlplane: false
        gitlab_rke2_control_plane_nodes:
          hosts:
            itsgitlab0006:
            itsgitlab0007:
            itsgitlab0008:
          vars:
            rancher_rke2_is_worker: true   # Debatable.
            rancher_rke2_is_controlplane: true
    rke2_clusters:
      vars:
        ansible_rancher_url: https://rancher-fsd.epfl.ch
        ansible_rancher_credentials_dir: "rke2-credentials-cache"

        ansible_connection: local
        ansible_python_interpreter: "{{ ansible_playbook_python }}"
        # ... Except for `rancher_login` tasks, which do their own thing and
        # use ssh; in which case we have
        ansible_ssh_user: root

      "hosts":  # Scarequotes intended — These are Kubernetes
                # clusters, even though we access them over HTTP/S
                # from the local workstation (as opposed to ssh)
        rancher:   # Assumed to be up and running; only used in `delegate_to:` tasks
          ansible_rancher_cluster_name: local

      children:
        gitlab_rke2_clusters:
          "hosts":
            gitlab-rke2:
              inventory_deployment_stage: test
              ansible_rancher_cluster_name: gitlab
              inventory_vips:
                # This VIP was created (and assigned to a nearby VM)
                # using the old-school “day-2” action on the VM. If
                # you wanted DNS with that, you had to order it
                # separately; see https://go.epfl.ch/INC0661613
                - gitlab-next.epfl.ch
