- tags:
    - backups
    - crontab
  name: "{{ backup_crontab }}"
  copy:
    dest: "{{ backup_crontab }}"
    content: |
        #!/bin/sh

        set -e

        DUMPFILE=/srv/gitlab/backup/postgresql_dump.sql

        docker exec postgresql_prod pg_dumpall --exclude-database=postgres -c -U postgres |grep -Pv '^(DROP|CREATE|ALTER) ROLE postgres' > $DUMPFILE.NEW
        mv $DUMPFILE.NEW $DUMPFILE
