- include_vars: database-vars.yml
  tags: always

- name: Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items: >-
    {{ [redis_config_dir, postgresql_config_dir] +
       ([ postgresql_staging_scripts_dir] if inventory_hostname == "gitlabstaging"
       else []) }}

- name: Doctored passwd file for PostgreSQL
  shell:
    creates: "{{ postgresql_config_dir }}/passwd"
    cmd: |
      (
        set -e -x
        docker run --rm "{{ postgresql_docker_image }}" cat /etc/passwd
        cat <<MOAR_PASSWD
      # TODO: we could figure the 999 part from the image again.
      gitlab:x:999:999::/home/postgres:/bin/sh
      gitlab-psql:x:999:999::/home/postgres:/bin/sh
      MOAR_PASSWD
      ) > "{{ postgresql_config_dir }}/passwd"

- name: 'Staging PostgreSQL: "log-queries.sh" script'
  when: inventory_hostname == "gitlabstaging"
  copy:
    dest: "{{ postgresql_staging_scripts_dir }}/log-queries.sh"
    mode: "0755"
    content: |
      #!/bin/bash
      # Found on https://github.com/Roconda/docker-postgres-logging/blob/master/Dockerfile
      set -e

      sed -ri "s/^#log_statement.*/log_statement = 'all'/g" /var/lib/postgresql/data/postgresql.conf

- name: 'Staging PostgreSQL: SQL startup script'
  when: inventory_hostname == "gitlabstaging"
  copy:
    dest: "{{ postgresql_staging_scripts_dir }}/00-create-db.sql"
    content: |
       -- This runs first to create the staging DB (look for
       -- postgresql_staging in ../docker-compose.yml), before
       -- restoring the daily backup.
       
       -- This is actually the production database, but the name is what it is.
       CREATE DATABASE gitlabhq_production;
       
       -- The only reasons these are here is so that the daily backup can DROP them
       -- without failing.
       CREATE ROLE "gitlab";
       CREATE ROLE "gitlab-psql";

- name: 'PostgreSQL database'
  docker_container:
    name: "postgresql_{{ environment_name }}"
    image: postgres:12
    detach: yes
    restart_policy: unless-stopped
    # Kick the staging database (so that it reloads from a production
    # backup) whenever we build a new image:
    restart: >-
      {{ (environment_name == "staging")
         and (_serving_image is defined)
         and (_serving_image is changed) }}
    log_driver: json-file
    log_options:
      max-size: 50m
      max-file: "3"
    volumes: "{{ volumes[environment_name] }}"
    env:
      POSTGRES_PASSWORD: "roo3bezahBo6bohH3aY9"  # TODO: generate a stable password here.
                                                 # (It just needs to be set; the value isn't
                                                 # shared anywhere else.)
  vars:
    volumes:
      staging: '{{ staging_startup_scripts + [socket_volume, doctored_passwd_volume] }}'
      prod: '{{ [socket_volume, doctored_passwd_volume, storage_volume] }}'
    socket_volume: "/srv/gitlab/run/postgres-socket{{ socket_suffix }}:/run/postgresql/"
    doctored_passwd_volume: "{{ postgresql_config_dir }}/passwd:/etc/passwd:ro"
    storage_volume: "/srv/gitlab/postgresql/data:/var/lib/postgresql/data"
    staging_startup_scripts:
      # The staging database is *not* persistent; instead, it
      # reloads from a production backup every time it starts up.
      #
      # As per https://hub.docker.com/_/postgres/, SQL / shell
      # scripts in /docker-entrypoint-initdb.d get executed at
      # startup:
      - "{{ postgresql_staging_scripts_dir }}/log-queries.sh:/docker-entrypoint-initdb.d/log-queries.sh:ro"
      - "{{ postgresql_staging_scripts_dir }}/00-create-db.sql:/docker-entrypoint-initdb.d/00-create-db.sql:ro"
      - "/srv/gitlab/backup/postgresql_dump.sql:/docker-entrypoint-initdb.d/10-postgresql_dump.sql:ro"

- name: "{{ redis_config_dir }}/redis.conf"
  copy:
    dest: "{{ redis_config_dir }}/redis.conf"
    content: >-
      {{ lookup("template", "redis.conf.j2") }}

- name: 'Redis'
  docker_container:
    name: "redis_{{ environment_name }}"
    image: redis:latest
    log_driver: json-file
    log_options:
      max-size: 50m
      max-file: "3"
    volumes:
      - "{{ redis_config_dir }}/redis.conf:/usr/local/etc/redis/redis.conf:ro"
      - "/srv/gitlab/run/redis-socket{{ socket_suffix }}:/run/redis"
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
