- name: Serving databases
  import_tasks: databases.yml
  tags: databases

- name: Serving containers
  tags:
    - serving
  include_tasks:
    file: serving.yml
    apply:
      tags:
        - serving
