- include_vars: serving-vars.yml
  tags: always

- name: "{{ serving_build_dir | dirname }} directory"
  file:
    state: directory
    path: "{{ serving_build_dir | dirname }}"

- name: "{{ serving_build_dir }}"
  git:
    repo: https://gitlab.com/epfl-idevfsd/gitlab-docker.git
    dest: '{{ serving_build_dir }}'

- name: "{{ serving_image }}"
  docker_image:
    name: "{{ serving_image }}"
    build:
      path: '{{ serving_build_dir }}/gitlab-main'

- name: "{{ gitlab_docker_staging_hostname }}"
  docker_container:
    name: "{{ gitlab_docker_staging_hostname }}"
    image: "{{ serving_image }}"
    detach: yes
    restart_policy: unless-stopped
    env:
      ENVIRONMENT: staging
    log_driver: json-file
    log_options:
      max-size: 50m
      max-file: "3"
    volumes:
      # TODO: this is identical btw/ production and staging.
      - "/srv/gitlab/secrets/ssh/ssh_host_dsa_key:/etc/gitlab/ssh_host_dsa_key:ro"
      - "/srv/gitlab/secrets/ssh/ssh_host_dsa_key.pub:/etc/gitlab/ssh_host_dsa_key.pub:ro"
      - "/srv/gitlab/secrets/ssh/ssh_host_key:/etc/gitlab/ssh_host_key:ro"
      - "/srv/gitlab/secrets/ssh/ssh_host_key.pub:/etc/gitlab/ssh_host_key.pub:ro"
      - "/srv/gitlab/secrets/ssh/ssh_host_ecdsa_key:/etc/gitlab/ssh_host_ecdsa_key:ro"
      - "/srv/gitlab/secrets/ssh/ssh_host_ecdsa_key.pub:/etc/gitlab/ssh_host_ecdsa_key.pub:ro"
      - "/srv/gitlab/secrets/ssh/ssh_host_ed25519_key:/etc/gitlab/ssh_host_ed25519_key:ro"
      - "/srv/gitlab/secrets/ssh/ssh_host_ed25519_key.pub:/etc/gitlab/ssh_host_ed25519_key.pub:ro"
      - "/srv/gitlab/secrets/ssh/ssh_host_rsa_key:/etc/gitlab/ssh_host_rsa_key:ro"
      - "/srv/gitlab/secrets/ssh/ssh_host_rsa_key.pub:/etc/gitlab/ssh_host_rsa_key.pub:ro"
      - "/srv/gitlab/secrets/gitlab-secrets.json:/etc/gitlab/gitlab-secrets.json"
      - "{{ serving_build_dir }}/gitlab-main/gitlab.rb:/etc/gitlab/gitlab.rb"
      - "/srv/gitlab/backup:/var/opt/gitlab/backups"
      - "/srv/gitlab/data/git-data:/var/opt/gitlab/git-data"
      - "/srv/gitlab/data/ssh_user_public_keys:/var/opt/gitlab/.ssh"
      - "/srv/gitlab/data/shared:/var/opt/gitlab/gitlab-rails/shared"
      - "/srv/gitlab/data/uploads:/var/opt/gitlab/gitlab-rails/uploads"
      - "/srv/gitlab/data/gitlab-ci/builds:/var/opt/gitlab/gitlab-ci/builds"
      # Below this line, things are different between gitlabprod and gitlabstaging
      - "/srv/gitlab/run/redis-socket-staging:/var/opt/gitlab/redis"
      - "/srv/gitlab/run/postgres-socket-staging:/var/opt/gitlab/postgresql"
    network_mode: "{{ docker_network_name }}"
