- include_vars: serving-vars.yml
  tags: always

- name: "Configuration directories"
  file:
    state: directory
    path: "{{ item | dirname }}"
  with_items: >-
      {{ [ serving_build_dir ]
         | union([
             serving_gitlab_rb_config_path | dirname
           ] | unique)
      }}

- name: "{{ serving_build_dir }}"
  git:
    repo: https://gitlab.com/epfl-idevfsd/gitlab-docker.git
    dest: '{{ serving_build_dir }}'

- name: "{{ serving_image }}"
  docker_image:
    name: "{{ serving_image }}"
    source: build
    build:
      pull: no     # Don't re-pull
      path: '{{ serving_build_dir }}/gitlab-main'

- name: "{{ serving_gitlab_rb_config_path }}"
  copy:
    dest: "{{ serving_gitlab_rb_config_path }}"
    content: '{{ lookup("template", "gitlab.rb.j2") }}'

- name: "{{ serving_hostname }}"
  docker_container:
    name: "{{ serving_hostname }}"
    image: "{{ serving_image }}"
    detach: yes
    restart_policy: unless-stopped
    env:
      ENVIRONMENT: staging
    log_driver: json-file
    log_options:
      max-size: 50m
      max-file: "3"
    volumes:
      - "/srv/gitlab/secrets/ssh/ssh_host_dsa_key:/etc/gitlab/ssh_host_dsa_key:ro"
      - "/srv/gitlab/secrets/ssh/ssh_host_dsa_key.pub:/etc/gitlab/ssh_host_dsa_key.pub:ro"
      - "/srv/gitlab/secrets/ssh/ssh_host_key:/etc/gitlab/ssh_host_key:ro"
      - "/srv/gitlab/secrets/ssh/ssh_host_key.pub:/etc/gitlab/ssh_host_key.pub:ro"
      - "/srv/gitlab/secrets/ssh/ssh_host_ecdsa_key:/etc/gitlab/ssh_host_ecdsa_key:ro"
      - "/srv/gitlab/secrets/ssh/ssh_host_ecdsa_key.pub:/etc/gitlab/ssh_host_ecdsa_key.pub:ro"
      - "/srv/gitlab/secrets/ssh/ssh_host_ed25519_key:/etc/gitlab/ssh_host_ed25519_key:ro"
      - "/srv/gitlab/secrets/ssh/ssh_host_ed25519_key.pub:/etc/gitlab/ssh_host_ed25519_key.pub:ro"
      - "/srv/gitlab/secrets/ssh/ssh_host_rsa_key:/etc/gitlab/ssh_host_rsa_key:ro"
      - "/srv/gitlab/secrets/ssh/ssh_host_rsa_key.pub:/etc/gitlab/ssh_host_rsa_key.pub:ro"
      - "/srv/gitlab/secrets/gitlab-secrets.json:/etc/gitlab/gitlab-secrets.json"
      - "{{ serving_gitlab_rb_config_path }}:/etc/gitlab/gitlab.rb"
      - "/srv/gitlab/backup:/var/opt/gitlab/backups"
      - "/srv/gitlab/data/git-data:/var/opt/gitlab/git-data"
      - "/srv/gitlab/data/ssh_user_public_keys:/var/opt/gitlab/.ssh"
      - "/srv/gitlab/data/shared:/var/opt/gitlab/gitlab-rails/shared"
      - "/srv/gitlab/data/uploads:/var/opt/gitlab/gitlab-rails/uploads"
      - "/srv/gitlab/data/gitlab-ci/builds:/var/opt/gitlab/gitlab-ci/builds"
      - "/srv/gitlab/run/redis-socket{{ socket_suffix }}:/var/opt/gitlab/redis"
      - "/srv/gitlab/run/postgres-socket{{ socket_suffix }}:/var/opt/gitlab/postgresql"
    network_mode: "{{ docker_network_name }}"
  vars:
    # TODO: this scheme is done this way for historical reasons.
    socket_suffix: >-
      {{ "-staging" if inventory_hostname == "gitlabstaging"
         else "" }}

- name: "Wait for {{ serving_hostname }} to become healthy"
  command: >
    docker inspect  --format '{{ "{{" }} .State.Health.Status }}' {{ serving_hostname }}
  register: _serving_healthy
  until: >
    ansible_check_mode or ("healthy" in _serving_healthy.stdout)
  retries: 20
  delay: 30
