- name: "Longhorn Helm charts"
  epfl_si.rancher.rancher_helm_chart:
    repository: rancher-charts
    chart: "{{ item.chart }}"
    namespace:
      name: "longhorn-system"   # Cannot be changed, as per
                                # https://github.com/longhorn/longhorn/blob/master/chart/README.md
      owned: true
      system: true
    values: >-
      {{ item.get("values", {}) }}
  with_items:
    - chart: longhorn-crd
    - chart: longhorn
      values:
        persistence:
          # Longhorn is *not* the default class; nfs-client is.
          defaultClass: false
        longhornManager:
          # We don't mind running Longhorn on the control
          # plane nodes:
          tolerations:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
              effect: "NoSchedule"
            - key: node-role.kubernetes.io/etcd
              operator: Exists
              effect: "NoExecute"
        defaultSettings:
          # Ditto:
          taintToleration: >-
            node-role.kubernetes.io/control-plane:NoSchedule;
            node-role.kubernetes.io/etcd:NoExecute
          # We want to explicitly declare which nodes can host
          # “replicas” on their “disks”, i.e. provide their disk space
          # to the cluster:
          createDefaultDiskLabeledNodes: true

- name: "Wait for nodes to register in Longhorn"
  retries: 5
  delay: 10
  epfl_si.k8s.k8s_info:
    api_version: longhorn.io/v1beta2
    kind: Node
    namespace: longhorn-system
  register: _longhorn_nodes
  until: _longhorn_nodes.resources | length >= 5

- with_inventory_hostnames: gitlab_rke2_vms
  when: >-
    hostvars[item].inventory_longhorn_storage_node is defined
  name: "Turn on Longhorn storage on desired nodes"
  epfl_si.k8s.k8s:
    definition:
      apiVersion: longhorn.io/v1beta2
      kind: Node
      metadata:
        name: "{{ item }}"
        namespace: longhorn-system
      spec:
        disks:
          longhorn:
            diskType: filesystem
            path: /var/lib/longhorn
            allowScheduling: true
