- tags: always
  include_vars: rke2-vars.yml

- include_tasks:
    file: _rancher_login.yml
    apply:
      tags:
      - rke2
      - rke2.login
  tags:
  - rke2
  - rke2.login

- include_tasks:
    file: metallb.yml
    apply:
      tags:
        - rke2
        - rke2.ingress
  tags:
    - rke2
    - rke2.ingress

- include_tasks:
    file: nfs-storage-class-uninstall.yml
    apply:
      tags:
        - rke2.storage.uninstall
  tags: rke2.storage.uninstall
  when: >-
    "rke2.storage.uninstall" in ansible_run_tags

- include_tasks:
    file: nfs-storage-class.yml
    apply:
      tags:
        - rke2
        - rke2.storage
  tags:
    - rke2
    - rke2.storage

- include_tasks:
    file: monitoring.yml
    apply:
      tags:
        - rke2
        - rke2.monitoring
  tags:
    - rke2
    - rke2.monitoring
