# Prometheus-(and-more-)as-a-service for your RKE2 cluster

- tags: always
  include_vars:
    name: monitoring_secrets
    file: monitoring-secrets.yml

- name: "`Secret/external-alertmanager-configs`"
  epfl_si.k8s.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: external-alertmanager-configs
        namespace: cattle-monitoring-system
      stringData:
        alertmanager-configs.yaml: |
          - scheme: https
            static_configs: ["targets": ["am.noc.fsd.team"]]
            basic_auth:
              username: "{{ monitoring_secrets.alertmanager.username }}"
              password: >-
                {{ monitoring_secrets.alertmanager.password
                | eyaml(monitoring_secrets.eyaml_keys) }}

- name: "`rancher-monitoring-crd` Helm chart"
  epfl_si.rancher.rancher_helm_chart:
    repository: rancher-charts
    chart: rancher-monitoring-crd
    namespace: kube-system

- name: "`rancher-monitoring` Helm chart"
  epfl_si.rancher.rancher_helm_chart:
    repository: rancher-charts
    chart: rancher-monitoring
    namespace:
      name: "cattle-monitoring-system"   # The chart won't let you choose another
      owned: true
      system: true
    values:
      rke2Etcd:
        enabled: true
      rke2ControllerManager:
        enabled: true
      rke2Scheduler:
        enabled: true
      rke2Proxy:
        enabled: true
      grafana:
        enabled: false
      alertmanager:
        enabled: false
      prometheus:
        prometheusSpec:
          # This is the “small T-shirt” configuration, whereby only one
          # Prometheus instance in the cluster monitors everything.
          serviceMonitorSelectorNilUsesHelmValues: false
          serviceMonitorSelector: {}
          podMonitorSelectorNilUsesHelmValues: false
          podMonitorSelector: {}
          ruleSelectorNilUsesHelmValues: false
          ruleSelector: {}
          # Optional: pick up alerts from other namespaces too
          ruleNamespaceSelector: {}
          serviceMonitorNamespaceSelector: {}
          podMonitorNamespaceSelector: {}
          # We want storage with that:
          storageSpec:
            volumeClaimTemplate:
              spec:
                storageClassName: nfs-client
                accessModes: ["ReadWriteMany"]
                resources:
                  requests:
                    storage: 50Gi   # Required, even though Kubernetes doesn't actually allocate anything
          # Connect to the team's external NOC.
          # https://github.com/rancher/charts/blob/main/charts/rancher-monitoring/values.yaml#L2361
          additionalAlertManagerConfigsSecret:
            name: external-alertmanager-configs
            key: alertmanager-configs.yaml
