# Prometheus-(and-more-)as-a-service for your RKE2 cluster

- name: "`rancher-monitoring-crd` Helm chart"
  epfl_si.rancher.rancher_helm_chart:
    repository: rancher-charts
    chart: rancher-monitoring-crd
    namespace: kube-system

- name: "`rancher-monitoring` Helm chart"
  epfl_si.rancher.rancher_helm_chart:
    repository: rancher-charts
    chart: rancher-monitoring
    namespace:
      name: "cattle-monitoring-system"   # The chart won't let you choose another
      owned: true
      system: true
    values:
      rke2Etcd:
        enabled: true
      rke2ControllerManager:
        enabled: true
      rke2Scheduler:
        enabled: true
      rke2Proxy:
        enabled: true
      grafana:
        enabled: false
      prometheus:
        prometheusSpec:
          # This is the “small T-shirt” configuration, whereby only one
          # Prometheus instance in the cluster monitors everything.
          serviceMonitorSelectorNilUsesHelmValues: false
          serviceMonitorSelector: {}
          podMonitorSelectorNilUsesHelmValues: false
          podMonitorSelector: {}
          ruleSelectorNilUsesHelmValues: false
          ruleSelector: {}
          # Optional: pick up alerts from other namespaces too
          ruleNamespaceSelector: {}
          serviceMonitorNamespaceSelector: {}
          podMonitorNamespaceSelector: {}
          storageSpec:
            volumeClaimTemplate:
              spec:
                storageClassName: nfs-client
                accessModes: ["ReadWriteMany"]
                resources:
                  requests:
                    storage: 50Gi   # Required, even though Kubernetes doesn't actually allocate anything
