- tags: always
  include_vars: ../../../vars/storage-vars.yml

- name: "`ClusterRepo/nfs-subdir-external-provisioner`"
  epfl_si.k8s.k8s:
    definition:
      apiVersion: catalog.cattle.io/v1
      kind: ClusterRepo
      metadata:
        name: nfs-subdir-external-provisioner
      spec:
        url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/

- name: "nfs-subdir-external-provisioner Helm chart"
  epfl_si.rancher.rancher_helm_chart:
    repository: nfs-subdir-external-provisioner
    chart: nfs-subdir-external-provisioner
    namespace:
      name: "{{ rke2_nfs_storage_namespace }}"
      owned: true
      system: true
    version: 4.0.18
    values:
      nfs:
        server: "{{ storage_nfs_share.server }}"
        path: "{{ storage_nfs_share.path }}"
      storageClass:
        defaultClass: true


- name: IP-level access to NAS (manual tasks)
  ansible.builtin.pause:
    prompt: |

      ⚠ Beyond this point, NFS traffic must be allowed from all nodes in the cluster to
      the following shares:

      {{ storage_nfs_share.server }}:{{ storage_nfs_share.path }}

      This requires the following tasks to be complete; both of which
      can be initiated at https://portal-xaas-its.epfl.ch/ → (login if required) →
      My Services → Service Broker:

      - unblock IP traffic to {{ storage_nfs_share.server }} in the DMZ firewall:
        from portal-xaas´ left-hand side menu → Virtual Machines → (search for each VM) →
        ⋮ → [DMZ] Reconfigure

      - whitelist all VMs in the share's IP access control list: again from portal-xaas´
        left-hand side menu → Resources → paste {{ storage_nfs_share.xaas_name }}
        in the search box on the top right and press Enter → ⋮ → Modify Access Policy

      And then you need to wait for something to happen in both cases (up to and including
      a human operator acting on a ServiceNow ticket.)

      💡 If you are feeling lazy, the next Ansible task requires all of the above to
       have been performed to completion (at least from the perspective of the
       {{ rke2_any_worker_node_of_this_cluster }} node); so you can just press C and
       Enter to continue now, and collect your “I told you so!” lecture here later:

- name: create `nfs-storageclass` subdirectory on the NAS
  delegate_to: "{{ rke2_any_worker_node_of_this_cluster }}"
  shell:
    cmd: |
      set -e -x
      mountdir="$(mktemp -d /tmp/mntXXXX)"
      mount -t nfs {{ storage_nfs_share.server }}:{{ storage_nfs_share.path }} "$mountdir" || {
        rmdir "$mountdir"
        exit 2
      }
      trap "umount $mountdir; rmdir $mountdir" EXIT

      wantdir="$mountdir/nfs-storageclass"
      test -d "$wantdir" && exit 0
      mkdir "$wantdir"
  register: _mkdir_nfs
  changed_when: >-
    "+ mkdir" in _mkdir_nfs.stderr
