- name: "Uninstall Helm chart"
  shell:
    cmd: |
      helm -n {{ rke2_nfs_storage_namespace }} delete nfs-subdir-external-provisioner || true
  register: _helm_uninstall_nfs
  changed_when: >-
    "release: not found" not in _helm_uninstall_nfs.stderr

- name: "`ClusterRepo/nfs-subdir-external-provisioner`"
  epfl_si.k8s.k8s:
    state: absent
    definition:
      apiVersion: catalog.cattle.io/v1
      kind: ClusterRepo
      metadata:
        name: nfs-subdir-external-provisioner

- name: "`Namespace/nfs-subdir-external-provisioner`"
  epfl_si.k8s.k8s:
    state: absent
    definition:
      kind: Namespace
      metadata:
        name: "{{ rke2_nfs_storage_namespace }}"
