- name: "`ClusterRepo/nfs-subdir-external-provisioner`"
  epfl_si.k8s.k8s:
    definition:
      apiVersion: catalog.cattle.io/v1
      kind: ClusterRepo
      metadata:
        name: nfs-subdir-external-provisioner
      spec:
        url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/

- name: "nfs-subdir-external-provisioner Helm chart"
  epfl_si.rancher.rancher_helm_chart:
    repository: nfs-subdir-external-provisioner
    chart: nfs-subdir-external-provisioner
    namespace:
      name: "{{ rke2_nfs_storage_namespace }}"
      owned: true
      system: true
    version: 4.0.18
    values:
      nfs:
        path: /svc1160_gitlab_test_app/nfs-storageclass
        server: nas-app-ma-nfs2.epfl.ch
      storageClass:
        defaultClass: true
