# This file is basically https://docs.rke2.io/upgrades/automated_upgrade
# translated into Ansible.

- tags: always
  include_vars: ../../vars/versions.yml

- name: system-upgrade-controller CRD
  epfl_si.k8s.k8s:
    definition: >-
      {{ lookup('url', _crd_objects_url, split_lines=False) | from_yaml_all }}
  vars:
    _crd_objects_url: >-
      https://github.com/rancher/system-upgrade-controller/releases/latest/download/crd.yaml

- name: system-upgrade-controller apparatus
  epfl_si.k8s.k8s:
    definition: >-
      {{ lookup('url', _other_objects_url, split_lines=False) | from_yaml_all }}
  vars:
    _other_objects_url: >-
      https://github.com/rancher/system-upgrade-controller/releases/latest/download/system-upgrade-controller.yaml

- name: Upgrade plans
  with_items:
  - name: control-plane
    rke2_upgrade: server
    operator: In
  - name: workers
    rke2_upgrade: agent
    operator: NotIn
    after: control-plane
  epfl_si.k8s.k8s:
    definition:
      apiVersion: upgrade.cattle.io/v1
      kind: Plan
      metadata:
        name: "{{ item.name }}"
        namespace: system-upgrade
        labels:
          rke2-upgrade: "{{ item.rke2_upgrade }}"
      spec: >-
        {{ _spec_yaml | from_yaml }}
  vars:
    _spec_yaml: |
      concurrency: 1
      nodeSelector:
        matchExpressions:
           - key: node-role.kubernetes.io/control-plane
             operator: {{ item.operator }}
             values: ["true"]
      {% if "after" in item %}
      prepare:
        image: rancher/rke2-upgrade
        args:
        - prepare
        - {{ item.after }}
      {% endif %}
      serviceAccountName: system-upgrade
      cordon: true
      drain:
        force: true
      upgrade:
        image: rancher/rke2-upgrade
      channel: https://update.rke2.io/v1-release/channels/stable
