# Create the cluster inside Rancher
#
# This is called by a special form in the playbook (an `include_role`
# task with the `tasks_from` argument; see
# https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_reuse_roles.html)
# so that these tasks happen *before* the cluster nodes are set up.
# This is unlike the role's `main.yml` flow, which runs *after* the
# nodes are ready and inserted into the cluster.

- tags: always
  include_role:
    name: epfl_si.rancher.cached_login

- tags: always
  include_vars: rke2-vars.yml

- tags: always
  include_vars: "../../../vars/{{ item }}"
  with_items:
    - versions.yml
    - ipam-vars.yml

- name: GitLab cluster in upstream Rancher
  epfl_si.k8s.k8s:
    definition:
      apiVersion: provisioning.cattle.io/v1
      kind: Cluster
      metadata:
        name: gitlab
        namespace: fleet-default
        annotations:
          ui.rancher/badge-color: transparent
          ui.rancher/badge-icon-text: GTL
      spec:
        kubernetesVersion: >-
          {{ rke2_version
          | default(rke2_updates_channel
                       | epfl_si.rancher.get_rke2_current_version) }}
        rkeConfig:
          etcd:
            snapshotRetention: 20
            snapshotScheduleCron: 0 */4 * * *
          machineGlobalConfig:
            cni: canal
            cluster-cidr: "{{ ipam_ipv4_pod_cidr     }},{{ ipam_ipv6_pod_cidr     }}"
            service-cidr: "{{ ipam_ipv4_service_cidr }},{{ ipam_ipv6_service_cidr }}"
          chartValues:
            rke2-canal:
              flannel:
                regexIface: "{{ rke2_main_interface_name_regex }}"
          upgradeStrategy:
            controlPlaneConcurrency: "1"
            workerConcurrency: "1"
            # I have no idea what drain options are. However, the clicky GUI
            # sets a few values as below, which *do* differ from the default
            # values:
            controlPlaneDrainOptions: >
              {{ _drain_options_as_the_gui_wants_them }}
            workerDrainOptions: >
              {{ _drain_options_as_the_gui_wants_them }}
        localClusterAuthEndpoint:
          enabled: true
  vars:
    _drain_options_as_the_gui_wants_them:
      gracePeriod: -1
      ignoreDaemonSets: true
      deleteEmptyDirData: true
      timeout: 120
  tags:
    - rke2
    - rke2.cluster
