# To edit the encrypted secrets below, you need eyaml installed.
# Familiarize yourself with
# https://puppet.com/blog/encrypt-your-data-using-hiera-eyaml first.
# The edit command goes like this,
#
#   ansible-deps-cache/bin/eyaml edit -d \
#       --pkcs7-public-key eyaml/epfl_gitlab.pkcs7.pem \
#       roles/rke2-gitlab/vars/tls-credentials.yml
#
# 💡 This *will not* decrypt anything for you because chances are, you
# don't need to decrypt secrets (YA RLY). For those cases where you
# do, wielding the private key from Keybase is left as an exercise to
# the reader.

eyaml_keys:
  priv: /keybase/team/epfl_gitlab/eyaml/private_key.pkcs7.pem
  pub: "{{ playbook_dir }}/eyaml/epfl_gitlab.pkcs7.pem"

gitlab:
  key: ENC[PKCS7,MIIIHQYJKoZIhvcNAQcDoIIIDjCCCAoCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAtkpAh9g0w6z4E9n2AHxboRbbJIbDTlPR/QwEQCew048GKBikIAK0T8P2xnh/iirzLqtQfEZqabzYEy+/s9r71+IJLm8AG+osAh5Whi914H7fBeyVYC1OyiLKunf8shfKJumoVTjkm+Thb7wL5pPxQ79kuNQ91nc088a75PKSAe0B6ZAEqgwN5jNAAQkQz63vTmtrpAQb8sEbr9RLD+ikRKoteRHiuDxNBLDTlhYXeB3StWOgUSbgCDYQnmeL1Rm5c4FzfCEDIHkWij39GQortkXTEHNEpNpcbxXGlIy9Nx+FRwisEQyNKU9Ku81JaqOx9qWqfZbq5Nik3pWx/wGtBzCCBt4GCSqGSIb3DQEHATAdBglghkgBZQMEASoEEGKJmdUw5/MNoJ0B9+i7/9CAggawyRNkyxqAz6zIYSWKKyZgGQwa7503ninLYk9ZnbwRNdE5nd7Nf/A09mZ54mKuU9+IEwy1ecSQ+Omku0N43TWfpsafpXPtNaFzVLhROMfkhdxCGeLkmwREkpWoMB28SBEJCHnB+UYst1c915OErSy0L+E8RhqT8pYivK9J9yKOU6KMHzpw+APYRdFKqyCd4XN3245OR5In1WLSWEYoZSNhjmUW4GXju7MlDyzN4SsB5rb3DJfFEji2U9+ggufANt/ZfVk7wvzISUe7xrwqqlp54F2G8PFwH3FJ3+mbFVqaq+DyUHj8uCCRBWOI8wfTxRg1RWkGiSu3EPY054tsmCwg3npNQjPVnMyT9Vi5jV7WiF9zcVS37TbgK2tG5hRwnfHFmaouH3ay1SFait/fZDvmOKC3QDV7YeD32opGqLd9BpM1ySBtlILhLpOr3OaKLEkZSniZNCZIic6+NdwYug5dtrVPzs9C0sOcvCLc3cXm7/qwSedEZQuNL3uZJd+BRVabvvnmL8fh+SUMxAl/TFYkp2g02CeWnS4Ene+Gu+CMc/Me7h/A7FJFqy9FdTJdprmZRCUJkUbhobLYSQZAbkNaIkeDjArK95qEAun377XAAiFIRWjeVbKetjCB/ZZnbczFhWS7xY9av29vQTkqR3QZrLmCl+w6UxvFtkrHOvkKdr6CYtTj+ByG7jBd8jwjup9X+3UB9jOFsucQJA/Et0pM2sd4I+kbYCCpqGTu0QWO7UsdVOPssIW9keBzhhWd7roUlsXJbR5X6EORJF3FT6sH5VmqPaIVXbKUu1O729xawCWguOYQsy/p5cEYaViHqZEQWQlC7tXbYVpTGWSBURIaIUnNJnKAfXfEJyZlmPy4/HMHbPeuVzI6a69Yyg1b494jU8tzVU0Fkm0bkSEv96363U+25/bBHXkjDQE55+T2hqKJVQ6B9E9ntVJ/s7Of8h7CpwAwj5IzLY7ArngLYZ36FWK09UONX1lZGWzJC3a64BgPkMSwDTir6CTlghAzdiUIlpiM/MGwrv/cDDegBUGomrnCzPKfRw03Ga50vamyNI7zReM6qD9bHniCeI+5JylmUhVAqlSbA2dvX2qMEe42Us+Lk3w/cyKmZPLHfHydmrozEGNhlQIiy4liH3HwwJ/5V32S1Jbto7n7StzPmg3Sbp2tDNpFsVPgbGYT3+tB5Xp9AZSvjeVBQmsTOmqJ0qucenVawr3Pv0474ZE722H2oAcLeOnChlSTsEdU9ANaqRu++VIbHoBca/f+CxmQdu3+8rAeT1bUwBD5tzNDpNJHrpCYiy5NL8fJ2V4BUYhX0F1vPvaN5gVFrY3mq70+oyfjZjHQ9VOvTXnu7mKvkgJXEGnRwku1eMgO4vd8+hGKOhZymhvnuP9wZPHlD48PaagsXiuijPwRTqPoXvkqEYMnW/lg5y3ZVn/1eidUq9dnIrNtz3Qh9AdfN6hXERMwXxT55fjIUwWSNfPo7Rt0ZU2Fr7LeRdkS6iSDhPN4fiEmnIg8NRRdNhrrFyaYpEfMLYI5Dsyg0i8pLAyMx7g4s5OPnztCO+MGIfcSWlM6LNxoBJJisbamYMVH+ZMz40kfwHxshcjmu2vbnFed0ps4eQqsa2FgC0uUQrc1u8ANbm6oTJdq7G/NNu9r9RkhlBRhqcgMUvalyhGYgN15e633H10cQRhy+dRlnITu2hLNqSop+lN4u7oaEYe0ljCt80Jd8r8t9nBlVhvJqFREW4vzGxEb2lwlCtFl/lkP+wd6lHNv5d47f+kIbOiVQ+c54l9ywxfBFmraWnRepwb9nWe+guC510zp9BAlgl6opPwLKYgU0qb4b1G9645gvbvqxEojqFk9kOUSi8jTjheTQy4/0NreRhd53wkjKq3moFd0PGAyyBhycJjrayFKz9I665MJ/TDmdgLlTVm3MQHR7440vs5eWSsscQ060uhfy9lp3plvoUDiXLX2V4NUEnkcSunuyVwcPekPOALXA/BRf+bgYb2eREAGs5iZheAS5Sji8CTMczAKi9qWlzkHTAvP2Wyut2OvQUL8+xTuYgYN+gtqohjUfjr0ymhNMDSuITRUqzUPjEAIDui7A3lTWe+UV31VTjGIa9w3e/nYehOuPxt+DrXmNxuOjlXMfaaoHVYD8EaJrya+0sDSeGmsRpWGj9HsByfXwe5j+icTa3+hwAc3yPduzqpMMmytUvPpiCivZhI/uzDfzQ4Ho+RF2hF7r7qOTnWSUWdoISU3XBbWpcPAkSlQ3g5Z5+NfbmtJAx9YiO2+zUg=]
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIHGDCCBgCgAwIBAgIQDQNtFTDzDnyYu/gLa3+R2zANBgkqhkiG9w0BAQsFADBZ
    MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMTMwMQYDVQQDEypE
    aWdpQ2VydCBHbG9iYWwgRzIgVExTIFJTQSBTSEEyNTYgMjAyMCBDQTEwHhcNMjUx
    MDE4MDAwMDAwWhcNMjYxMDIwMjM1OTU5WjBvMQswCQYDVQQGEwJDSDERMA8GA1UE
    BxMITGF1c2FubmUxNDAyBgNVBAoMK8OJY29sZSBwb2x5dGVjaG5pcXVlIGbDqWTD
    qXJhbGUgZGUgTGF1c2FubmUxFzAVBgNVBAMTDmdpdGxhYi5lcGZsLmNoMIIBIjAN
    BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAu/sMOmo/Z6DKSaOJDzKWoe1tfx08
    Z1MBsjs6O2QU6G03zDk8IZEZVz+3kaIipilNI9Jwq9Bcaa5UrMltG6Z8dnZmbQrX
    J0J0613Kl8DCXR2BOq6kYYqxAb2UIbnIBPfYnNuybUSmWss8PTf441sYxuyAFR58
    OQ5VbyYBPukviccHXeC0UZ7Zv2zMT5CZHmAQeS1ZG0XuPesigYeQc9JNiASvvOn0
    opkwQl4ZfGGNZySzG8dLZRvJ6maGa0HG2RQpu8UIcQqFlQGZnInINxoEK6l3eXXx
    n947IeNtavMbs0xRTIaQ2RJLBUDRmrCb30gjXoE19A273gUlDLa8DvqvgwIDAQAB
    o4IDxDCCA8AwHwYDVR0jBBgwFoAUdIWAwGbH3zfez70pN6oDHb7tzRcwHQYDVR0O
    BBYEFCWzG7tHRUZBzugTwWGB+4d8thzjMF4GA1UdEQRXMFWCDmdpdGxhYi5lcGZs
    LmNoghNnaXRsYWItdGVzdC5lcGZsLmNoghNnaXRsYWItbmV4dC5lcGZsLmNoghln
    aXRsYWItcHJvbWV0aGV1cy5lcGZsLmNoMD4GA1UdIAQ3MDUwMwYGZ4EMAQICMCkw
    JwYIKwYBBQUHAgEWG2h0dHA6Ly93d3cuZGlnaWNlcnQuY29tL0NQUzAOBgNVHQ8B
    Af8EBAMCBaAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwgZ8GA1UdHwSBlzCBlDBIoEag
    RIZCaHR0cDovL2NybDMuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0R2xvYmFsRzJUTFNS
    U0FTSEEyNTYyMDIwQ0ExLTEuY3JsMEigRqBEhkJodHRwOi8vY3JsNC5kaWdpY2Vy
    dC5jb20vRGlnaUNlcnRHbG9iYWxHMlRMU1JTQVNIQTI1NjIwMjBDQTEtMS5jcmww
    gYcGCCsGAQUFBwEBBHsweTAkBggrBgEFBQcwAYYYaHR0cDovL29jc3AuZGlnaWNl
    cnQuY29tMFEGCCsGAQUFBzAChkVodHRwOi8vY2FjZXJ0cy5kaWdpY2VydC5jb20v
    RGlnaUNlcnRHbG9iYWxHMlRMU1JTQVNIQTI1NjIwMjBDQTEtMS5jcnQwDAYDVR0T
    AQH/BAIwADCCAX0GCisGAQQB1nkCBAIEggFtBIIBaQFnAHUA1219ENGn9XfCx+lf
    1wC/+YLJM1pl4dCzAXMXwMjFaXcAAAGZ9jP7ewAABAMARjBEAiAHnNCJDBliP0wh
    k0fiF4FW9FxadpGaBmUpIf3wgvtzHgIgceef4Fwx7CWtWHgwl9BUCet/LWcuc3ql
    J4EnVeiUhwoAdQDCMX5XRRmjRe5/ON6ykEHrx8IhWiK/f9W1rXaa2Q5SzQAAAZn2
    M/u8AAAEAwBGMEQCIHd2pM/osLKzHrFb8gGp+fcqkiZxeeFhesIQLCqqwbXfAiAT
    Dqa+nxAADSh9OOIce+ZBDQZAiSoAzDnSD6jWJupa3wB3AJROQ4f67MHvgfMZJCao
    GGUBx9NfOAIBP3JnfVU3LhnYAAABmfYz+9MAAAQDAEgwRgIhAJP7EkKnKIw6TPJO
    +tpFGyHi2LWy2xlilBWAFnXm6KZ+AiEAsg+R5PtYvpgbpsW1diEeqVLpQifb6fDu
    6My6mivLyREwDQYJKoZIhvcNAQELBQADggEBAGqbI6EGUvVbFrhtwKYiY1aQAVvo
    dDksVON3RQSx25ARVD0uV8cbCfQmBl1pSw70ycekEG0k/CEco45+Ah9tdarSZloM
    fC5O0V8IkB+4c81GTSLMcU0TV6GE6IPeaZGLOGymSAQGM0IyYj1TPlbzs/Spndyy
    4LXZ3f3XaClMpfiWA7U514pyaQLeBGJIALstTnamBc0L+s//02Ka7opSXsEg2X8l
    eaGW+2XtOZ3DoujJuN2hLGBkOfzQTDWuJ4XBWFFqX+EGF+Q20WzCOohFDYBUd/X0
    NKtWvfhlzeRA3ZEWJ08xlkbFPf73rBsVgxnr3ReuFDNJDjkNGkxDlu7y9EI=
    -----END CERTIFICATE-----

digicert:
  operational_ca_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIEyDCCA7CgAwIBAgIQDPW9BitWAvR6uFAsI8zwZjANBgkqhkiG9w0BAQsFADBh
    MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
    d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBH
    MjAeFw0yMTAzMzAwMDAwMDBaFw0zMTAzMjkyMzU5NTlaMFkxCzAJBgNVBAYTAlVT
    MRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxMzAxBgNVBAMTKkRpZ2lDZXJ0IEdsb2Jh
    bCBHMiBUTFMgUlNBIFNIQTI1NiAyMDIwIENBMTCCASIwDQYJKoZIhvcNAQEBBQAD
    ggEPADCCAQoCggEBAMz3EGJPprtjb+2QUlbFbSd7ehJWivH0+dbn4Y+9lavyYEEV
    cNsSAPonCrVXOFt9slGTcZUOakGUWzUb+nv6u8W+JDD+Vu/E832X4xT1FE3LpxDy
    FuqrIvAxIhFhaZAmunjZlx/jfWardUSVc8is/+9dCopZQ+GssjoP80j812s3wWPc
    3kbW20X+fSP9kOhRBx5Ro1/tSUZUfyyIxfQTnJcVPAPooTncaQwywa8WV0yUR0J8
    osicfebUTVSvQpmowQTCd5zWSOTOEeAqgJnwQ3DPP3Zr0UxJqyRewg2C/Uaoq2yT
    zGJSQnWS+Jr6Xl6ysGHlHx+5fwmY6D36g39HaaECAwEAAaOCAYIwggF+MBIGA1Ud
    EwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFHSFgMBmx9833s+9KTeqAx2+7c0XMB8G
    A1UdIwQYMBaAFE4iVCAYlebjbuYP+vq5Eu0GF485MA4GA1UdDwEB/wQEAwIBhjAd
    BgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwdgYIKwYBBQUHAQEEajBoMCQG
    CCsGAQUFBzABhhhodHRwOi8vb2NzcC5kaWdpY2VydC5jb20wQAYIKwYBBQUHMAKG
    NGh0dHA6Ly9jYWNlcnRzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydEdsb2JhbFJvb3RH
    Mi5jcnQwQgYDVR0fBDswOTA3oDWgM4YxaHR0cDovL2NybDMuZGlnaWNlcnQuY29t
    L0RpZ2lDZXJ0R2xvYmFsUm9vdEcyLmNybDA9BgNVHSAENjA0MAsGCWCGSAGG/WwC
    ATAHBgVngQwBATAIBgZngQwBAgEwCAYGZ4EMAQICMAgGBmeBDAECAzANBgkqhkiG
    9w0BAQsFAAOCAQEAkPFwyyiXaZd8dP3A+iZ7U6utzWX9upwGnIrXWkOH7U1MVl+t
    wcW1BSAuWdH/SvWgKtiwla3JLko716f2b4gp/DA/JIS7w7d7kwcsr4drdjPtAFVS
    slme5LnQ89/nD/7d+MS5EHKBCQRfz5eeLjJ1js+aWNJXMX43AYGyZm0pGrFmCW3R
    bpD0ufovARTFXFZkAdl9h6g4U5+LXUZtXMYnhIHUfoyMo5tS58aI7Dd8KvvwVVo4
    chDYABPPTHPbqjc1qCmBaZx2vN4Ye5DUys/vZwP9BFohFrH/6j/f3IL16/RZkiMN
    JCqVJUzKoZHm1Lesh3Sz8W2jmdv51b2EQJ8HmA==
    -----END CERTIFICATE-----
